decompiler: RuleLoadVarnode Class Reference
RuleLoadVarnode Class Reference
Convert LOAD operations using a constant offset to COPY.
Public Member Functions
RuleLoadVarnode (const string &g)
Constructor.
virtual Rule * clone (const ActionGroupList &grouplist) const
Clone the Rule.
virtual void getOpList (vector< uint4 > &oplist) const
List of op codes this rule operates on.
virtual int4 applyOp (PcodeOp *op, Funcdata &data)
Attempt to apply this Rule.
Public Member Functions inherited from Rule
Rule (const string &g, uint4 fl, const string &nm)
Construct given group, properties name.
virtual ~Rule (void)
Destructor.
const string & getName (void) const
Return the name of this Rule.
const string & getGroup (void) const
Return the group this Rule belongs to.
uint4 getNumTests (void)
Get number of attempted applications.
uint4 getNumApply (void)
Get number of successful applications.
void setBreak (uint4 tp)
Set a breakpoint on this Rule.
void clearBreak (uint4 tp)
Clear a breakpoint on this Rule.
void clearBreakPoints (void)
Clear all breakpoints on this Rule.
void turnOnWarnings (void)
Enable warnings for this Rule.
void turnOffWarnings (void)
Disable warnings for this Rule.
bool isDisabled (void) const
Return true if this Rule is disabled.
void setDisable (void)
Disable this Rule (within its pool)
void clearDisable (void)
Enable this Rule (within its pool)
bool checkActionBreak (void)
Check if an action breakpoint is turned on.
uint4 getBreakPoint (void) const
Return breakpoint toggles.
virtual void reset (Funcdata &data)
Reset this Rule.
virtual void resetStats (void)
Reset Rule statistics.
virtual void printStatistics (ostream &s) const
Print statistics for this Rule.
Static Private Member Functions
static AddrSpace * correctSpacebase (Architecture *glb, Varnode *vn, AddrSpace *spc)
Return associated space if given Varnode is an active spacebase.
static AddrSpace * vnSpacebase (Architecture *glb, Varnode *vn, uintb &val, AddrSpace *spc)
Check if given Varnode is spacebase + a constant.
static AddrSpace * checkSpacebase (Architecture *glb, PcodeOp *op, uintb &offoff)
Check if STORE or LOAD is off of a spacebase + constant.
Friends
class RuleStoreVarnode
Additional Inherited Members
Public Types inherited from Rule
enum typeflags { type_disable = 1, rule_debug = 2, warnings_on = 4, warnings_given = 8 }
Properties associated with a Rule.
Detailed Description
Convert LOAD operations using a constant offset to COPY.
The pointer can either be a constant offset into the LOAD's specified address space, or it can be a spacebase register plus an offset, in which case it points into the spacebase register's address space.
Member Function Documentation
int4 RuleLoadVarnode::applyOp (PcodeOp * op, Funcdata & data) virtual
Attempt to apply this Rule.
This method contains the main logic for applying the Rule. It must use a given PcodeOp as the point at which the Rule applies. If it does apply, changes are made directly to the function and 1 (non-zero) is returned, otherwise 0 is returned.
Parameters
op is the given PcodeOp where the Rule may apply
data is the function to which to apply
Reimplemented from Rule.
References AddrSpace::addressToByte(), Varnode::clearSpacebasePlaceholder(), CPUI_COPY, Funcdata::getArch(), Funcdata::getCallSpecs(), PcodeOp::getOut(), Varnode::getSize(), AddrSpace::getWordSize(), Varnode::isSpacebasePlaceholder(), Varnode::loneDescend(), Funcdata::newVarnode(), Funcdata::opRemoveInput(), Funcdata::opSetInput(), Funcdata::opSetOpcode(), and FuncCallSpecs::resolveSpacebaseRelative().
AddrSpace * RuleLoadVarnode::checkSpacebase (Architecture * glb, PcodeOp * op, uintb & offoff) static private
Check if STORE or LOAD is off of a spacebase + constant.
If so return the associated space and pass back the offset
Parameters
glb is the address space manager
op is the STORE or LOAD PcodeOp
offoff is a reference to where the offset should get passed back
Returns
the associated space or NULL
References PcodeOp::code(), CPUI_SEGMENTOP, Varnode::getAddr(), Varnode::getDef(), PcodeOp::getIn(), Varnode::getOffset(), Address::getSpaceFromConst(), Varnode::isConstant(), and Varnode::isWritten().
Referenced by RuleStoreVarnode::applyOp().
virtual Rule* RuleLoadVarnode::clone (const ActionGroupList & grouplist) const inline virtual
Clone the Rule.
If this Rule is a member of one of the groups in the grouplist, this returns a clone of the Rule, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Rule or NULL
Implements Rule.
References RuleStoreVarnode::applyOp(), ActionGroupList::contains(), AddTreeState::data, Rule::getGroup(), and RuleStoreVarnode::getOpList().
AddrSpace * RuleLoadVarnode::correctSpacebase (Architecture * glb, Varnode * vn, AddrSpace * spc) static private
Return associated space if given Varnode is an active spacebase.
The Varnode should be a spacebase register input to the function or a constant, and it should get loaded from the correct space.
Parameters
glb is the address space manager
vn is the given Varnode
spc is the address space being loaded from
Returns
the associated space or NULL if the Varnode is not of the correct form
References Varnode::getAddr(), AddrSpace::getContain(), Varnode::getSize(), Architecture::getSpaceBySpacebase(), Varnode::isConstant(), Varnode::isInput(), and Varnode::isSpacebase().
void RuleLoadVarnode::getOpList (vector< uint4 > & oplist) const virtual
List of op codes this rule operates on.
Populate the given array with all possible OpCodes this Rule might apply to. By default, this method returns all possible OpCodes
Parameters
oplist is the array to populate
Reimplemented from Rule.
References CPUI_LOAD.
AddrSpace * RuleLoadVarnode::vnSpacebase (Architecture * glb, Varnode * vn, uintb & val, AddrSpace * spc) static private
Check if given Varnode is spacebase + a constant.
If it is, pass back the constant and return the associated space
Parameters
glb is the address space manager
vn is the given Varnode
val is the reference for passing back the constant
spc is the space being loaded from
Returns
the associated space or NULL
References PcodeOp::code(), CPUI_INT_ADD, Varnode::getDef(), PcodeOp::getIn(), Varnode::getOffset(), Varnode::isConstant(), and Varnode::isWritten().
The documentation for this class was generated from the following files:
ruleaction.hh
ruleaction.cc