decompiler: XmlArchitecture Class Reference
XmlArchitecture Class Reference
An Architecture that loads executables using an XML format.
#include <xml_arch.hh>
Public Member Functions
virtual void saveXml (ostream &s) const
virtual void restoreXml (DocumentStorage &store)
Restore the Architecture state from an XML stream.
XmlArchitecture (const string &fname, const string &targ, ostream *estream)
Constructor.
Public Member Functions inherited from SleighArchitecture
SleighArchitecture (const string &fname, const string &targ, ostream *estream)
Construct given executable file.
const string & getFilename (void) const
Get the executable filename.
const string & getTarget (void) const
Get the language id of the active processor.
void saveXmlHeader (ostream &s) const
Write out (as XML) basic attributes of the active executable.
void restoreXmlHeader (const Element *el)
Restore from XML basic attributes of an executable.
virtual void printMessage (const string &message) const
Print an error message to console.
virtual string getDescription (void) const
Get a string describing this architecture.
Public Member Functions inherited from Architecture
Architecture (void)
Construct an uninitialized Architecture.
void init (DocumentStorage &store)
Load the image and configure architecture.
void resetDefaultsInternal (void)
Reset default values for options specific to Architecture.
void resetDefaults (void)
Reset defaults values for options owned by this.
ProtoModel * getModel (const string &nm) const
Get a specific PrototypeModel.
bool hasModel (const string &nm) const
Does this Architecture have a specific PrototypeModel.
bool highPtrPossible (const Address &loc, int4 size) const
Are pointers possible to the given location?
AddrSpace * getSpaceBySpacebase (const Address &loc, int4 size) const
Get space associated with a spacebase register.
const LanedRegister * getLanedRegister (const Address &loc, int4 size) const
Get LanedRegister associated with storage.
int4 getMinimumLanedRegisterSize (void) const
Get the minimum size of a laned register in bytes.
void setDefaultModel (const string &nm)
Set the default PrototypeModel.
void clearAnalysis (Funcdata *fd)
Clear analysis specific to a function.
void readLoaderSymbols (const string &delim)
Read any symbols from loader into database.
void collectBehaviors (vector< OpBehavior * > &behave) const
Provide a list of OpBehavior objects.
SegmentOp * getSegmentOp (AddrSpace *spc) const
Retrieve the segment op for the given space if any.
void setPrototype (const PrototypePieces &pieces)
Set the prototype for a particular function.
void setPrintLanguage (const string &nm)
Establish a particular output language.
void globalify (void)
Mark all spaces as global.
void restoreFlowOverride (const Element *el)
Set flow overrides from XML.
virtual ~Architecture (void)
Destructor.
virtual void nameFunction (const Address &addr, string &name) const
Pick a default name for a function.
Public Member Functions inherited from AddrSpaceManager
AddrSpaceManager (void)
Construct an empty address space manager.
virtual ~AddrSpaceManager (void)
Destroy the manager.
int4 getDefaultSize (void) const
Get size of addresses for the default space.
AddrSpace * getSpaceByName (const string &nm) const
Get address space by name.
AddrSpace * getSpaceByShortcut (char sc) const
Get address space from its shortcut.
AddrSpace * getIopSpace (void) const
Get the internal pcode op space.
AddrSpace * getFspecSpace (void) const
Get the internal callspec space.
AddrSpace * getJoinSpace (void) const
Get the joining space.
AddrSpace * getStackSpace (void) const
Get the stack space for this processor.
AddrSpace * getUniqueSpace (void) const
Get the temporary register space for this processor.
AddrSpace * getDefaultCodeSpace (void) const
Get the default address space of this processor.
AddrSpace * getDefaultDataSpace (void) const
Get the default address space where data is stored.
AddrSpace * getConstantSpace (void) const
Get the constant space.
Address getConstant (uintb val) const
Get a constant encoded as an Address.
Address createConstFromSpace (AddrSpace *spc) const
Create a constant address encoding an address space.
Address resolveConstant (AddrSpace *spc, uintb val, int4 sz, const Address &point, uintb &fullEncoding) const
Resolve a native constant into an Address.
int4 numSpaces (void) const
Get the number of address spaces for this processor.
AddrSpace * getSpace (int4 i) const
Get an address space via its index.
AddrSpace * getNextSpaceInOrder (AddrSpace *spc) const
Get the next contiguous address space.
JoinRecord * findAddJoin (const vector< VarnodeData > &pieces, uint4 logicalsize)
Get (or create) JoinRecord for pieces.
JoinRecord * findJoin (uintb offset) const
Find JoinRecord for offset in the join space.
void setDeadcodeDelay (AddrSpace *spc, int4 delaydelta)
Set the deadcodedelay for a specific space.
void truncateSpace (const TruncationTag &tag)
Mark a space as truncated from its original size.
Address constructFloatExtensionAddress (const Address &realaddr, int4 realsize, int4 logicalsize)
Build a logically lower precision storage location for a bigger floating point register.
Address constructJoinAddress (const Translate *translate, const Address &hiaddr, int4 hisz, const Address &loaddr, int4 losz)
Build a logical whole from register pairs.
void renormalizeJoinAddress (Address &addr, int4 size)
Make sure a possibly offset join address has a proper JoinRecord.
Private Member Functions
virtual void buildLoader (DocumentStorage &store)
Build the LoadImage object and load the executable image.
virtual void postSpecFile (void)
Read in image information (which uses translator)
Private Attributes
long adjustvma
The amount to adjust the virtual memory address.
Additional Inherited Members
Static Public Member Functions inherited from SleighArchitecture
static string normalizeProcessor (const string &nm)
Try to recover a language id processor field.
static string normalizeEndian (const string &nm)
Try to recover a language id endianess field.
static string normalizeSize (const string &nm)
Try to recover a language id size field.
static string normalizeArchitecture (const string &nm)
Try to recover a language id string.
static void scanForSleighDirectories (const string &rootpath)
Scan directories for SLEIGH specification files.
static void shutdown (void)
Shutdown this SleighArchitecture and free all resources.
Public Attributes inherited from Architecture
string archid
ID string uniquely describing this architecture.
int4 trim_recurse_max
How many levels to let parameter trims recurse.
int4 max_implied_ref
Maximum number of references to an implied var.
int4 max_term_duplication
Max terms duplicated without a new variable.
int4 max_basetype_size
Maximum size of an "integer" type before creating an array type.
int4 min_funcsymbol_size
Minimum size of a function symbol.
bool aggressive_ext_trim
Aggressively trim inputs that look like they are sign extended.
bool readonlypropagate
true if readonly values should be treated as constants
bool infer_pointers
True if we should infer pointers from constants that are likely addresses.
vector< AddrSpace * > inferPtrSpaces
Set of address spaces in which a pointer constant is inferable.
int4 funcptr_align
How many bits of alignment a function ptr has.
uint4 flowoptions
options passed to flow following engine
uint4 max_instructions
Maximum instructions that can be processed in one function.
int4 alias_block_level
Aliases blocked by 0=none, 1=struct, 2=array, 3=all.
vector< Rule * > extra_pool_rules
Extra rules that go in the main pool (cpu specific, experimental)
Database * symboltab
Memory map of global variables and functions.
ContextDatabase * context
Map from addresses to context settings.
map< string, ProtoModel * > protoModels
Parsed forms of possible prototypes.
ProtoModel * defaultfp
Parsed form of default prototype.
VarnodeData defaultReturnAddr
Default storage location of return address (for current function)
ProtoModel * evalfp_current
Function proto to use when evaluating current function.
ProtoModel * evalfp_called
Function proto to use when evaluating called functions.
TypeFactory * types
List of types for this binary.
const Translate * translate
Translation method for this binary.
LoadImage * loader
Method for loading portions of binary.
PcodeInjectLibrary * pcodeinjectlib
Pcode injection manager.
RangeList nohighptr
Ranges for which high-level pointers are not possible.
CommentDatabase * commentdb
Comments for this architecture.
StringManager * stringManager
Manager of decoded strings.
ConstantPool * cpool
Deferred constant values.
PrintLanguage * print
Current high-level language printer.
vector< PrintLanguage * > printlist
List of high-level language printers supported.
OptionDatabase * options
Options that can be configured.
vector< TypeOp * > inst
Registered p-code instructions.
UserOpManage userops
Specifically registered user-defined p-code ops.
vector< PreferSplitRecord > splitrecords
registers that we would prefer to see split for this processor
vector< LanedRegister > lanerecords
Vector registers that have preferred lane sizes.
ActionDatabase allacts
Actions that can be applied in this architecture.
bool loadersymbols_parsed
True if loader symbols have been read.
Static Public Attributes inherited from SleighArchitecture
static FileManage specpaths
Known directories that contain .ldefs files.
Protected Member Functions inherited from SleighArchitecture
virtual Translate * buildTranslator (DocumentStorage &store)
Build the Translator object.
virtual PcodeInjectLibrary * buildPcodeInjectLibrary (void)
Build the injection library.
virtual void buildSpecFile (DocumentStorage &store)
Load any relevant specification files.
virtual void modifySpaces (Translate *trans)
Modify address spaces as required by this Architecture.
virtual void resolveArchitecture (void)
Figure out the processor and compiler of the target executable.
Protected Member Functions inherited from Architecture
void addSpacebase (AddrSpace *basespace, const string &nm, const VarnodeData &ptrdata, int4 truncSize, bool isreversejustified, bool stackGrowth)
Create a new space and associated pointer.
void addNoHighPtr (const Range &rng)
Add a new region where pointers do not exist.
virtual Scope * buildDatabase (DocumentStorage &store)
Build the database and global scope for this executable.
virtual void buildTypegrp (DocumentStorage &store)
Build the data-type factory/container.
virtual void buildCommentDB (DocumentStorage &store)
Build the comment database.
virtual void buildStringManager (DocumentStorage &store)
Build the string manager.
virtual void buildConstantPool (DocumentStorage &store)
Build the constant pool.
virtual void buildInstructions (DocumentStorage &store)
Register the p-code operations.
virtual void buildAction (DocumentStorage &store)
Build the Action framework.
virtual void buildContext (DocumentStorage &store)
Build the Context database.
void restoreFromSpec (DocumentStorage &store)
Fully initialize the Translate object.
void fillinReadOnlyFromLoader (void)
Load info about read-only sections.
void initializeSegments ()
Set up segment resolvers.
void cacheAddrSpaceProperties (void)
Calculate some frequently used space properties and cache them.
void parseProcessorConfig (DocumentStorage &store)
Apply processor specific configuration.
void parseCompilerConfig (DocumentStorage &store)
Apply compiler specific configuration.
void parseExtraRules (DocumentStorage &store)
Apply any Rule tags.
void parseDynamicRule (const Element *el)
Apply details of a dynamic Rule object.
ProtoModel * parseProto (const Element *el)
Build a proto-type model from an XML tag.
void parseProtoEval (const Element *el)
Apply prototype evaluation configuration.
void parseDefaultProto (const Element *el)
Apply default prototype model configuration.
void parseGlobal (const Element *el)
Apply global space configuration.
void addOtherSpace (void)
Add OTHER space and all of its overlays to the symboltab.
void parseReadOnly (const Element *el)
Apply read-only region configuration.
void parseVolatile (const Element *el)
Apply volatile region configuration.
void parseReturnAddress (const Element *el)
Apply return address configuration.
void parseIncidentalCopy (const Element *el)
Apply incidental copy configuration.
void parseLaneSizes (const Element *el)
Apply lane size configuration.
void parseStackPointer (const Element *el)
Apply stack pointer configuration.
void parseDeadcodeDelay (const Element *el)
Apply dead-code delay configuration.
void parseInferPtrBounds (const Element *el)
Apply pointer inference bounds.
void parseFuncPtrAlign (const Element *el)
Apply function pointer alignment configuration.
void parseSpacebase (const Element *el)
Create an additional indexed space.
void parseNoHighPtr (const Element *el)
Apply memory alias configuration.
void parsePreferSplit (const Element *el)
Designate registers to be split.
void parseAggressiveTrim (const Element *el)
Designate how to trim extension p-code ops.
Protected Member Functions inherited from AddrSpaceManager
AddrSpace * restoreXmlSpace (const Element *el, const Translate *trans)
Add a space to the model based an on XML tag.
void restoreXmlSpaces (const Element *el, const Translate *trans)
Restore address spaces in the model from an XML tag.
void setDefaultCodeSpace (int4 index)
Set the default address space (for code)
void setDefaultDataSpace (int4 index)
Set the default address space for data.
void setReverseJustified (AddrSpace *spc)
Set reverse justified property on this space.
void assignShortcut (AddrSpace *spc)
Select a shortcut character for a new space.
void markNearPointers (AddrSpace *spc, int4 size)
Mark that given space can be accessed with near pointers.
void insertSpace (AddrSpace *spc)
Add a new address space to the model.
void copySpaces (const AddrSpaceManager *op2)
Copy spaces from another manager.
void addSpacebasePointer (SpacebaseSpace *basespace, const VarnodeData &ptrdata, int4 truncSize, bool stackGrowth)
Set the base register of a spacebase space.
void insertResolver (AddrSpace *spc, AddressResolver *rsolv)
Override the base resolver for a space.
void setInferPtrBounds (const Range &range)
Set the range of addresses that can be inferred as pointers.
JoinRecord * findJoinInternal (uintb offset) const
Find JoinRecord for offset in the join space.
Static Protected Member Functions inherited from SleighArchitecture
static void collectSpecFiles (ostream &errs)
Gather specification files in normal locations.
Protected Attributes inherited from SleighArchitecture
ostream * errorstream
Error stream associated with this SleighArchitecture.
Detailed Description
An Architecture that loads executables using an XML format.
Constructor & Destructor Documentation
XmlArchitecture::XmlArchitecture (const string & fname, const string & targ, ostream * estream)
Constructor.
This just wraps the base constructor
Parameters
fname is the path to the executable file (containing XML)
targ is the (optional) language id
estream is the stream to use for the error console
References adjustvma.
Member Function Documentation
void XmlArchitecture::buildLoader (DocumentStorage & store) private virtual
Build the LoadImage object and load the executable image.
Parameters
store may hold configuration information
Implements Architecture.
References Document::getRoot(), DocumentStorage::getTag(), DocumentStorage::openDocument(), and DocumentStorage::registerTag().
void XmlArchitecture::restoreXml (DocumentStorage & store) virtual
Restore the Architecture state from an XML stream.
Read in all the sub-component state from a <save_state> XML tag When adding stuff to this BEWARE: The spec file has already initialized stuff
Parameters
store is document store containing the parsed root tag
Reimplemented from Architecture.
References adjustvma, Element::getAttributeValue(), Element::getChildren(), DocumentStorage::getTag(), Architecture::init(), DocumentStorage::registerTag(), Architecture::restoreXml(), and SleighArchitecture::restoreXmlHeader().
void XmlArchitecture::saveXml (ostream & s) const virtual
Prepend extra stuff to specify binary file and spec
Parameters
s is the stream to write to
Reimplemented from Architecture.
References a_v_u(), adjustvma, Architecture::loader, Architecture::saveXml(), TypeFactory::saveXmlCoreTypes(), SleighArchitecture::saveXmlHeader(), and Architecture::types.
The documentation for this class was generated from the following files:
xml_arch.hh
xml_arch.cc