decompiler: WidenerFull Class Reference
WidenerFull Class Reference
Class for doing normal widening.
#include <rangeutil.hh>
Public Member Functions
WidenerFull (void)
Constructor with default iterations.
WidenerFull (int4 wide, int4 full)
Constructor specifying iterations.
virtual int4 determineIterationReset (const ValueSet &valueSet)
Upon entering a fresh partition, determine how the given ValueSet count should be reset.
virtual bool checkFreeze (const ValueSet &valueSet)
Check if the given value set has been frozen for the remainder of the iteration process.
virtual bool doWidening (const ValueSet &valueSet, CircleRange &range, const CircleRange &newRange)
For an iteration that isn't stabilizing attempt to widen the given ValueSet.
Public Member Functions inherited from Widener
virtual ~Widener (void)
Destructor.
Private Attributes
int4 widenIteration
The iteration at which widening is attempted.
int4 fullIteration
The iteration at which a full range is produced.
Detailed Description
Class for doing normal widening.
Widening is attempted at a specific iteration. If a landmark is available, it is used to do a controlled widening, holding the stable range boundary constant. Otherwise a full range is produced. At a later iteration, a full range is produced automatically.
Member Function Documentation
bool WidenerFull::checkFreeze (const ValueSet & valueSet) virtual
Check if the given value set has been frozen for the remainder of the iteration process.
Parameters
valueSet is the given value set
Returns
true if the valueSet will no longer change
Implements Widener.
References ValueSet::getRange(), and CircleRange::isFull().
int4 WidenerFull::determineIterationReset (const ValueSet & valueSet) virtual
Upon entering a fresh partition, determine how the given ValueSet count should be reset.
Parameters
valueSet is the given value set
Returns
the value of the iteration counter to reset to
Implements Widener.
References ValueSet::getCount().
bool WidenerFull::doWidening (const ValueSet & valueSet, CircleRange & range, const CircleRange & newRange) virtual
For an iteration that isn't stabilizing attempt to widen the given ValueSet.
Change the given range based on its previous iteration so that it stabilizes more rapidly on future iterations.
Parameters
valueSet is the given value set
range is the previous form of the given range (and storage for the widening result)
newRange is the current iteration of the given range
Returns
true if widening succeeded
Implements Widener.
References CircleRange::contains(), ValueSet::getCount(), ValueSet::getLandMark(), CircleRange::getMin(), CircleRange::invert(), and CircleRange::widen().
The documentation for this class was generated from the following files:
rangeutil.hh
rangeutil.cc