decompiler: SubfloatFlow Class Reference
SubfloatFlow Class Reference
Class for tracing changes of precision in floating point variables.
#include <subflow.hh>
Public Member Functions
SubfloatFlow (Funcdata *f, Varnode *root, int4 prec)
virtual bool preserveAddress (Varnode *vn, int4 bitSize, int4 lsbOffset) const
Should the address of the given Varnode be preserved when constructing a piece.
bool doTrace (void)
Trace logical value as far as possible.
Public Member Functions inherited from TransformManager
TransformManager (Funcdata *f)
Constructor.
virtual ~TransformManager (void)
Destructor.
Funcdata * getFunction (void) const
Get function being transformed.
void clearVarnodeMarks (void)
Clear mark for all Varnodes in the map.
TransformVar * newPreexistingVarnode (Varnode *vn)
Make placeholder for preexisting Varnode.
TransformVar * newUnique (int4 size)
Make placeholder for new unique space Varnode.
TransformVar * newConstant (int4 size, int4 lsbOffset, uintb val)
Make placeholder for constant Varnode.
TransformVar * newIop (Varnode *vn)
Make placeholder for special iop constant.
TransformVar * newPiece (Varnode *vn, int4 bitSize, int4 lsbOffset)
Make placeholder for piece of a Varnode.
TransformVar * newSplit (Varnode *vn, const LaneDescription &description)
Create placeholder nodes splitting a Varnode into its lanes.
TransformVar * newSplit (Varnode *vn, const LaneDescription &description, int4 numLanes, int4 startLane)
Create placeholder nodes splitting a Varnode into a subset of lanes in the given description.
TransformOp * newOpReplace (int4 numParams, OpCode opc, PcodeOp *replace)
Create a new placeholder op intended to replace an existing op.
TransformOp * newOp (int4 numParams, OpCode opc, TransformOp *follow)
Create a new placeholder op that will not replace an existing op.
TransformOp * newPreexistingOp (int4 numParams, OpCode opc, PcodeOp *originalOp)
Create a new placeholder op for an existing PcodeOp.
TransformVar * getPreexistingVarnode (Varnode *vn)
Get (or create) placeholder for preexisting Varnode.
TransformVar * getPiece (Varnode *vn, int4 bitSize, int4 lsbOffset)
Get (or create) placeholder piece.
TransformVar * getSplit (Varnode *vn, const LaneDescription &description)
Find (or create) placeholder nodes splitting a Varnode into its lanes.
TransformVar * getSplit (Varnode *vn, const LaneDescription &description, int4 numLanes, int4 startLane)
Find (or create) placeholder nodes splitting a Varnode into a subset of lanes from a description.
void opSetInput (TransformOp *rop, TransformVar *rvn, int4 slot)
Mark given variable as input to given op.
void opSetOutput (TransformOp *rop, TransformVar *rvn)
Mark given variable as output of given op.
void apply (void)
Apply the full transform to the function.
Private Member Functions
TransformVar * setReplacement (Varnode *vn)
Create and return a placeholder associated with the given Varnode.
bool traceForward (TransformVar *rvn)
Try to trace logical variable through descendant Varnodes.
bool traceBackward (TransformVar *rvn)
Trace a logical value backward through defining op one level.
bool processNextWork (void)
Push the trace one hop from the placeholder at the top of the worklist.
Private Attributes
int4 precision
Number of bytes of precision in the logical flow.
int4 terminatorCount
Number of terminating nodes reachable via the root.
const FloatFormat * format
The floating-point format of the logical value.
vector< TransformVar * > worklist
Current list of placeholders that still need to be traced.
Additional Inherited Members
Static Public Member Functions inherited from TransformManager
static bool preexistingGuard (int4 slot, TransformVar *rvn)
Should newPreexistingOp be called.
Detailed Description
Class for tracing changes of precision in floating point variables.
It follows the flow of a logical lower precision value stored in higher precision locations and then rewrites the data-flow in terms of the lower precision, eliminating the precision conversions.
Constructor & Destructor Documentation
SubfloatFlow::SubfloatFlow (Funcdata * f, Varnode * root, int4 prec)
Parameters
f is the function being transformed
root is the start Varnode containing the logical value
prec is the precision to assume for the logical value
References format, Funcdata::getArch(), Translate::getFloatFormat(), precision, setReplacement(), and Architecture::translate.
Member Function Documentation
bool SubfloatFlow::doTrace (void)
Trace logical value as far as possible.
The interpretation that the root Varnode contains a logical value with smaller precision is pushed through the data-flow. If the interpretation is inconsistent, false is returned. Otherwise a transform is constructed that makes the smaller precision the explicit size of Varnodes within the data-flow.
Returns
true if a transform consistent with the given precision can be built
References TransformManager::clearVarnodeMarks(), format, processNextWork(), terminatorCount, and worklist.
Referenced by RuleSubfloatConvert::applyOp().
bool SubfloatFlow::preserveAddress (Varnode * vn, int4 bitSize, int4 lsbOffset) const virtual
Should the address of the given Varnode be preserved when constructing a piece.
A new Varnode will be created that represents a logical piece of the given Varnode. This routine determines whether the new Varnode should be constructed using storage which overlaps the given Varnode. It returns true if overlapping storage should be used, false if the new Varnode should be constructed as a unique temporary.
Parameters
vn is the given Varnode
bitSize is the logical size of the Varnode piece being constructed
lsbOffset is the least significant bit position of the logical value within the given Varnode
Returns
true if overlapping storage should be used in construction
Reimplemented from TransformManager.
References Varnode::isInput().
bool SubfloatFlow::processNextWork (void) private
Push the trace one hop from the placeholder at the top of the worklist.
The logical value for the value on top of the worklist stack is pushed back to the input Varnodes of the operation defining it. Then the value is pushed forward through all operations that read it.
Returns
true if the trace is successfully pushed
References SplitFlow::traceBackward(), SplitFlow::traceForward(), and SplitFlow::worklist.
Referenced by doTrace().
TransformVar * SubfloatFlow::setReplacement (Varnode * vn) private
Create and return a placeholder associated with the given Varnode.
Add the placeholder to the worklist if it hasn't been visited before
Parameters
vn is the given Varnode
Returns
the placeholder or null if the Varnode is not suitable for replacement
References Funcdata::getArch(), Translate::getFloatFormat(), TransformManager::getFunction(), Varnode::getOffset(), TransformManager::getPiece(), Datatype::getSize(), Varnode::getSize(), Varnode::getType(), Varnode::isAddrForce(), Varnode::isConstant(), Varnode::isFree(), Varnode::isInput(), Varnode::isMark(), Varnode::isTypeLock(), TransformManager::newConstant(), TransformManager::newPiece(), TransformManager::newPreexistingVarnode(), Varnode::setMark(), Architecture::translate, and SplitFlow::worklist.
Referenced by LaneDivide::buildMultiequal(), LaneDivide::buildPiece(), LaneDivide::buildRightShift(), LaneDivide::buildStore(), SubfloatFlow(), LaneDivide::traceBackward(), and LaneDivide::traceForward().
bool SubfloatFlow::traceBackward (TransformVar * rvn) private
Trace a logical value backward through defining op one level.
Given an existing variable placeholder look at the op defining it and define placeholder variables for all its inputs. Put the new placeholders onto the worklist if appropriate.
Parameters
rvn is the given variable placeholder
Returns
true if the logical value can be traced properly
References PcodeOp::code(), CPUI_COPY, CPUI_FLOAT_ABS, CPUI_FLOAT_ADD, CPUI_FLOAT_CEIL, CPUI_FLOAT_DIV, CPUI_FLOAT_FLOAT2FLOAT, CPUI_FLOAT_FLOOR, CPUI_FLOAT_INT2FLOAT, CPUI_FLOAT_MULT, CPUI_FLOAT_NEG, CPUI_FLOAT_ROUND, CPUI_FLOAT_SQRT, CPUI_FLOAT_SUB, CPUI_MULTIEQUAL, TransformVar::getDef(), Varnode::getDef(), TransformOp::getIn(), PcodeOp::getIn(), Varnode::getOffset(), TransformVar::getOriginal(), TransformManager::getPreexistingVarnode(), Varnode::getSize(), Varnode::isConstant(), Varnode::isFree(), TransformManager::newConstant(), TransformManager::newOpReplace(), PcodeOp::numInput(), TransformManager::opSetInput(), TransformManager::opSetOutput(), and SplitFlow::setReplacement().
Referenced by LaneDivide::processNextWork().
bool SubfloatFlow::traceForward (TransformVar * rvn) private
Try to trace logical variable through descendant Varnodes.
Given a Varnode placeholder, look at all descendent PcodeOps and create placeholders for the op and its output Varnode. If appropriate add the output placeholder to the worklist.
Parameters
rvn is the given Varnode placeholder
Returns
true if tracing the logical variable forward was possible
References Varnode::beginDescend(), PcodeOp::code(), CPUI_COPY, CPUI_FLOAT_ABS, CPUI_FLOAT_ADD, CPUI_FLOAT_CEIL, CPUI_FLOAT_DIV, CPUI_FLOAT_EQUAL, CPUI_FLOAT_FLOAT2FLOAT, CPUI_FLOAT_FLOOR, CPUI_FLOAT_LESS, CPUI_FLOAT_LESSEQUAL, CPUI_FLOAT_MULT, CPUI_FLOAT_NAN, CPUI_FLOAT_NEG, CPUI_FLOAT_NOTEQUAL, CPUI_FLOAT_ROUND, CPUI_FLOAT_SQRT, CPUI_FLOAT_SUB, CPUI_FLOAT_TRUNC, CPUI_MULTIEQUAL, Varnode::endDescend(), PcodeOp::getIn(), TransformVar::getOriginal(), PcodeOp::getOut(), PcodeOp::getRepeatSlot(), Varnode::getSize(), PcodeOp::getSlot(), Varnode::isMark(), TransformManager::newOpReplace(), TransformManager::newPreexistingOp(), PcodeOp::numInput(), TransformManager::opSetInput(), TransformManager::opSetOutput(), TransformManager::preexistingGuard(), and SplitFlow::setReplacement().
Referenced by LaneDivide::processNextWork().
The documentation for this class was generated from the following files:
subflow.hh
subflow.cc