decompiler: TypeOpIntSright Class Reference
TypeOpIntSright Class Reference
Information about the INT_SRIGHT op-code.
#include <typeop.hh>
Public Member Functions
TypeOpIntSright (TypeFactory *t)
Constructor.
virtual void push (PrintLanguage *lng, const PcodeOp *op, const PcodeOp *readOp) const
Push the specific PcodeOp to the emitter's RPN stack.
virtual void printRaw (ostream &s, const PcodeOp *op)
Print (for debugging purposes) this specific PcodeOp to the stream.
virtual Datatype * getInputCast (const PcodeOp *op, int4 slot, const CastStrategy *castStrategy) const
Find the data-type of the input to a specific PcodeOp.
virtual Datatype * getInputLocal (const PcodeOp *op, int4 slot) const
Find the minimal (or suggested) data-type of an input to this op-code.
virtual Datatype * getOutputToken (const PcodeOp *op, CastStrategy *castStrategy) const
Find the data-type of the output that would be assigned by a compiler.
Public Member Functions inherited from TypeOpBinary
TypeOpBinary (TypeFactory *t, OpCode opc, const string &n, type_metatype mout, type_metatype min)
Constructor.
virtual Datatype * getOutputLocal (const PcodeOp *op) const
Find the minimal (or suggested) data-type of an output to this op-code.
Public Member Functions inherited from TypeOp
TypeOp (TypeFactory *t, OpCode opc, const string &n)
Constructor.
virtual ~TypeOp (void)
Destructor.
const string & getName (void) const
Get the display name of the op-code.
OpCode getOpcode (void) const
Get the op-code value.
uint4 getFlags (void) const
Get the properties associated with the op-code.
OpBehavior * getBehavior (void) const
Get the behavior associated with the op-code.
bool markExplicitUnsigned (PcodeOp *op, int4 slot) const
Check if a constant input should be explicitly labeled as unsigned.
uintb evaluateUnary (int4 sizeout, int4 sizein, uintb in1) const
Emulate the unary op-code on an input value.
uintb evaluateBinary (int4 sizeout, int4 sizein, uintb in1, uintb in2) const
Emulate the binary op-code on an input value.
uintb recoverInputBinary (int4 slot, int4 sizeout, uintb out, int4 sizein, uintb in) const
Reverse the binary op-code operation, recovering a constant input value.
uintb recoverInputUnary (int4 sizeout, uintb out, int4 sizein) const
Reverse the unary op-code operation, recovering a constant input value.
bool isCommutative (void) const
Return true if this op-code is commutative.
bool inheritsSign (void) const
Return true if the op-code inherits it signedness from its inputs.
virtual string getOperatorName (const PcodeOp *op) const
Get the name of the op-code as it should be displayed in context.
Additional Inherited Members
Public Types inherited from TypeOp
enum { inherits_sign = 1, inherits_sign_zero = 2 }
Static Public Member Functions inherited from TypeOp
static void registerInstructions (vector< TypeOp * > &inst, TypeFactory *tlst, const Translate *trans)
Build a map from op-code value to the TypeOp information objects.
static void selectJavaOperators (vector< TypeOp * > &inst, bool val)
Toggle Java specific aspects of the op-code information.
Protected Member Functions inherited from TypeOp
virtual void setSymbol (const string &nm)
Set the display symbol associated with the op-code.
Protected Attributes inherited from TypeOp
TypeFactory * tlst
Pointer to data-type factory.
OpCode opcode
The op-code value.
uint4 opflags
Cached pcode-op properties for this op-code.
uint4 addlflags
Additional properties.
string name
Symbol denoting this operation.
OpBehavior * behave
Object for emulating the behavior of the op-code.
Detailed Description
Information about the INT_SRIGHT op-code.
Member Function Documentation
Datatype * TypeOpIntSright::getInputCast (const PcodeOp * op, int4 slot, const CastStrategy * castStrategy) const virtual
Find the data-type of the input to a specific PcodeOp.
Calculate the actual data-type of the input to the specific PcodeOp. A null result indicates the input data-type is the same as or otherwise doesn't need a cast from the data-type of the actual input Varnode
Parameters
op is the specific PcodeOp
slot is the input to consider
castStrategy is the current casting strategy
Returns
the data-type
Reimplemented from TypeOp.
References CastStrategy::castStandard(), Varnode::getHigh(), PcodeOp::getIn(), TypeOp::getInputCast(), HighVariable::getType(), PcodeOp::inputTypeLocal(), CastStrategy::intPromotionType(), CastStrategy::NO_PROMOTION, and CastStrategy::SIGNED_EXTENSION.
Datatype * TypeOpIntSright::getInputLocal (const PcodeOp * op, int4 slot) const virtual
Find the minimal (or suggested) data-type of an input to this op-code.
The result should depend only on the op-code itself (and the size of the input)
Parameters
op is the PcodeOp being considered
slot is the input being considered
Returns
the data-type
Reimplemented from TypeOpBinary.
References TypeFactory::getBaseNoChar(), PcodeOp::getIn(), TypeOpBinary::getInputLocal(), Varnode::getSize(), TypeOp::tlst, and TYPE_INT.
Datatype * TypeOpIntSright::getOutputToken (const PcodeOp * op, CastStrategy * castStrategy) const virtual
Find the data-type of the output that would be assigned by a compiler.
Calculate the actual data-type of the output for a specific PcodeOp as would be assigned by a C compiler parsing a grammar containing this op.
Parameters
op is the specific PcodeOp
castStrategy is the current casting strategy
Returns
the data-type
Reimplemented from TypeOp.
References TypeFactory::getBase(), Varnode::getHigh(), PcodeOp::getIn(), Datatype::getMetatype(), Datatype::getSize(), HighVariable::getType(), TypeOp::tlst, TYPE_BOOL, and TYPE_INT.
void TypeOpIntSright::printRaw (ostream & s, const PcodeOp * op) virtual
Print (for debugging purposes) this specific PcodeOp to the stream.
Parameters
s is the output stream
op is the specific PcodeOp to print
Reimplemented from TypeOpBinary.
References PcodeOp::getIn(), PcodeOp::getOut(), and Varnode::printRaw().
virtual void TypeOpIntSright::push (PrintLanguage * lng, const PcodeOp * op, const PcodeOp * readOp) const inline virtual
Push the specific PcodeOp to the emitter's RPN stack.
Given a specific language and PcodeOp, emit the expression rooted at the operation.
Parameters
lng is the PrintLanguage to emit
op is the specific PcodeOp
Implements TypeOp.
References TypeOp::getInputCast(), TypeOp::getInputLocal(), TypeOp::getOutputToken(), PrintLanguage::opIntSright(), and TypeOp::printRaw().
The documentation for this class was generated from the following files:
typeop.hh
typeop.cc