decompiler: SymbolEntry Class Reference
SymbolEntry Class Reference
A storage location for a particular Symbol.
#include <database.hh>
Classes
class EntryInitData
Initialization data for a SymbolEntry to facilitate a rangemap.
class EntrySubsort
Class for sub-sorting different SymbolEntry objects at the same address.
Public Types
typedef uintb linetype
The linear element for a rangemap of SymbolEntry.
typedef EntrySubsort subsorttype
The sub-sort object for a rangemap.
typedef EntryInitData inittype
Initialization data for a SymbolEntry in a rangemap.
Public Member Functions
SymbolEntry (void)
Constructor for use with rangemap.
SymbolEntry (Symbol *sym, uint4 exfl, uint8 h, int4 off, int4 sz, const RangeList &rnglist)
Construct a dynamic SymbolEntry.
bool isPiece (void) const
Is this a high or low piece of the whole Symbol.
bool isDynamic (void) const
Is storage dynamic.
bool isInvalid (void) const
Is this storage invalid.
uint4 getAllFlags (void) const
Get all Varnode flags for this storage.
int4 getOffset (void) const
Get offset of this within the Symbol.
uintb getFirst (void) const
Get the first offset of this storage location.
uintb getLast (void) const
Get the last offset of this storage location.
subsorttype getSubsort (void) const
Get the sub-sort object.
void initialize (const EntryInitData &data, uintb a, uintb b)
Fully initialize this.
Symbol * getSymbol (void) const
Get the Symbol associated with this.
const Address & getAddr (void) const
Get the starting address of this storage.
uint8 getHash (void) const
Get the hash used to identify this storage.
int4 getSize (void) const
Get the number of bytes consumed by this storage.
bool inUse (const Address &usepoint) const
Is this storage valid for the given code address.
const RangeList & getUseLimit (void) const
Get the set of valid code addresses for this storage.
Address getFirstUseAddress (void) const
Get the first code address where this storage is valid.
void setUseLimit (const RangeList &uselim)
Set the range of code addresses where this is valid.
bool isAddrTied (void) const
Is this storage address tied.
bool updateType (Varnode *vn) const
Update a Varnode data-type from this.
Datatype * getSizedType (const Address &addr, int4 sz) const
Get the data-type associated with (a piece of) this.
void printEntry (ostream &s) const
Dump a description of this to a stream.
void saveXml (ostream &s) const
Save this to an XML stream.
List::const_iterator restoreXml (List::const_iterator iter, const AddrSpaceManager *manage)
Restore this from an XML stream.
Private Member Functions
SymbolEntry (Symbol *sym)
Construct a mapping for a Symbol without an address.
Private Attributes
Symbol * symbol
Symbol object being mapped.
uint4 extraflags
Varnode flags specific to this storage location.
Address addr
Starting address of the storage location.
uint8 hash
A dynamic storage address (an alternative to addr for dynamic symbols)
int4 offset
Offset into the Symbol that this covers.
int4 size
Number of bytes consumed by this (piece of the) storage.
RangeList uselimit
Code address ranges where this storage is valid.
Friends
class Scope
Detailed Description
A storage location for a particular Symbol.
Where a Symbol is stored, as a byte address and a size, is of particular importance to the decompiler. This class encapsulates this storage meta-data. A single Symbol split across multiple storage locations is supported by the offset and size fields. The hash field supports dynamic storage, where a Symbol is represented by a constant or a temporary register. In this case, storage must be tied to the particular p-code operators using the value.
A particular memory address does not have to represent the symbol across all code. Storage may get recycled for different Symbols at different points in the code. The uselimit object defines the range of instruction addresses over which a particular memory address does represent a Symbol, with the convention that an empty uselimit indicates the storage holds the Symbol across all code.
Constructor & Destructor Documentation
SymbolEntry::SymbolEntry (Symbol * sym) private
Construct a mapping for a Symbol without an address.
This SymbolEntry is unintegrated. An address or hash must be provided either directly or via restoreXml().
Parameters
sym is the Symbol this will be a map for
References extraflags, hash, offset, and size.
SymbolEntry::SymbolEntry (Symbol * sym, uint4 exfl, uint8 h, int4 off, int4 sz, const RangeList & rnglist)
Construct a dynamic SymbolEntry.
This is used specifically for dynamic Symbol objects, where the storage location is attached to a temporary register or a constant. The main address field (addr) is set to invalid, and the hash becomes the primary location information.
Parameters
sym is the underlying Symbol
exfl are the Varnode flags associated with the storage location
h is the the hash
off if the offset into the Symbol for this (piece of) storage
sz is the size in bytes of this (piece of) storage
rnglist is the set of code addresses where this SymbolEntry represents the Symbol
References addr, extraflags, hash, offset, size, symbol, and uselimit.
Member Function Documentation
uint4 SymbolEntry::getAllFlags (void) const inline
Get all Varnode flags for this storage.
Retrieve the (union of) Varnode flags specific to the Symbol and specific to this storage.
Returns
all Varnode flags that apply
References SymbolEntry::EntryInitData::extraflags, Symbol::getFlags(), and SymbolEntry::EntryInitData::symbol.
Referenced by isInvalid(), Scope::queryProperties(), Varnode::setSymbolProperties(), and Funcdata::syncVarnodesWithSymbols().
Datatype * SymbolEntry::getSizedType (const Address & inaddr, int4 sz) const
Get the data-type associated with (a piece of) this.
Return the data-type that matches the given size and address within this storage. NULL is returned if there is no valid sub-type matching the size.
Parameters
inaddr is the given address
sz is the given size (in bytes)
Returns
the matching data-type or NULL
References addr, Address::getOffset(), Datatype::getSize(), Datatype::getSubType(), Symbol::getType(), isDynamic(), offset, and symbol.
Referenced by TypeOpCallother::getInputLocal(), TypeOpCallother::getOutputLocal(), setUseLimit(), and updateType().
SymbolEntry::subsorttype SymbolEntry::getSubsort (void) const
Get the sub-sort object.
Get data used to sub-sort entries (in a rangemap) at the same address
Returns
the sub-sort object
References Varnode::addrtied, Range::getFirst(), RangeList::getFirstRange(), Symbol::getFlags(), AddrSpace::getIndex(), Range::getSpace(), symbol, SymbolEntry::EntrySubsort::useindex, uselimit, and SymbolEntry::EntrySubsort::useoffset.
Referenced by getLast().
void SymbolEntry::initialize (const EntryInitData & data, uintb a, uintb b)
Fully initialize this.
Assuming the boundary offsets have been specified with the constructor, fill in the rest of the data.
Parameters
data contains the raw initialization data
a is the starting offset of the entry
b is the ending offset of the entry
References addr, extraflags, SymbolEntry::EntryInitData::extraflags, offset, SymbolEntry::EntryInitData::offset, size, SymbolEntry::EntryInitData::space, symbol, SymbolEntry::EntryInitData::symbol, uselimit, and SymbolEntry::EntryInitData::uselimit.
Referenced by getLast().
bool SymbolEntry::inUse (const Address & usepoint) const
Is this storage valid for the given code address.
This storage location may only hold the Symbol value for a limited portion of the code.
Parameters
usepoint is the given code address to test
Returns
true if this storage is valid at the given address
References RangeList::inRange(), isAddrTied(), Address::isInvalid(), and uselimit.
Referenced by ScopeInternal::findAddr(), ScopeInternal::findClosestFit(), ScopeInternal::findCodeLabel(), ScopeInternal::findContainer(), Funcdata::findLinkedVarnode(), Funcdata::findLinkedVarnodes(), and getSize().
void SymbolEntry::printEntry (ostream & s) const
Dump a description of this to a stream.
Give a contained one-line description of this storage, suitable for a debug console
Parameters
s is the output stream
References addr, Symbol::getName(), Address::getShortcut(), Datatype::getSize(), Symbol::getType(), Address::isInvalid(), RangeList::printBounds(), Address::printRaw(), Datatype::printRaw(), symbol, and uselimit.
Referenced by setUseLimit().
List::const_iterator SymbolEntry::restoreXml (List::const_iterator iter, const AddrSpaceManager * manage)
Restore this from an XML stream.
Given an iterator to children of a <mapsym> tag, restore the storage address (or the hash if the symbol is dynamic) and the uselimit describing the valid range of code addresses, then advance the iterator to the next tag.
Parameters
iter is the iterator pointing to the address or hash tag
manage is an address space manager for constructing Address objects
Returns
the advanced iterator
References addr, Element::getAttributeValue(), Element::getName(), hash, Address::restoreXml(), RangeList::restoreXml(), and uselimit.
Referenced by Scope::addMapSym(), Symbol::getMapEntry(), Database::getProperties(), ExternRefSymbol::getRefAddr(), EquateSymbol::getValue(), Scope::inScope(), and setUseLimit().
void SymbolEntry::saveXml (ostream & s) const
Save this to an XML stream.
This writes tags internal to the <mapsym> tag associated with the Symbol. It outputs the address tag (or the <hash> tag for dynamic symbols) and a <rangelist> tag associated with the uselimit.
Parameters
s is the output stream
References addr, hash, Address::isInvalid(), isPiece(), Address::saveXml(), RangeList::saveXml(), and uselimit.
Referenced by Symbol::getMapEntry(), Database::getProperties(), ExternRefSymbol::getRefAddr(), EquateSymbol::getValue(), Scope::inScope(), ScopeInternal::saveXml(), and setUseLimit().
bool SymbolEntry::updateType (Varnode * vn) const
Update a Varnode data-type from this.
If the Symbol associated with this is type-locked, change the given Varnode's attached data-type to match the Symbol
Parameters
vn is the Varnode to modify
Returns
true if the data-type was changed
References Varnode::getAddr(), Symbol::getFlags(), Varnode::getSize(), getSizedType(), symbol, Varnode::typelock, and Varnode::updateType().
Referenced by Varnode::setSymbolProperties(), and setUseLimit().
The documentation for this class was generated from the following files:
database.hh
database.cc