decompiler: RuleSubvarAnd Class Reference
RuleSubvarAnd Class Reference
Perform SubVariableFlow analysis triggered by INT_AND.
Public Member Functions
RuleSubvarAnd (const string &g)
Constructor.
virtual Rule * clone (const ActionGroupList &grouplist) const
Clone the Rule.
virtual void getOpList (vector< uint4 > &oplist) const
List of op codes this rule operates on.
virtual int4 applyOp (PcodeOp *op, Funcdata &data)
Attempt to apply this Rule.
Public Member Functions inherited from Rule
Rule (const string &g, uint4 fl, const string &nm)
Construct given group, properties name.
virtual ~Rule (void)
Destructor.
const string & getName (void) const
Return the name of this Rule.
const string & getGroup (void) const
Return the group this Rule belongs to.
uint4 getNumTests (void)
Get number of attempted applications.
uint4 getNumApply (void)
Get number of successful applications.
void setBreak (uint4 tp)
Set a breakpoint on this Rule.
void clearBreak (uint4 tp)
Clear a breakpoint on this Rule.
void clearBreakPoints (void)
Clear all breakpoints on this Rule.
void turnOnWarnings (void)
Enable warnings for this Rule.
void turnOffWarnings (void)
Disable warnings for this Rule.
bool isDisabled (void) const
Return true if this Rule is disabled.
void setDisable (void)
Disable this Rule (within its pool)
void clearDisable (void)
Enable this Rule (within its pool)
bool checkActionBreak (void)
Check if an action breakpoint is turned on.
uint4 getBreakPoint (void) const
Return breakpoint toggles.
virtual void reset (Funcdata &data)
Reset this Rule.
virtual void resetStats (void)
Reset Rule statistics.
virtual void printStatistics (ostream &s) const
Print statistics for this Rule.
Additional Inherited Members
Public Types inherited from Rule
enum typeflags { type_disable = 1, rule_debug = 2, warnings_on = 4, warnings_given = 8 }
Properties associated with a Rule.
Detailed Description
Perform SubVariableFlow analysis triggered by INT_AND.
Member Function Documentation
int4 RuleSubvarAnd::applyOp (PcodeOp * op, Funcdata & data) virtual
Attempt to apply this Rule.
This method contains the main logic for applying the Rule. It must use a given PcodeOp as the point at which the Rule applies. If it does apply, changes are made directly to the function and 1 (non-zero) is returned, otherwise 0 is returned.
Parameters
op is the given PcodeOp where the Rule may apply
data is the function to which to apply
Reimplemented from Rule.
References calc_mask(), SubvariableFlow::doReplacement(), SubvariableFlow::doTrace(), Varnode::getConsume(), PcodeOp::getIn(), Varnode::getOffset(), PcodeOp::getOut(), Varnode::getSize(), Varnode::hasNoDescend(), and Varnode::isConstant().
virtual Rule* RuleSubvarAnd::clone (const ActionGroupList & grouplist) const inline virtual
Clone the Rule.
If this Rule is a member of one of the groups in the grouplist, this returns a clone of the Rule, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Rule or NULL
Implements Rule.
References ActionGroupList::contains(), and AddTreeState::data.
void RuleSubvarAnd::getOpList (vector< uint4 > & oplist) const virtual
List of op codes this rule operates on.
Populate the given array with all possible OpCodes this Rule might apply to. By default, this method returns all possible OpCodes
Parameters
oplist is the array to populate
Reimplemented from Rule.
References CPUI_INT_AND.
The documentation for this class was generated from the following files:
ruleaction.hh
ruleaction.cc