decompiler: ParamListStandardOut Class Reference
ParamListStandardOut Class Reference
A standard model for passing back return values from a function.
#include <fspec.hh>
Public Member Functions
ParamListStandardOut (void)
Constructor.
ParamListStandardOut (const ParamListStandardOut &op2)
Copy constructor.
virtual uint4 getType (void) const
Get the type of parameter list.
virtual void assignMap (const vector< Datatype * > &proto, bool isinput, TypeFactory &typefactory, vector< ParameterPieces > &res) const
Given list of data-types, map the list positions to storage locations.
virtual void fillinMap (ParamActive *active) const
Given an unordered list of storage locations, calculate a function prototype.
virtual bool possibleParam (const Address &loc, int4 size) const
Does the given storage location make sense as a parameter.
virtual void restoreXml (const Element *el, const AddrSpaceManager *manage, vector< EffectRecord > &effectlist, bool normalstack)
Restore the model from an XML stream.
virtual ParamList * clone (void) const
Clone this parameter list model.
Public Member Functions inherited from ParamListStandard
ParamListStandard (void)
Construct for use with restoreXml()
ParamListStandard (const ParamListStandard &op2)
Copy constructor.
const list< ParamEntry > & getEntry (void) const
Get the list of parameter entries.
virtual bool checkJoin (const Address &hiaddr, int4 hisize, const Address &loaddr, int4 losize) const
Check if the given two storage locations can represent a single logical parameter.
virtual bool checkSplit (const Address &loc, int4 size, int4 splitpoint) const
Check if it makes sense to split a single storage location into two parameters.
virtual int4 characterizeAsParam (const Address &loc, int4 size) const
Characterize whether the given range overlaps parameter storage.
virtual bool possibleParamWithSlot (const Address &loc, int4 size, int4 &slot, int4 &slotsize) const
Pass-back the slot and slot size for the given storage location as a parameter.
virtual bool getBiggestContainedParam (const Address &loc, int4 size, VarnodeData &res) const
Pass-back the biggest parameter contained within the given range.
virtual bool unjustifiedContainer (const Address &loc, int4 size, VarnodeData &res) const
Check if the given storage location looks like an unjustified parameter.
virtual OpCode assumedExtension (const Address &addr, int4 size, VarnodeData &res) const
Get the type of extension and containing parameter for the given storage.
virtual AddrSpace * getSpacebase (void) const
Get the address space associated with any stack based parameters in this list.
virtual void getRangeList (AddrSpace *spc, RangeList &res) const
For a given address space, collect all the parameter locations within that space.
virtual int4 getMaxDelay (void) const
Return the maximum heritage delay across all possible parameters.
Public Member Functions inherited from ParamList
virtual ~ParamList (void)
Destructor.
Additional Inherited Members
Public Types inherited from ParamList
enum { p_standard, p_standard_out, p_register, p_merged }
Protected Member Functions inherited from ParamListStandard
const ParamEntry * findEntry (const Address &loc, int4 size) const
Given storage location find matching ParamEntry.
Address assignAddress (const Datatype *tp, vector< int4 > &status) const
Assign storage for given parameter data-type.
void buildTrialMap (ParamActive *active) const
Build map from parameter trials to model ParamEntrys.
void separateFloat (ParamActive *active, int4 &floatstart, int4 &floatstop, int4 &start, int4 &stop) const
Calculate the range of floating-point entries within a given set of parameter trials.
void forceExclusionGroup (ParamActive *active) const
Enforce exclusion rules for the given set of parameter trials.
void forceNoUse (ParamActive *active, int4 start, int4 stop) const
Mark every trial above the first "definitely not used" as inactive.
void forceInactiveChain (ParamActive *active, int4 maxchain, int4 start, int4 stop) const
Enforce rules about chains of inactive slots.
void calcDelay (void)
Calculate the maximum heritage delay for any potential parameter in this list.
void populateResolver (void)
Build the ParamEntry resolver maps.
Protected Attributes inherited from ParamListStandard
int4 numgroup
Number of groups in this parameter convention.
int4 maxdelay
Maximum heritage delay across all parameters.
int4 pointermax
If non-zero, maximum size of a data-type before converting to a pointer.
bool thisbeforeret
Does a this parameter come before a hidden return parameter.
int4 nonfloatgroup
Group of first entry which is not marked float.
list< ParamEntry > entry
The ordered list of parameter entries.
vector< ParamEntryResolver * > resolverMap
Map from space id to resolver.
AddrSpace * spacebase
Address space containing relative offset parameters.
Detailed Description
A standard model for passing back return values from a function.
This models a resource list of potential storage locations for a return value, at most 1 of which will be chosen for a given function. Order only matters in that the first ParamEntry that fits is used. If no entry fits, the return value is converted to a pointer data-type, storage allocation is attempted again, and the return value is marked as a hidden return parameter to inform the input model.
Member Function Documentation
void ParamListStandardOut::assignMap (const vector< Datatype * > & proto, bool isinput, TypeFactory & typefactory, vector< ParameterPieces > & res) const virtual
Given list of data-types, map the list positions to storage locations.
If we know the function prototype, recover how parameters are actually stored using the model.
Parameters
proto is the ordered list of data-types
isinput is true for the input prototype, false for output prototype
typefactory is the TypeFactory (for constructing pointers)
res will contain the storage locations corresponding to the datatypes
Reimplemented from ParamListStandard.
References AddrSpace::getAddrSize(), TypeFactory::getArch(), AddrSpaceManager::getDefaultDataSpace(), TypeFactory::getTypePointer(), AddrSpace::getWordSize(), ParameterPieces::hiddenretparm, ParameterPieces::indirectstorage, and TYPE_VOID.
void ParamListStandardOut::fillinMap (ParamActive * active) const virtual
Given an unordered list of storage locations, calculate a function prototype.
A list of input (or output) trials is given, which may have holes, invalid inputs etc. Decide on the formal ordered parameter list. Trials within the ParamActive are added, removed, or reordered as needed.
Parameters
active is the given list of trials
Reimplemented from ParamListStandard.
References ParamEntry::getMinSize(), ParamActive::getNumTrials(), ParamTrial::getSize(), ParamActive::getTrial(), ParamEntry::getType(), ParamEntry::isParamCheckHigh(), ParamEntry::isParamCheckLow(), ParamEntry::justifiedContain(), ParamTrial::markNoUse(), ParamActive::sortTrials(), and TYPE_PTR.
bool ParamListStandardOut::possibleParam (const Address & loc, int4 size) const virtual
Does the given storage location make sense as a parameter.
Within this model, decide if the storage location can be considered a parameter.
Parameters
loc is the starting address of the storage location
size is the number of bytes in the storage location
Returns
true if the location can be a parameter
Reimplemented from ParamListStandard.
void ParamListStandardOut::restoreXml (const Element * el, const AddrSpaceManager * manage, vector< EffectRecord > & effectlist, bool normalstack) virtual
Restore the model from an XML stream.
Parameters
el is the root <input> or <output> element
manage is used to resolve references to address spaces
effectlist is a container collecting EffectRecords across all parameters
normalstack is true if parameters are pushed on the stack in the normal order
Reimplemented from ParamListStandard.
References ParamListStandard::restoreXml().
The documentation for this class was generated from the following files:
fspec.hh
fspec.cc