decompiler: InjectPayload Class Reference
InjectPayload Class Reference abstract
An active container for a set of p-code operations that can be injected into data-flow.
#include <pcodeinject.hh>
Public Types
enum { CALLFIXUP_TYPE = 1, CALLOTHERFIXUP_TYPE = 2, CALLMECHANISM_TYPE = 3, EXECUTABLEPCODE_TYPE = 4 }
Public Member Functions
InjectPayload (const string &nm, int4 tp)
Construct for use with restoreXml.
int4 getParamShift (void) const
Get the number of parameters shifted.
bool isDynamic (void) const
Return true if p-code in the injection is generated dynamically.
bool isIncidentalCopy (void) const
Return true if any injected COPY is considered incidental.
int4 sizeInput (void) const
Return the number of input parameters.
int4 sizeOutput (void) const
Return the number of output parameters.
InjectParameter & getInput (int4 i)
Get the i-th input parameter.
InjectParameter & getOutput (int4 i)
Get the i-th output parameter.
virtual ~InjectPayload (void)
Destructor.
virtual void inject (InjectContext &context, PcodeEmit &emit) const =0
virtual void restoreXml (const Element *el)
Restore this payload from an XML stream.
virtual void printTemplate (ostream &s) const =0
Print the p-code ops of the injection to a stream (for debugging)
string getName (void) const
Return the name of the injection.
int4 getType (void) const
Return the type of injection (CALLFIXUP_TYPE, CALLOTHERFIXUP_TYPE, etc.)
virtual string getSource (void) const =0
Return a string describing the source of the injection (.cspec, prototype model, etc.)
Protected Member Functions
void orderParameters (void)
Assign an index to parameters.
Static Protected Member Functions
static void readParameter (const Element *el, string &name, uint4 &size)
Read in an <input> or <output> XML tag describing an injection parameter.
Protected Attributes
string name
Formal name of the payload.
int4 type
Type of this payload: CALLFIXUP_TYPE, CALLOTHERFIXUP_TYPE, etc.
bool dynamic
True if the injection is generated dynamically.
bool incidentalCopy
True if injected COPYs are considered incidental.
int4 paramshift
Number of parameters shifted in the original call.
vector< InjectParameter > inputlist
List of input parameters to this payload.
vector< InjectParameter > output
List of output parameters.
Detailed Description
An active container for a set of p-code operations that can be injected into data-flow.
This is an abstract base class. Derived classes manage details of how the p-code is stored. The methods provide access to the input/output parameter information, and the main injection is performed with inject().
Member Enumeration Documentation
anonymous enum
Enumerator
CALLFIXUP_TYPE
Injection that replaces a CALL.
CALLOTHERFIXUP_TYPE
Injection that replaces a user-defined p-code op, CALLOTHER.
CALLMECHANISM_TYPE
Injection to patch up data-flow around the caller/callee boundary.
EXECUTABLEPCODE_TYPE
Injection running as a stand-alone p-code script.
Member Function Documentation
virtual void InjectPayload::inject (InjectContext & context, PcodeEmit & emit) const pure virtual
Perform the injection of this payload into data-flow.
P-code operations representing this payload are copied into the controlling analysis context. The provided PcodeEmit object dictates exactly where the PcodeOp and Varnode objects are inserted and to what container. An InjectContext object specifies how placeholder elements become concrete Varnodes in the appropriate context.
Parameters
context is the provided InjectConject object
emit is the provovided PcodeEmit object
Implemented in ExecutablePcodeGhidra, and InjectPayloadGhidra.
Referenced by ExecutablePcode::build(), FlowInfo::doInjection(), and Funcdata::doLiveInject().
void InjectPayload::orderParameters (void) protected
Assign an index to parameters.
Input and output parameters are assigned a unique index.
References inputlist, and output.
Referenced by restoreXml().
void InjectPayload::readParameter (const Element * el, string & name, uint4 & size) static protected
Read in an <input> or <output> XML tag describing an injection parameter.
Parameters
el is the XML element
name is used to pass back the parameter name
size is used to pass back the parameter size
References Element::getAttributeName(), Element::getAttributeValue(), and Element::getNumAttributes().
Referenced by restoreXml().
void InjectPayload::restoreXml (const Element * el) virtual
Restore this payload from an XML stream.
The base class version of this method restores from a <pcode> tag. Derived classes may restore from a parent tag and then invoke the base class method.
Parameters
el is the XML element
Reimplemented in ExecutablePcodeGhidra, InjectCallotherGhidra, InjectCallfixupGhidra, and InjectPayloadGhidra.
References dynamic, Element::getAttributeName(), Element::getAttributeValue(), Element::getChildren(), Element::getName(), Element::getNumAttributes(), incidentalCopy, inputlist, orderParameters(), output, paramshift, readParameter(), and xml_readbool().
Referenced by InjectCallotherGhidra::restoreXml(), and ExecutablePcodeGhidra::restoreXml().
The documentation for this class was generated from the following files:
pcodeinject.hh
pcodeinject.cc