decompiler: FlowBlock Class Reference
FlowBlock Class Reference
Description of a control-flow block containing PcodeOps.
#include <block.hh>
Public Types
enum block_type {
t_plain, t_basic, t_graph, t_copy,
t_goto, t_multigoto, t_ls, t_condition,
t_if, t_whiledo, t_dowhile, t_switch,
t_infloop, t_for
}
The possible block types.
enum block_flags {
f_goto_goto = 1, f_break_goto = 2, f_continue_goto = 4, f_switch_out = 0x10,
f_unstructured_targ = 0x20, f_mark = 0x80, f_mark2 = 0x100, f_entry_point = 0x200,
f_interior_gotoout = 0x400, f_interior_gotoin = 0x800, f_label_bumpup = 0x1000, f_donothing_loop = 0x2000,
f_dead = 0x4000, f_whiledo_overflow = 0x8000, f_flip_path = 0x10000, f_joined_block = 0x20000,
f_duplicate_block = 0x40000
}
Boolean properties of blocks.
enum edge_flags {
f_goto_edge = 1, f_loop_edge = 2, f_defaultswitch_edge = 4, f_irreducible = 8,
f_tree_edge = 0x10, f_forward_edge = 0x20, f_cross_edge = 0x40, f_back_edge = 0x80,
f_loop_exit_edge = 0x100
}
Boolean properties on edges.
Public Member Functions
FlowBlock (void)
Construct a block with no edges.
virtual ~FlowBlock (void)
Destructor.
int4 getIndex (void) const
Get the index assigned to this block.
FlowBlock * getParent (void)
Get the parent FlowBlock of this.
FlowBlock * getImmedDom (void) const
Get the immediate dominator FlowBlock.
FlowBlock * getCopyMap (void) const
Get the mapped FlowBlock.
const FlowBlock * getParent (void) const
Get the parent FlowBlock of this.
uint4 getFlags (void) const
Get the block_flags properties.
virtual Address getStart (void) const
Get the starting address of code in this FlowBlock.
virtual Address getStop (void) const
Get the ending address of code in this FlowBlock.
virtual block_type getType (void) const
Get the FlowBlock type of this.
virtual FlowBlock * subBlock (int4 i) const
Get the i-th component block.
virtual void markUnstructured (void)
Mark target blocks of any unstructured edges.
virtual void markLabelBumpUp (bool bump)
Let hierarchical blocks steal labels of their (first) components.
virtual void scopeBreak (int4 curexit, int4 curloopexit)
Mark unstructured edges that should be breaks.
virtual void printHeader (ostream &s) const
Print a simple description of this to stream.
virtual void printTree (ostream &s, int4 level) const
Print tree structure of any blocks owned by this.
virtual void printRaw (ostream &s) const
Print raw instructions contained in this FlowBlock.
virtual void emit (PrintLanguage *lng) const
Emit the instructions in this FlowBlock as structured code.
virtual const FlowBlock * getExitLeaf (void) const
Get the FlowBlock to which this block exits.
virtual PcodeOp * lastOp (void) const
Get the last PcodeOp executed by this FlowBlock.
virtual bool negateCondition (bool toporbottom)
Flip the condition computed by this.
virtual bool preferComplement (Funcdata &data)
Rearrange this hierarchy to simplify boolean expressions.
virtual FlowBlock * getSplitPoint (void)
Get the leaf splitting block.
virtual int4 flipInPlaceTest (vector< PcodeOp * > &fliplist) const
Test normalizing the conditional branch in this.
virtual void flipInPlaceExecute (void)
Perform the flip to normalize conditional branch executed by this block.
virtual bool isComplex (void) const
Is this too complex to be a condition (BlockCondition)
virtual FlowBlock * nextFlowAfter (const FlowBlock *bl) const
Get the leaf FlowBlock that will execute after the given FlowBlock.
virtual void finalizePrinting (const Funcdata &data) const
Make any final configurations necessary to print the block.
virtual void saveXmlHeader (ostream &s) const
Save basic information as XML attributes.
virtual void restoreXmlHeader (const Element *el)
Restore basic information for XML attributes.
virtual void saveXmlBody (ostream &s) const
Save detail about components to an XML stream.
virtual void restoreXmlBody (List::const_iterator &iter, List::const_iterator enditer, BlockMap &resolver)
Restore details about this FlowBlock from an XML stream.
void saveXmlEdges (ostream &s) const
Save edge information to an XML stream.
void restoreXmlEdges (List::const_iterator &iter, List::const_iterator enditer, BlockMap &resolver)
Restore edges from an XML stream.
void saveXml (ostream &s) const
Write out this to an XML stream.
void restoreXml (const Element *el, BlockMap &resolver)
Restore this from an XML stream.
const FlowBlock * nextInFlow (void) const
Return next block to be executed in flow.
void setVisitCount (int4 i)
Set the number of times this block has been visited.
int4 getVisitCount (void) const
Get the count of visits.
void setGotoBranch (int4 i)
Mark a goto branch.
void setDefaultSwitch (int4 i)
Mark an edge as the switch default.
bool isMark (void) const
Return true if this block has been marked.
void setMark (void)
Mark this block.
void clearMark (void)
Clear any mark on this block.
void setDonothingLoop (void)
Label this as a do nothing loop.
void setDead (void)
Label this as dead.
bool hasSpecialLabel (void) const
Return true if this uses a different label.
bool isJoined (void) const
Return true if this is a joined basic block.
bool isDuplicated (void) const
Return true if this is a duplicated block.
void setLoopExit (int4 i)
Label the edge exiting this as a loop.
void clearLoopExit (int4 i)
Clear the loop exit edge.
void setBackEdge (int4 i)
Label the back edge of a loop.
bool getFlipPath (void) const
Have out edges been flipped.
bool isJumpTarget (void) const
Return true if non-fallthru jump flows into this.
FlowBlock * getFalseOut (void) const
Get the false output FlowBlock.
FlowBlock * getTrueOut (void) const
Get the true output FlowBlock.
FlowBlock * getOut (int4 i)
Get the i-th output FlowBlock.
const FlowBlock * getOut (int4 i) const
Get i-th output FlowBlock.
int4 getOutRevIndex (int4 i) const
Get the input index of the i-th output FlowBlock.
FlowBlock * getIn (int4 i)
Get the i-th input FlowBlock.
const FlowBlock * getIn (int4 i) const
Get the i-th input FlowBlock.
int4 getInRevIndex (int4 i) const
Get the output index of the i-th input FlowBlock.
const FlowBlock * getFrontLeaf (void) const
Get the first leaf FlowBlock.
FlowBlock * getFrontLeaf (void)
Get the first leaf FlowBlock.
int4 calcDepth (const FlowBlock *leaf) const
Get the depth of the given component FlowBlock.
bool dominates (const FlowBlock *subBlock) const
Does this block dominate the given block.
bool restrictedByConditional (const FlowBlock *cond) const
Check if the condition from the given block holds for this block.
int4 sizeOut (void) const
Get the number of out edges.
int4 sizeIn (void) const
Get the number of in edges.
bool hasLoopIn (void) const
Is there a looping edge coming into this block.
bool hasLoopOut (void) const
Is there a looping edge going out of this block.
bool isLoopIn (int4 i) const
Is the i-th incoming edge a loop edge.
bool isLoopOut (int4 i) const
Is the i-th outgoing edge a loop edge.
int4 getInIndex (const FlowBlock *bl) const
Get the incoming edge index for the given FlowBlock.
int4 getOutIndex (const FlowBlock *bl) const
Get the outgoing edge index for the given FlowBlock.
bool isDefaultBranch (int4 i) const
Is the i-th out edge the switch default edge.
bool isLabelBumpUp (void) const
Are labels for this printed by the parent.
bool isUnstructuredTarget (void) const
Is this the target of an unstructured goto.
bool isInteriorGotoTarget (void) const
Is there an unstructured goto to this block's interior.
bool hasInteriorGoto (void) const
Is there an unstructured goto out of this block's interior.
bool isEntryPoint (void) const
Is the entry point of the function.
bool isSwitchOut (void) const
Is this a switch block.
bool isDonothingLoop (void) const
Is this a do nothing block.
bool isDead (void) const
Is this block dead.
bool isTreeEdgeIn (int4 i) const
Is the i-th incoming edge part of the spanning tree.
bool isBackEdgeIn (int4 i) const
Is the i-th incoming edge a back edge.
bool isBackEdgeOut (int4 i) const
Is the i-th outgoing edge a back edge.
bool isIrreducibleOut (int4 i) const
Is the i-th outgoing edge an irreducible edge.
bool isIrreducibleIn (int4 i) const
Is the i-th incoming edge an irreducible edge.
bool isDecisionOut (int4 i) const
Can this and the i-th output be merged into a BlockIf or BlockList.
bool isDecisionIn (int4 i) const
Can this and the i-th input be merged into a BlockIf or BlockList.
bool isLoopDAGOut (int4 i) const
Is the i-th outgoing edge part of the DAG sub-graph.
bool isLoopDAGIn (int4 i) const
Is the i-th incoming edge part of the DAG sub-graph.
bool isGotoIn (int4 i) const
Is the i-th incoming edge unstructured.
bool isGotoOut (int4 i) const
Is the i-th outgoing edge unstructured.
JumpTable * getJumptable (void) const
Get the JumpTable associated this block.
Static Public Member Functions
static block_type nameToType (const string &name)
Get the block_type associated with a name string.
static string typeToName (block_type bt)
Get the name string associated with a block_type.
static bool compareBlockIndex (const FlowBlock *bl1, const FlowBlock *bl2)
Compare FlowBlock by index.
static bool compareFinalOrder (const FlowBlock *bl1, const FlowBlock *bl2)
Final FlowBlock comparison.
static FlowBlock * findCommonBlock (FlowBlock *bl1, FlowBlock *bl2)
Find the common dominator of two FlowBlocks.
static FlowBlock * findCommonBlock (const vector< FlowBlock * > &blockSet)
Find common dominator of multiple FlowBlocks.
Protected Member Functions
void setFlag (uint4 fl)
Set a boolean property.
void clearFlag (uint4 fl)
Clear a boolean property.
Private Member Functions
void addInEdge (FlowBlock *b, uint4 lab)
Add an edge coming into this.
void restoreNextInEdge (const Element *el, BlockMap &resolver)
Restore the next input edge from XML.
void halfDeleteInEdge (int4 slot)
Delete the in half of an edge, correcting indices.
void halfDeleteOutEdge (int4 slot)
Delete the out half of an edge, correcting indices.
void removeInEdge (int4 slot)
Remove an incoming edge.
void removeOutEdge (int4 slot)
Remove an outgoing edge.
void replaceInEdge (int4 num, FlowBlock *b)
Make an incoming edge flow from a given block.
void replaceOutEdge (int4 num, FlowBlock *b)
Make an outgoing edge flow to a given block.
void replaceEdgesThru (int4 in, int4 out)
Remove this from flow between two blocks.
void swapEdges (void)
Swap the first and second out edges.
void setOutEdgeFlag (int4 i, uint4 lab)
Apply an out edge label.
void clearOutEdgeFlag (int4 i, uint4 lab)
Remove an out edge label.
void eliminateInDups (FlowBlock *bl)
Eliminate duplicate in edges from given block.
void eliminateOutDups (FlowBlock *bl)
Eliminate duplicate out edges to given block.
void dedup (void)
Eliminate duplicate edges.
void replaceUsingMap (void)
Update references to other blocks using getCopyMap()
Static Private Member Functions
static void replaceEdgeMap (vector< BlockEdge > &vec)
Update block references in edges with copy map.
static void findDups (const vector< BlockEdge > &ref, vector< FlowBlock * > &duplist)
Find blocks that are at the end of multiple edges.
Private Attributes
uint4 flags
Collection of block_flags.
FlowBlock * parent
The parent block to which this belongs.
FlowBlock * immed_dom
Immediate dominating block.
FlowBlock * copymap
Back reference to a BlockCopy of this.
int4 index
Reference index for this block (reverse post order)
int4 visitcount
A count of visits of this node for various algorithms.
int4 numdesc
Number of descendants of this block in spanning tree (+1)
vector< BlockEdge > intothis
Blocks which (can) fall into this block.
vector< BlockEdge > outofthis
Blocks into which this block (can) fall.
Friends
class BlockGraph
Detailed Description
Description of a control-flow block containing PcodeOps.
This is the base class for basic blocks (BlockBasic) and the hierarchical description of structured code. At all levels, these can be viewed as a block of code (PcodeOp objects) with other blocks flowing into and out of it.
Member Enumeration Documentation
enum FlowBlock::block_flags
Boolean properties of blocks.
The first four flags describe attributes of the blocks primary exiting edges The f_interior_* flags do not necessarily apply to these edges. They are used with the block structure and hierarchy algorithms where unstructured jumps are removed from the list of primary edges. These flags keep track only of the existence of unstructured edges, even though they aren't listed
Enumerator
f_goto_goto
(Block ends in) non-structured branch
f_break_goto
Block ends with a break;.
f_continue_goto
Block ends with a continue;.
f_switch_out
Output is decided by switch.
f_unstructured_targ
Block is destination of unstructured goto.
f_mark
Generic way to mark a block.
f_mark2
A secondary mark.
f_entry_point
Official entry point of the function.
f_interior_gotoout
The block has an unstructured jump out of interior.
f_interior_gotoin
Block is target of unstructured jump to its interior.
f_label_bumpup
Any label printed higher up in hierarchy.
f_donothing_loop
Block does nothing in infinite loop (halt)
f_dead
Block is in process of being deleted.
f_whiledo_overflow
Set if the conditional block of a whiledo is too big to print as while(cond) { ...
f_flip_path
If true, out edges have been flipped since last time path was traced.
f_joined_block
Block is a merged form of original basic blocks.
f_duplicate_block
Block is a duplicated version of an original basic block.
enum FlowBlock::edge_flags
Boolean properties on edges.
Enumerator
f_goto_edge
Edge is unstructured.
f_loop_edge
Edge completes a loop, removing these edges gives you a DAG.
f_defaultswitch_edge
This is default edge from switchblock.
f_irreducible
Edge which must be removed to make graph reducible.
f_tree_edge
An edge in the spanning tree.
f_forward_edge
An edge that jumps forward in the spanning tree.
f_cross_edge
An edge that crosses subtrees in the spanning tree.
f_back_edge
Within (reducible) graph, a back edge defining a loop.
f_loop_exit_edge
Edge exits the body of a loop.
Member Function Documentation
void FlowBlock::addInEdge (FlowBlock * b, uint4 lab) private
Add an edge coming into this.
Parameters
b is the FlowBlock coming in
lab is a label for the edge
References BlockEdge::BlockEdge(), and outofthis.
Referenced by BlockGraph::addEdge().
int4 FlowBlock::calcDepth (const FlowBlock * leaf) const
Get the depth of the given component FlowBlock.
How many getParent() calls from the leaf to this
Parameters
leaf is the component FlowBlock
Returns
the depth count
References getParent().
Referenced by getInRevIndex(), BlockGoto::saveXmlBody(), BlockMultiGoto::saveXmlBody(), and BlockIf::saveXmlBody().
void FlowBlock::clearOutEdgeFlag (int4 i, uint4 lab) private
Remove an out edge label.
Parameters
i is the index of the outgoing edge
lab is the edge label to remove
References intothis.
Referenced by clearLoopExit(), and BlockGraph::findIrreducible().
bool FlowBlock::compareBlockIndex (const FlowBlock * bl1, const FlowBlock * bl2) inline static
Compare FlowBlock by index.
Parameters
bl1 is the first FlowBlock to compare
bl2 is the second FlowBlock to compare
Returns
true if the first comes before the second
References getIndex().
Referenced by isGotoOut(), and BlockMap::sortList().
bool FlowBlock::compareFinalOrder (const FlowBlock * bl1, const FlowBlock * bl2) static
Final FlowBlock comparison.
Comparator for ordering the final 0-exit blocks
Parameters
bl1 is the first FlowBlock to compare
bl2 is the second FlowBlock
Returns
true if the first comes before the second
References PcodeOp::code(), CPUI_RETURN, getIndex(), and lastOp().
Referenced by isGotoOut().
bool FlowBlock::dominates (const FlowBlock * subBlock) const
Does this block dominate the given block.
Return true if this block dominates the given block (or is equal to it). This assumes that block indices have been set with a reverse post order so that having a smaller index is a necessary condition for dominance.
Parameters
subBlock is the given block to test against this for dominance
Returns
true if this dominates
References getImmedDom().
Referenced by Merge::checkCopyPair(), and getInRevIndex().
void FlowBlock::eliminateInDups (FlowBlock * bl) private
Eliminate duplicate in edges from given block.
Parameters
bl is the given block
References halfDeleteOutEdge(), and BlockEdge::point.
void FlowBlock::eliminateOutDups (FlowBlock * bl) private
Eliminate duplicate out edges to given block.
Parameters
bl is the given block
References halfDeleteInEdge(), and BlockEdge::point.
void FlowBlock::emit (PrintLanguage * lng) const inline virtual
Emit the instructions in this FlowBlock as structured code.
This is the main entry point, at the control-flow level, for printing structured code.
Parameters
lng is the PrintLanguage that provides details of the high-level language being printed
Reimplemented in BlockSwitch, BlockInfLoop, BlockDoWhile, BlockFor, BlockWhileDo, BlockIf, BlockCondition, BlockList, BlockMultiGoto, BlockGoto, BlockCopy, BlockBasic, and BlockGraph.
Referenced by PrintC::emitBlockCondition(), PrintC::emitBlockCopy(), PrintC::emitBlockDoWhile(), PrintC::emitBlockFor(), PrintC::emitBlockGoto(), PrintC::emitBlockIf(), PrintC::emitBlockInfLoop(), PrintC::emitBlockLs(), PrintC::emitBlockSwitch(), and PrintC::emitBlockWhileDo().
FlowBlock * FlowBlock::findCommonBlock (FlowBlock * bl1, FlowBlock * bl2) static
Find the common dominator of two FlowBlocks.
Within the dominator tree, find the earliest common ancestor of two FlowBlocks
Parameters
bl1 is the first FlowBlock
bl2 is the second
Returns
the common ancestor which dominates both
References clearMark(), getImmedDom(), isMark(), and setMark().
Referenced by Merge::buildDominantCopy(), PcodeOp::compareOrder(), cseElimination(), and isGotoOut().
FlowBlock * FlowBlock::findCommonBlock (const vector< FlowBlock * > & blockSet) static
Find common dominator of multiple FlowBlocks.
Find the most immediate dominating FlowBlock of all blocks in the given set. The container must not be empty.
Parameters
blockSet is the given set of blocks
Returns
the most immediate dominating FlowBlock
References getImmedDom(), getIndex(), isMark(), and setMark().
void FlowBlock::findDups (const vector< BlockEdge > & ref, vector< FlowBlock * > & duplist) static private
Find blocks that are at the end of multiple edges.
Parameters
ref is the list of BlockEdges to search
duplist will contain the list of blocks with duplicate edges
void FlowBlock::flipInPlaceExecute (void) inline virtual
Perform the flip to normalize conditional branch executed by this block.
This reverses the outgoing edge order in the right basic blocks, but does not modify the instructions directly.
Reimplemented in BlockCondition, and BlockBasic.
Referenced by lastOp(), and BlockIf::preferComplement().
int4 FlowBlock::flipInPlaceTest (vector< PcodeOp * > & fliplist) const inline virtual
Test normalizing the conditional branch in this.
Find the set of PcodeOp objects that need to be adjusted to flip the condition this FlowBlock calculates.
Return:
0 if the flip would normalize the condition
1 if the flip doesn't affect normalization of the condition
2 if the flip produces an unnormalized condition
Parameters
fliplist will contain the PcodeOps that need to be adjusted
Returns
0 if the condition will be normalized, 1 or 2 otherwise
Reimplemented in BlockCondition, and BlockBasic.
Referenced by BlockCondition::flipInPlaceTest(), lastOp(), and BlockIf::preferComplement().
const FlowBlock * FlowBlock::getFrontLeaf (void) const
Get the first leaf FlowBlock.
Keep descending tree hierarchy, taking the front block, until we get to the bottom copy block
Returns
the first leaf FlowBlock to execute
References getType(), and subBlock().
Referenced by BlockSwitch::addCase(), PrintC::emitAnyLabelStatement(), PrintC::emitLabel(), getInRevIndex(), BlockGoto::gotoPrints(), BlockSwitch::grabCaseBasic(), BlockGraph::markCopyBlock(), BlockGraph::nextFlowAfter(), BlockGoto::nextFlowAfter(), BlockWhileDo::nextFlowAfter(), BlockFor::nextFlowAfter(), BlockInfLoop::nextFlowAfter(), BlockSwitch::nextFlowAfter(), BlockGoto::saveXmlBody(), BlockMultiGoto::saveXmlBody(), and BlockIf::saveXmlBody().
FlowBlock * FlowBlock::getFrontLeaf (void)
Get the first leaf FlowBlock.
Keep descending tree hierarchy, taking the front block, until we get to the bottom copy block
Returns
the first leaf FlowBlock to execute
References getType(), and subBlock().
int4 FlowBlock::getInIndex (const FlowBlock * bl) const
Get the incoming edge index for the given FlowBlock.
Search through incoming blocks in edge order for the given block.
Parameters
bl is the given FlowBlock
Returns
the matching edge index or -1 if bl doesn't flow into this
References BlockEdge::point.
Referenced by BlockSwitch::addCase(), Funcdata::blockRemoveInternal(), Funcdata::branchRemoveInternal(), BlockSwitch::grabCaseBasic(), isLoopOut(), and BlockBasic::unblockedMulti().
JumpTable * FlowBlock::getJumptable (void) const
Get the JumpTable associated this block.
If this FlowBlock was ends with a computed jump, retrieve the associated JumpTable object
Returns
the JumpTable object or NULL
References Funcdata::findJumpTable(), BlockBasic::getFuncdata(), and PcodeOp::getParent().
Referenced by BlockSwitch::BlockSwitch(), and isGotoOut().
int4 FlowBlock::getOutIndex (const FlowBlock * bl) const
Get the outgoing edge index for the given FlowBlock.
Search through outgoing blocks in edge order for the given block.
Parameters
bl is the given FlowBlock
Returns
the matching edge index or -1 if bl doesn't flow out of this
References BlockEdge::point.
Referenced by FloatingEdge::getCurrentEdge(), isLoopOut(), and Funcdata::nodeJoinCreateBlock().
FlowBlock * FlowBlock::getSplitPoint (void) inline virtual
Get the leaf splitting block.
If this block ends with a conditional branch, return the deepest component block that performs the split. This component needs to be able to perform flipInPlaceTest() and flipInPlaceExecute()
Returns
the component FlowBlock or NULL if this doesn't end in a conditional branch
Reimplemented in BlockCondition, BlockList, BlockCopy, and BlockBasic.
Referenced by BlockCondition::flipInPlaceTest(), BlockCopy::getSplitPoint(), BlockList::getSplitPoint(), lastOp(), and BlockIf::preferComplement().
void FlowBlock::halfDeleteInEdge (int4 slot) private
Delete the in half of an edge, correcting indices.
Parameters
slot is the index of the incoming edge being altered
References outofthis, BlockEdge::point, and BlockEdge::reverse_index.
Referenced by eliminateOutDups(), removeOutEdge(), and replaceOutEdge().
void FlowBlock::halfDeleteOutEdge (int4 slot) private
Delete the out half of an edge, correcting indices.
Parameters
slot is the index of the outgoing edge being altered
References intothis, BlockEdge::point, and BlockEdge::reverse_index.
Referenced by eliminateInDups(), removeInEdge(), and replaceInEdge().
bool FlowBlock::hasLoopIn (void) const
Is there a looping edge coming into this block.
Returns
true if this is the top of a loop
References BlockEdge::label.
Referenced by RulePullsubMulti::applyOp(), and sizeIn().
bool FlowBlock::hasLoopOut (void) const
Is there a looping edge going out of this block.
Returns
true if this is the bottom of a loop
References BlockEdge::label.
Referenced by sizeIn().
bool FlowBlock::isJumpTarget (void) const
Return true if non-fallthru jump flows into this.
return true if block is the target of a jump
References index, and BlockEdge::point.
Referenced by PrintC::emitLabelStatement(), and getFlipPath().
void FlowBlock::markLabelBumpUp (bool bump) virtual
Let hierarchical blocks steal labels of their (first) components.
Parameters
bump if true, mark that labels for this block are printed by somebody higher in hierarchy
Reimplemented in BlockInfLoop, BlockDoWhile, BlockFor, BlockWhileDo, and BlockGraph.
Referenced by BlockGraph::markLabelBumpUp().
FlowBlock::block_type FlowBlock::nameToType (const string & nm) static
Get the block_type associated with a name string.
Given a string describing a FlowBlock type, return the block_type. This is currently only used by the restoreXml() process. TODO: Fill in the remaining names and types
Parameters
nm is the name string
Returns
the corresponding block_type
Referenced by BlockMap::createBlock(), and isGotoOut().
bool FlowBlock::negateCondition (bool toporbottom) virtual
Flip the condition computed by this.
Flip the order of outgoing edges (at least). This should also affect the original op causing the condition. Note: we don't have to flip at all levels of the hierarchy only at the top and at the bottom
Parameters
toporbottom is true if this is the top outermost block of the hierarchy getting negated
Returns
true if a change was made to data-flow
Reimplemented in BlockCondition, BlockList, BlockCopy, and BlockBasic.
Referenced by BlockBasic::flipInPlaceExecute(), lastOp(), BlockBasic::negateCondition(), BlockCopy::negateCondition(), BlockList::negateCondition(), BlockCondition::negateCondition(), CollapseStructure::ruleBlockDoWhile(), CollapseStructure::ruleBlockFor(), CollapseStructure::ruleBlockGoto(), CollapseStructure::ruleBlockIfNoExit(), CollapseStructure::ruleBlockOr(), CollapseStructure::ruleBlockProperIf(), and CollapseStructure::ruleBlockWhileDo().
FlowBlock * FlowBlock::nextFlowAfter (const FlowBlock * bl) const inline virtual
Get the leaf FlowBlock that will execute after the given FlowBlock.
Within the hierarchy of this FlowBlock, assume the given FlowBlock will fall-thru in its execution at some point. Return the first leaf block (BlockBasic or BlockCopy) that will execute after the given FlowBlock completes, assuming this is a unique block.
Parameters
bl is the given FlowBlock
Returns
the next FlowBlock to execute or NULL
Reimplemented in BlockSwitch, BlockInfLoop, BlockDoWhile, BlockFor, BlockWhileDo, BlockIf, BlockCondition, BlockMultiGoto, BlockGoto, and BlockGraph.
Referenced by BlockGoto::gotoPrints(), BlockIf::nextFlowAfter(), and BlockSwitch::nextFlowAfter().
const FlowBlock * FlowBlock::nextInFlow (void) const
Return next block to be executed in flow.
If there are two branches, pick the fall-thru branch
Returns
the next block in flow, or NULL otherwise
References PcodeOp::code(), CPUI_CBRANCH, and PcodeOp::isFallthruTrue().
Referenced by PrintC::emitBlockLs(), and restoreXmlBody().
bool FlowBlock::preferComplement (Funcdata & data) inline virtual
Rearrange this hierarchy to simplify boolean expressions.
For the instructions in this block, decide if the control-flow structure can be rearranged so that boolean expressions come out more naturally.
Parameters
data is the function to analyze
Returns
true if a change was made
Reimplemented in BlockIf.
Referenced by ActionPreferComplement::apply(), and lastOp().
void FlowBlock::printHeader (ostream & s) const virtual
Print a simple description of this to stream.
Only print a header for this single block
Parameters
s is the output stream
Reimplemented in BlockSwitch, BlockInfLoop, BlockDoWhile, BlockFor, BlockWhileDo, BlockIf, BlockCondition, BlockList, BlockMultiGoto, BlockGoto, BlockCopy, and BlockBasic.
Referenced by BlockBasic::printHeader(), BlockCopy::printHeader(), BlockGoto::printHeader(), BlockMultiGoto::printHeader(), BlockList::printHeader(), BlockCondition::printHeader(), BlockIf::printHeader(), BlockWhileDo::printHeader(), BlockFor::printHeader(), BlockDoWhile::printHeader(), BlockInfLoop::printHeader(), BlockSwitch::printHeader(), and scopeBreak().
void FlowBlock::printTree (ostream & s, int4 level) const virtual
Print tree structure of any blocks owned by this.
Recursively print out the hierarchical structure of this FlowBlock.
Parameters
s is the output stream
level is the current level of indentation
Reimplemented in BlockCopy, and BlockGraph.
Referenced by BlockGraph::printTree().
void FlowBlock::removeInEdge (int4 slot) private
Remove an incoming edge.
Parameters
slot is the index of the incoming edge to remove
References halfDeleteOutEdge().
Referenced by BlockGraph::removeEdge().
void FlowBlock::removeOutEdge (int4 slot) private
Remove an outgoing edge.
Parameters
slot is the index of the outgoing edge to remove
References halfDeleteInEdge().
Referenced by BlockGraph::calcForwardDominator(), BlockGraph::removeFromFlow(), and BlockGraph::spliceBlock().
void FlowBlock::replaceEdgeMap (vector< BlockEdge > & vec) static private
Update block references in edges with copy map.
Block references are updated using the getCopyMap() reference on the original block
Parameters
vec is the list of edges whose block references should be updated
void FlowBlock::replaceEdgesThru (int4 in, int4 out) private
Remove this from flow between two blocks.
Remove edge in and out from this block, but create a new edge between the in-block and the out-block, preserving position in the in/out edge lists.
Parameters
in is the index of the incoming block
out is the index of the outgoing block
References intothis, and outofthis.
Referenced by BlockGraph::removeFromFlowSplit().
void FlowBlock::replaceInEdge (int4 num, FlowBlock * b) private
Make an incoming edge flow from a given block.
The original edge, which must exist, is replaced.
Parameters
num is the index of the incoming edge
b is the new incoming block
References BlockEdge::BlockEdge(), halfDeleteOutEdge(), BlockEdge::label, outofthis, and BlockEdge::reverse_index.
Referenced by BlockGraph::moveOutEdge(), and BlockGraph::selfIdentify().
void FlowBlock::replaceOutEdge (int4 num, FlowBlock * b) private
Make an outgoing edge flow to a given block.
The original edge, which must exist is replaced.
Parameters
num is the index of the outgoing edge
b is the new outgoing block
References BlockEdge::BlockEdge(), halfDeleteInEdge(), intothis, BlockEdge::label, and BlockEdge::reverse_index.
Referenced by BlockGraph::removeFromFlow(), BlockGraph::selfIdentify(), and BlockGraph::switchEdge().
void FlowBlock::replaceUsingMap (void) private
Update references to other blocks using getCopyMap()
Run through incoming and outgoing edges and replace FlowBlock references with the FlowBlock accessed via the getCopyMap() method.
void FlowBlock::restoreNextInEdge (const Element * el, BlockMap & resolver) private
Restore the next input edge from XML.
Parameters
el is the <edge> element
resolver is used to resolve block references
References BlockEdge::BlockEdge(), BlockEdge::label, BlockEdge::point, BlockEdge::restoreXml(), and BlockEdge::reverse_index.
void FlowBlock::restoreXml (const Element * el, BlockMap & resolver)
Restore this from an XML stream.
Recover this and all it sub-components from an XML <block> tag.
This will construct all the sub-components using resolver as a factory.
Parameters
el is the root XML element
resolver acts as a factory and resolves cross-references
References Element::getChildren().
Referenced by BlockGraph::restoreXml(), and BlockGraph::restoreXmlBody().
virtual void FlowBlock::restoreXmlBody (List::const_iterator & iter, List::const_iterator enditer, BlockMap & resolver) inline virtual
Restore details about this FlowBlock from an XML stream.
Parameters
iter is an iterator to XML elements containing component tags etc.
enditer marks the end of the XML tags
resolver is used to recover FlowBlock objects based on XML references
Reimplemented in BlockBasic, and BlockGraph.
References nextInFlow(), BlockEdge::restoreXml(), restoreXmlEdges(), BlockEdge::saveXml(), and saveXmlEdges().
Referenced by BlockGraph::restoreXmlBody().
void FlowBlock::restoreXmlEdges (List::const_iterator & iter, List::const_iterator enditer, BlockMap & resolver)
Restore edges from an XML stream.
Parameters
iter is an iterator to the <edge> tags
enditer marks the end of the list of tags
resolver is used to recover FlowBlock cross-references
References Element::getName().
Referenced by restoreXmlBody().
void FlowBlock::restoreXmlHeader (const Element * el) virtual
Restore basic information for XML attributes.
Parameters
el is the XML element to pull attributes from
References Element::getAttributeValue().
Referenced by finalizePrinting().
bool FlowBlock::restrictedByConditional (const FlowBlock * cond) const
Check if the condition from the given block holds for this block.
We assume the given block has 2 out-edges and that this block is immediately reached by one of these two edges. Some condition holds when traversing the out-edge to this, and the complement of the condition holds for traversing the other out-edge. We verify that the condition holds for this entire block. More specifically, we check that that there is no path to this through the sibling edge, where the complement of the condition holds (unless we loop back through the conditional block).
Parameters
cond is the conditional block with 2 out-edges
Returns
true if the condition holds for this block
References getImmedDom().
Referenced by ActionConditionalConst::apply(), ValueSetSolver::applyConstraints(), and getInRevIndex().
void FlowBlock::saveXml (ostream & s) const
Write out this to an XML stream.
Serialize this and all its sub-components as an XML <block> tag.
Parameters
s is the output stream
Referenced by StructureGraph::rawAction().
void FlowBlock::saveXmlEdges (ostream & s) const
Save edge information to an XML stream.
Write <edge> tags to stream
Parameters
s is the output stream
Referenced by restoreXmlBody(), and Funcdata::saveXmlTree().
void FlowBlock::saveXmlHeader (ostream & s) const virtual
Save basic information as XML attributes.
Parameters
s is the output stream
Reimplemented in BlockCondition, and BlockCopy.
References a_v_i().
Referenced by finalizePrinting(), BlockCopy::saveXmlHeader(), and BlockCondition::saveXmlHeader().
void FlowBlock::setGotoBranch (int4 i)
Mark a goto branch.
This is the main entry point for marking a branch from one block to another as unstructured.
Parameters
i is the index of the outgoing edge to mark
Referenced by CollapseStructure::checkSwitchSkips(), Funcdata::forceGoto(), getVisitCount(), CollapseStructure::markExitsAsGotos(), CollapseStructure::ruleCaseFallthru(), and CollapseStructure::selectGoto().
void FlowBlock::setOutEdgeFlag (int4 i, uint4 lab) private
Apply an out edge label.
Parameters
i is the index of the outgoing edge
lab is the new edge label
References intothis.
Referenced by BlockGraph::addLoopEdge(), BlockGraph::findIrreducible(), BlockGraph::findSpanningTree(), setBackEdge(), setDefaultSwitch(), and setLoopExit().
string FlowBlock::typeToName (FlowBlock::block_type bt) static
Get the name string associated with a block_type.
For use in serializng FlowBlocks to XML.
Parameters
bt is the block_type
Returns
the corresponding name string
Referenced by isGotoOut(), and BlockGraph::saveXmlBody().
The documentation for this class was generated from the following files:
block.hh
block.cc