decompiler: BlockCondition Class Reference
BlockCondition Class Reference
Two conditional blocks combined into one conditional using BOOL_AND or BOOL_OR.
#include <block.hh>
Public Member Functions
BlockCondition (OpCode c)
Construct given the boolean operation.
OpCode getOpcode (void) const
Get the boolean operation.
virtual block_type getType (void) const
Get the FlowBlock type of this.
virtual void scopeBreak (int4 curexit, int4 curloopexit)
Mark unstructured edges that should be breaks.
virtual void printHeader (ostream &s) const
Print a simple description of this to stream.
virtual void emit (PrintLanguage *lng) const
Emit the instructions in this FlowBlock as structured code.
virtual bool negateCondition (bool toporbottom)
Flip the condition computed by this.
virtual FlowBlock * getSplitPoint (void)
Get the leaf splitting block.
virtual int4 flipInPlaceTest (vector< PcodeOp * > &fliplist) const
Test normalizing the conditional branch in this.
virtual void flipInPlaceExecute (void)
Perform the flip to normalize conditional branch executed by this block.
virtual PcodeOp * lastOp (void) const
Get the last PcodeOp executed by this FlowBlock.
virtual bool isComplex (void) const
Is this too complex to be a condition (BlockCondition)
virtual FlowBlock * nextFlowAfter (const FlowBlock *bl) const
Get the leaf FlowBlock that will execute after the given FlowBlock.
virtual void saveXmlHeader (ostream &s) const
Save basic information as XML attributes.
Public Member Functions inherited from BlockGraph
void clear (void)
Clear all component FlowBlock objects.
virtual ~BlockGraph (void)
Destructor.
const vector< FlowBlock * > & getList (void) const
Get the list of component FlowBlock objects.
int4 getSize (void) const
Get the number of components.
FlowBlock * getBlock (int4 i) const
Get the i-th component.
virtual FlowBlock * subBlock (int4 i) const
Get the i-th component block.
virtual void markUnstructured (void)
Mark target blocks of any unstructured edges.
virtual void markLabelBumpUp (bool bump)
Let hierarchical blocks steal labels of their (first) components.
virtual void printTree (ostream &s, int4 level) const
Print tree structure of any blocks owned by this.
virtual void printRaw (ostream &s) const
Print raw instructions contained in this FlowBlock.
virtual void finalizePrinting (const Funcdata &data) const
Make any final configurations necessary to print the block.
virtual void saveXmlBody (ostream &s) const
Save detail about components to an XML stream.
virtual void restoreXmlBody (List::const_iterator &iter, List::const_iterator enditer, BlockMap &resolver)
Restore details about this FlowBlock from an XML stream.
void restoreXml (const Element *el, const AddrSpaceManager *m)
Restore this BlockGraph from an XML stream.
void addEdge (FlowBlock *begin, FlowBlock *end)
Add a directed edge between component FlowBlocks.
void addLoopEdge (FlowBlock *begin, int4 outindex)
Mark a given edge as a loop edge.
void removeEdge (FlowBlock *begin, FlowBlock *end)
Remove an edge between component FlowBlocks.
void switchEdge (FlowBlock *in, FlowBlock *outbefore, FlowBlock *outafter)
Move an edge from one out FlowBlock to another.
void moveOutEdge (FlowBlock *blold, int4 slot, FlowBlock *blnew)
Move indicated out edge to a new FlowBlock.
void removeBlock (FlowBlock *bl)
Remove a FlowBlock from this BlockGraph.
void removeFromFlow (FlowBlock *bl)
Remove given FlowBlock preserving flow in this.
void removeFromFlowSplit (FlowBlock *bl, bool flipflow)
Remove FlowBlock splitting flow between input and output edges.
void spliceBlock (FlowBlock *bl)
Splice given FlowBlock together with its output.
void setStartBlock (FlowBlock *bl)
Set the entry point FlowBlock for this graph.
FlowBlock * getStartBlock (void) const
Get the entry point FlowBlock.
FlowBlock * newBlock (void)
Build a new plain FlowBlock.
BlockBasic * newBlockBasic (Funcdata *fd)
Build a new BlockBasic.
BlockCopy * newBlockCopy (FlowBlock *bl)
Build a new BlockCopy.
BlockGoto * newBlockGoto (FlowBlock *bl)
Build a new BlockGoto.
BlockMultiGoto * newBlockMultiGoto (FlowBlock *bl, int4 outedge)
Build a new BlockMultiGoto.
BlockList * newBlockList (const vector< FlowBlock * > &nodes)
Build a new BlockList.
BlockCondition * newBlockCondition (FlowBlock *b1, FlowBlock *b2)
Build a new BlockCondition.
BlockIf * newBlockIfGoto (FlowBlock *cond)
Build a new BlockIfGoto.
BlockIf * newBlockIf (FlowBlock *cond, FlowBlock *tc)
Build a new BlockIf.
BlockIf * newBlockIfElse (FlowBlock *cond, FlowBlock *tc, FlowBlock *fc)
Build a new BlockIfElse.
BlockWhileDo * newBlockWhileDo (FlowBlock *cond, FlowBlock *cl)
Build a new BlockWhileDo.
BlockFor * newBlockFor (FlowBlock *cond, FlowBlock *cl)
Build a new BlockFor.
BlockDoWhile * newBlockDoWhile (FlowBlock *condcl)
Build a new BlockDoWhile.
BlockInfLoop * newBlockInfLoop (FlowBlock *body)
Build a new BlockInfLoop.
BlockSwitch * newBlockSwitch (const vector< FlowBlock * > &cs, bool hasExit)
Build a new BlockSwitch.
void orderBlocks (void)
void buildCopy (const BlockGraph &graph)
Build a copy of a BlockGraph.
void clearVisitCount (void)
Clear the visit count in all node FlowBlocks.
void calcForwardDominator (const vector< FlowBlock * > &rootlist)
Calculate forward dominators.
void buildDomTree (vector< vector< FlowBlock * > > &child) const
Build the dominator tree.
int4 buildDomDepth (vector< int4 > &depth) const
Calculate dominator depths.
void buildDomSubTree (vector< FlowBlock * > &res, FlowBlock *root) const
Collect nodes from a dominator sub-tree.
void calcLoop (void)
Calculate loop edges.
void collectReachable (vector< FlowBlock * > &res, FlowBlock *bl, bool un) const
Collect reachable/unreachable FlowBlocks from a given start FlowBlock.
void structureLoops (vector< FlowBlock * > &rootlist)
Label loop edges.
Public Member Functions inherited from FlowBlock
FlowBlock (void)
Construct a block with no edges.
virtual ~FlowBlock (void)
Destructor.
int4 getIndex (void) const
Get the index assigned to this block.
FlowBlock * getParent (void)
Get the parent FlowBlock of this.
FlowBlock * getImmedDom (void) const
Get the immediate dominator FlowBlock.
FlowBlock * getCopyMap (void) const
Get the mapped FlowBlock.
const FlowBlock * getParent (void) const
Get the parent FlowBlock of this.
uint4 getFlags (void) const
Get the block_flags properties.
virtual Address getStart (void) const
Get the starting address of code in this FlowBlock.
virtual Address getStop (void) const
Get the ending address of code in this FlowBlock.
virtual const FlowBlock * getExitLeaf (void) const
Get the FlowBlock to which this block exits.
virtual bool preferComplement (Funcdata &data)
Rearrange this hierarchy to simplify boolean expressions.
virtual void restoreXmlHeader (const Element *el)
Restore basic information for XML attributes.
void saveXmlEdges (ostream &s) const
Save edge information to an XML stream.
void restoreXmlEdges (List::const_iterator &iter, List::const_iterator enditer, BlockMap &resolver)
Restore edges from an XML stream.
void saveXml (ostream &s) const
Write out this to an XML stream.
void restoreXml (const Element *el, BlockMap &resolver)
Restore this from an XML stream.
const FlowBlock * nextInFlow (void) const
Return next block to be executed in flow.
void setVisitCount (int4 i)
Set the number of times this block has been visited.
int4 getVisitCount (void) const
Get the count of visits.
void setGotoBranch (int4 i)
Mark a goto branch.
void setDefaultSwitch (int4 i)
Mark an edge as the switch default.
bool isMark (void) const
Return true if this block has been marked.
void setMark (void)
Mark this block.
void clearMark (void)
Clear any mark on this block.
void setDonothingLoop (void)
Label this as a do nothing loop.
void setDead (void)
Label this as dead.
bool hasSpecialLabel (void) const
Return true if this uses a different label.
bool isJoined (void) const
Return true if this is a joined basic block.
bool isDuplicated (void) const
Return true if this is a duplicated block.
void setLoopExit (int4 i)
Label the edge exiting this as a loop.
void clearLoopExit (int4 i)
Clear the loop exit edge.
void setBackEdge (int4 i)
Label the back edge of a loop.
bool getFlipPath (void) const
Have out edges been flipped.
bool isJumpTarget (void) const
Return true if non-fallthru jump flows into this.
FlowBlock * getFalseOut (void) const
Get the false output FlowBlock.
FlowBlock * getTrueOut (void) const
Get the true output FlowBlock.
FlowBlock * getOut (int4 i)
Get the i-th output FlowBlock.
const FlowBlock * getOut (int4 i) const
Get i-th output FlowBlock.
int4 getOutRevIndex (int4 i) const
Get the input index of the i-th output FlowBlock.
FlowBlock * getIn (int4 i)
Get the i-th input FlowBlock.
const FlowBlock * getIn (int4 i) const
Get the i-th input FlowBlock.
int4 getInRevIndex (int4 i) const
Get the output index of the i-th input FlowBlock.
const FlowBlock * getFrontLeaf (void) const
Get the first leaf FlowBlock.
FlowBlock * getFrontLeaf (void)
Get the first leaf FlowBlock.
int4 calcDepth (const FlowBlock *leaf) const
Get the depth of the given component FlowBlock.
bool dominates (const FlowBlock *subBlock) const
Does this block dominate the given block.
bool restrictedByConditional (const FlowBlock *cond) const
Check if the condition from the given block holds for this block.
int4 sizeOut (void) const
Get the number of out edges.
int4 sizeIn (void) const
Get the number of in edges.
bool hasLoopIn (void) const
Is there a looping edge coming into this block.
bool hasLoopOut (void) const
Is there a looping edge going out of this block.
bool isLoopIn (int4 i) const
Is the i-th incoming edge a loop edge.
bool isLoopOut (int4 i) const
Is the i-th outgoing edge a loop edge.
int4 getInIndex (const FlowBlock *bl) const
Get the incoming edge index for the given FlowBlock.
int4 getOutIndex (const FlowBlock *bl) const
Get the outgoing edge index for the given FlowBlock.
bool isDefaultBranch (int4 i) const
Is the i-th out edge the switch default edge.
bool isLabelBumpUp (void) const
Are labels for this printed by the parent.
bool isUnstructuredTarget (void) const
Is this the target of an unstructured goto.
bool isInteriorGotoTarget (void) const
Is there an unstructured goto to this block's interior.
bool hasInteriorGoto (void) const
Is there an unstructured goto out of this block's interior.
bool isEntryPoint (void) const
Is the entry point of the function.
bool isSwitchOut (void) const
Is this a switch block.
bool isDonothingLoop (void) const
Is this a do nothing block.
bool isDead (void) const
Is this block dead.
bool isTreeEdgeIn (int4 i) const
Is the i-th incoming edge part of the spanning tree.
bool isBackEdgeIn (int4 i) const
Is the i-th incoming edge a back edge.
bool isBackEdgeOut (int4 i) const
Is the i-th outgoing edge a back edge.
bool isIrreducibleOut (int4 i) const
Is the i-th outgoing edge an irreducible edge.
bool isIrreducibleIn (int4 i) const
Is the i-th incoming edge an irreducible edge.
bool isDecisionOut (int4 i) const
Can this and the i-th output be merged into a BlockIf or BlockList.
bool isDecisionIn (int4 i) const
Can this and the i-th input be merged into a BlockIf or BlockList.
bool isLoopDAGOut (int4 i) const
Is the i-th outgoing edge part of the DAG sub-graph.
bool isLoopDAGIn (int4 i) const
Is the i-th incoming edge part of the DAG sub-graph.
bool isGotoIn (int4 i) const
Is the i-th incoming edge unstructured.
bool isGotoOut (int4 i) const
Is the i-th outgoing edge unstructured.
JumpTable * getJumptable (void) const
Get the JumpTable associated this block.
Private Attributes
OpCode opc
Type of boolean operation.
Additional Inherited Members
Public Types inherited from FlowBlock
enum block_type {
t_plain, t_basic, t_graph, t_copy,
t_goto, t_multigoto, t_ls, t_condition,
t_if, t_whiledo, t_dowhile, t_switch,
t_infloop, t_for
}
The possible block types.
enum block_flags {
f_goto_goto = 1, f_break_goto = 2, f_continue_goto = 4, f_switch_out = 0x10,
f_unstructured_targ = 0x20, f_mark = 0x80, f_mark2 = 0x100, f_entry_point = 0x200,
f_interior_gotoout = 0x400, f_interior_gotoin = 0x800, f_label_bumpup = 0x1000, f_donothing_loop = 0x2000,
f_dead = 0x4000, f_whiledo_overflow = 0x8000, f_flip_path = 0x10000, f_joined_block = 0x20000,
f_duplicate_block = 0x40000
}
Boolean properties of blocks.
enum edge_flags {
f_goto_edge = 1, f_loop_edge = 2, f_defaultswitch_edge = 4, f_irreducible = 8,
f_tree_edge = 0x10, f_forward_edge = 0x20, f_cross_edge = 0x40, f_back_edge = 0x80,
f_loop_exit_edge = 0x100
}
Boolean properties on edges.
Static Public Member Functions inherited from FlowBlock
static block_type nameToType (const string &name)
Get the block_type associated with a name string.
static string typeToName (block_type bt)
Get the name string associated with a block_type.
static bool compareBlockIndex (const FlowBlock *bl1, const FlowBlock *bl2)
Compare FlowBlock by index.
static bool compareFinalOrder (const FlowBlock *bl1, const FlowBlock *bl2)
Final FlowBlock comparison.
static FlowBlock * findCommonBlock (FlowBlock *bl1, FlowBlock *bl2)
Find the common dominator of two FlowBlocks.
static FlowBlock * findCommonBlock (const vector< FlowBlock * > &blockSet)
Find common dominator of multiple FlowBlocks.
Protected Member Functions inherited from BlockGraph
void swapBlocks (int4 i, int4 j)
Swap the positions two component FlowBlocks.
Protected Member Functions inherited from FlowBlock
void setFlag (uint4 fl)
Set a boolean property.
void clearFlag (uint4 fl)
Clear a boolean property.
Static Protected Member Functions inherited from BlockGraph
static void markCopyBlock (FlowBlock *bl, uint4 fl)
Set properties on the first leaf FlowBlock.
Detailed Description
Two conditional blocks combined into one conditional using BOOL_AND or BOOL_OR.
This class is used to construct full conditional expressions. An instance glues together two components, each with two outgoing edges. Of the four edges, 1 must go between the two components, and 2 must go to the same exit block, so there will be exactly 2 distinct exit blocks in total. The new condition can be interpreted as either:
If condition one and condition two, goto exit 0, otherwise goto exit 1.
If condition one or condition two, goto exit 1, otherwise goto exit 0.
depending on the boolean operation setting for the condition
Member Function Documentation
virtual void BlockCondition::emit (PrintLanguage * lng) const inline virtual
Emit the instructions in this FlowBlock as structured code.
This is the main entry point, at the control-flow level, for printing structured code.
Parameters
lng is the PrintLanguage that provides details of the high-level language being printed
Reimplemented from BlockGraph.
References PrintLanguage::emitBlockCondition().
void BlockCondition::flipInPlaceExecute (void) virtual
Perform the flip to normalize conditional branch executed by this block.
This reverses the outgoing edge order in the right basic blocks, but does not modify the instructions directly.
Reimplemented from FlowBlock.
References CPUI_BOOL_AND, and CPUI_BOOL_OR.
int4 BlockCondition::flipInPlaceTest (vector< PcodeOp * > & fliplist) const virtual
Test normalizing the conditional branch in this.
Find the set of PcodeOp objects that need to be adjusted to flip the condition this FlowBlock calculates.
Return:
0 if the flip would normalize the condition
1 if the flip doesn't affect normalization of the condition
2 if the flip produces an unnormalized condition
Parameters
fliplist will contain the PcodeOps that need to be adjusted
Returns
0 if the condition will be normalized, 1 or 2 otherwise
Reimplemented from FlowBlock.
References FlowBlock::flipInPlaceTest(), and FlowBlock::getSplitPoint().
virtual FlowBlock* BlockCondition::getSplitPoint (void) inline virtual
Get the leaf splitting block.
If this block ends with a conditional branch, return the deepest component block that performs the split. This component needs to be able to perform flipInPlaceTest() and flipInPlaceExecute()
Returns
the component FlowBlock or NULL if this doesn't end in a conditional branch
Reimplemented from FlowBlock.
bool BlockCondition::negateCondition (bool toporbottom) virtual
Flip the condition computed by this.
Flip the order of outgoing edges (at least). This should also affect the original op causing the condition. Note: we don't have to flip at all levels of the hierarchy only at the top and at the bottom
Parameters
toporbottom is true if this is the top outermost block of the hierarchy getting negated
Returns
true if a change was made to data-flow
Reimplemented from FlowBlock.
References CPUI_BOOL_AND, CPUI_BOOL_OR, and FlowBlock::negateCondition().
FlowBlock * BlockCondition::nextFlowAfter (const FlowBlock * bl) const virtual
Get the leaf FlowBlock that will execute after the given FlowBlock.
Within the hierarchy of this FlowBlock, assume the given FlowBlock will fall-thru in its execution at some point. Return the first leaf block (BlockBasic or BlockCopy) that will execute after the given FlowBlock completes, assuming this is a unique block.
Parameters
bl is the given FlowBlock
Returns
the next FlowBlock to execute or NULL
Reimplemented from BlockGraph.
void BlockCondition::printHeader (ostream & s) const virtual
Print a simple description of this to stream.
Only print a header for this single block
Parameters
s is the output stream
Reimplemented from FlowBlock.
References CPUI_BOOL_AND, and FlowBlock::printHeader().
void BlockCondition::saveXmlHeader (ostream & s) const virtual
Save basic information as XML attributes.
Parameters
s is the output stream
Reimplemented from FlowBlock.
References a_v(), get_opname(), and FlowBlock::saveXmlHeader().
The documentation for this class was generated from the following files:
block.hh
block.cc