decompiler: ScopeInternal Class Reference
ScopeInternal Class Reference
An in-memory implementation of the Scope interface.
#include <database.hh>
Public Member Functions
ScopeInternal (uint8 id, const string &nm, Architecture *g)
Construct the Scope.
ScopeInternal (uint8 id, const string &nm, Architecture *g, Scope *own)
Construct as a cache.
virtual void clear (void)
Clear all symbols from this scope.
virtual void categorySanity (void)
Make sure Symbol categories are sane.
virtual void clearCategory (int4 cat)
Clear all symbols of the given category from this scope.
virtual void clearUnlocked (void)
Clear all unlocked symbols from this scope.
virtual void clearUnlockedCategory (int4 cat)
Clear unlocked symbols of the given category from this scope.
virtual void adjustCaches (void)
Let scopes internally adjust any caches.
virtual MapIterator begin (void) const
Beginning iterator to mapped SymbolEntrys.
virtual MapIterator end (void) const
Ending iterator to mapped SymbolEntrys.
virtual list< SymbolEntry >::const_iterator beginDynamic (void) const
Beginning iterator to dynamic SymbolEntrys.
virtual list< SymbolEntry >::const_iterator endDynamic (void) const
Ending iterator to dynamic SymbolEntrys.
virtual list< SymbolEntry >::iterator beginDynamic (void)
Beginning iterator to dynamic SymbolEntrys.
virtual list< SymbolEntry >::iterator endDynamic (void)
Ending iterator to dynamic SymbolEntrys.
virtual void removeSymbolMappings (Symbol *symbol)
Remove all SymbolEntrys from the given Symbol.
virtual void removeSymbol (Symbol *symbol)
Remove the given Symbol from this Scope.
virtual void renameSymbol (Symbol *sym, const string &newname)
Rename a Symbol within this Scope.
virtual void retypeSymbol (Symbol *sym, Datatype *ct)
Change the data-type of a Symbol within this Scope.
virtual void setAttribute (Symbol *sym, uint4 attr)
Set boolean Varnode properties on a Symbol.
virtual void clearAttribute (Symbol *sym, uint4 attr)
Clear boolean Varnode properties on a Symbol.
virtual void setDisplayFormat (Symbol *sym, uint4 attr)
Set the display format for a Symbol.
virtual SymbolEntry * findAddr (const Address &addr, const Address &usepoint) const
Find a Symbol at a given address and usepoint.
virtual SymbolEntry * findContainer (const Address &addr, int4 size, const Address &usepoint) const
Find the smallest Symbol containing the given memory range.
virtual SymbolEntry * findClosestFit (const Address &addr, int4 size, const Address &usepoint) const
Find Symbol which is the closest fit to the given memory range.
virtual Funcdata * findFunction (const Address &addr) const
Find the function starting at the given address.
virtual ExternRefSymbol * findExternalRef (const Address &addr) const
Find an external reference at the given address.
virtual LabSymbol * findCodeLabel (const Address &addr) const
Find a label Symbol at the given address.
virtual SymbolEntry * findOverlap (const Address &addr, int4 size) const
Find first Symbol overlapping the given memory range.
virtual void findByName (const string &name, vector< Symbol * > &res) const
Find a Symbol by name within this Scope.
virtual bool isNameUsed (const string &nm, const Scope *op2) const
Check if the given name is occurs within the given scope path.
virtual Funcdata * resolveExternalRefFunction (ExternRefSymbol *sym) const
Convert an external reference to the referenced function.
virtual string buildVariableName (const Address &addr, const Address &pc, Datatype *ct, int4 &index, uint4 flags) const
Given an address and data-type, build a suitable generic symbol name.
virtual string buildUndefinedName (void) const
Build a formal undefined name, used internally when a Symbol is not given a name.
virtual string makeNameUnique (const string &nm) const
Produce a version of the given symbol name that won't collide with other names in this Scope.
virtual void saveXml (ostream &s) const
Write out this as a <scope> XML tag.
virtual void restoreXml (const Element *el)
Restore this Scope from a <scope> XML tag.
virtual void printEntries (ostream &s) const
Dump a description of all SymbolEntry objects to a stream.
virtual int4 getCategorySize (int4 cat) const
Get the number of Symbols in the given category.
virtual Symbol * getCategorySymbol (int4 cat, int4 ind) const
Retrieve a Symbol by index within a specific category.
virtual void setCategory (Symbol *sym, int4 cat, int4 ind)
Set the category and index for the given Symbol.
void assignDefaultNames (int4 &base)
Assign a default name (via buildVariableName) to any unnamed symbol.
set< Symbol * >::const_iterator beginMultiEntry (void) const
Start of symbols with more than one entry.
set< Symbol * >::const_iterator endMultiEntry (void) const
End of symbols with more than one entry.
Public Member Functions inherited from Scope
Scope (uint8 id, const string &nm, Architecture *g, Scope *own)
Construct an empty scope, given a name and Architecture.
virtual ~Scope (void)
Destructor.
virtual bool inScope (const Address &addr, int4 size, const Address &usepoint) const
Query if the given range is owned by this Scope.
virtual SymbolEntry * addSymbol (const string &name, Datatype *ct, const Address &addr, const Address &usepoint)
Add a new Symbol to this Scope, given a name, data-type, and a single mapping.
const string & getName (void) const
Get the name of the Scope.
uint8 getId (void) const
Get the globally unique id.
bool isGlobal (void) const
Return true if this scope is global.
void queryByName (const string &name, vector< Symbol * > &res) const
Look-up symbols by name.
Funcdata * queryFunction (const string &name) const
Look-up a function by name.
SymbolEntry * queryByAddr (const Address &addr, const Address &usepoint) const
Get Symbol with matching address.
SymbolEntry * queryContainer (const Address &addr, int4 size, const Address &usepoint) const
Find the smallest containing Symbol.
SymbolEntry * queryProperties (const Address &addr, int4 size, const Address &usepoint, uint4 &flags) const
Find a Symbol or properties at the given address.
Funcdata * queryFunction (const Address &addr) const
Look-up a function by address.
Funcdata * queryExternalRefFunction (const Address &addr) const
Look-up a function thru an external reference.
LabSymbol * queryCodeLabel (const Address &addr) const
Look-up a code label by address.
Scope * resolveScope (const string &name, bool strategy) const
Find a child Scope of this.
Scope * discoverScope (const Address &addr, int4 sz, const Address &usepoint)
Find the owning Scope of a given memory range.
ScopeMap::const_iterator childrenBegin () const
Beginning iterator of child scopes.
ScopeMap::const_iterator childrenEnd () const
Ending iterator of child scopes.
void saveXmlRecursive (ostream &s, bool onlyGlobal) const
Save all contained scopes as an XML stream.
void overrideSizeLockType (Symbol *sym, Datatype *ct)
Change the data-type of a Symbol that is sizelocked.
void resetSizeLockType (Symbol *sym)
Clear a Symbol's size-locked data-type.
void setThisPointer (Symbol *sym, bool val)
Toggle the given Symbol as the "this" pointer.
bool isSubScope (const Scope *scp) const
Is this a sub-scope of the given Scope.
string getFullName (void) const
Get the full name of this Scope.
void getScopePath (vector< const Scope * > &vec) const
Get the ordered list of scopes up to this.
const Scope * findDistinguishingScope (const Scope *op2) const
Find first ancestor of this not shared by given scope.
Architecture * getArch (void) const
Get the Architecture associated with this.
Scope * getParent (void) const
Get the parent Scope (or NULL if this is the global Scope)
Symbol * addSymbol (const string &name, Datatype *ct)
Add a new Symbol without mapping it to an address.
SymbolEntry * addMapPoint (Symbol *sym, const Address &addr, const Address &usepoint)
Map a Symbol to a specific address.
Symbol * addMapSym (const Element *el)
Add a mapped Symbol from a <mapsym> XML tag.
FunctionSymbol * addFunction (const Address &addr, const string &nm)
Create a function Symbol at the given address in this Scope.
ExternRefSymbol * addExternalRef (const Address &addr, const Address &refaddr, const string &nm)
LabSymbol * addCodeLabel (const Address &addr, const string &nm)
Create a code label at the given address in this Scope.
Symbol * addDynamicSymbol (const string &nm, Datatype *ct, const Address &caddr, uint8 hash)
Create a dynamically mapped Symbol attached to a specific data-flow.
string buildDefaultName (Symbol *sym, int4 &base, Varnode *vn) const
Create a default name for the given Symbol.
bool isReadOnly (const Address &addr, int4 size, const Address &usepoint) const
Is the given memory range marked as read-only.
void printBounds (ostream &s) const
Print a description of this Scope's owned memory ranges.
Protected Member Functions
virtual Scope * buildSubScope (uint8 id, const string &nm)
Build an unattached Scope to be associated as a sub-scope of this.
virtual void addSymbolInternal (Symbol *sym)
Put a Symbol into the name map.
virtual SymbolEntry * addMapInternal (Symbol *sym, uint4 exfl, const Address &addr, int4 off, int4 sz, const RangeList &uselim)
Create a new SymbolEntry for a Symbol given a memory range.
virtual SymbolEntry * addDynamicMapInternal (Symbol *sym, uint4 exfl, uint8 hash, int4 off, int4 sz, const RangeList &uselim)
Create a new SymbolEntry for a Symbol given a dynamic hash.
Protected Member Functions inherited from Scope
const RangeList & getRangeTree (void) const
Access the address ranges owned by this Scope.
virtual void restrictScope (Funcdata *f)
Convert this to a local Scope.
virtual void addRange (AddrSpace *spc, uintb first, uintb last)
Add a memory range to the ownership of this Scope.
virtual void removeRange (AddrSpace *spc, uintb first, uintb last)
Remove a memory range from the ownership of this Scope.
SymbolEntry * addMap (SymbolEntry &entry)
Integrate a SymbolEntry into the range maps.
void setSymbolId (Symbol *sym, uint8 id) const
Adjust the id associated with a symbol.
Protected Attributes
SymbolNameTree nametree
The set of Symbol objects, sorted by name.
vector< EntryMap * > maptable
Rangemaps of SymbolEntry, one map for each address space.
vector< vector< Symbol * > > category
References to Symbol objects organized by category.
list< SymbolEntry > dynamicentry
Dynamic symbol entries.
SymbolNameTree multiEntrySet
Set of symbols with multiple entries.
uint8 nextUniqueId
Next available symbol id.
Protected Attributes inherited from Scope
Architecture * glb
Architecture of this scope.
string name
Name of this scope.
Funcdata * fd
(If non-null) the function which this is the local Scope for
uint8 uniqueId
Unique id for the scope, for deduping scope names, assigning symbol ids.
Private Member Functions
void processHole (const Element *el)
Parse a <hole> XML tag that describes boolean properties of memory range.
void processCollision (const Element *el)
Parse a <collision> tag indicating a named symbol with no storage or data-type info.
void insertNameTree (Symbol *sym)
Insert a Symbol into the nametree.
SymbolNameTree::const_iterator findFirstByName (const string &name) const
Find an iterator pointing to the first Symbol in the ordering with a given name.
Additional Inherited Members
Static Protected Member Functions inherited from Scope
static const Scope * stackAddr (const Scope *scope1, const Scope *scope2, const Address &addr, const Address &usepoint, SymbolEntry **addrmatch)
Query for Symbols starting at a given address, which match a given usepoint.
static const Scope * stackContainer (const Scope *scope1, const Scope *scope2, const Address &addr, int4 size, const Address &usepoint, SymbolEntry **addrmatch)
static const Scope * stackClosestFit (const Scope *scope1, const Scope *scope2, const Address &addr, int4 size, const Address &usepoint, SymbolEntry **addrmatch)
static const Scope * stackFunction (const Scope *scope1, const Scope *scope2, const Address &addr, Funcdata **addrmatch)
static const Scope * stackExternalRef (const Scope *scope1, const Scope *scope2, const Address &addr, ExternRefSymbol **addrmatch)
static const Scope * stackCodeLabel (const Scope *scope1, const Scope *scope2, const Address &addr, LabSymbol **addrmatch)
Detailed Description
An in-memory implementation of the Scope interface.
This can act as a stand-alone Scope object or serve as an in-memory cache for another implementation. This implements a nametree, which is a a set of Symbol objects (the set owns the Symbol objects). It also implements a maptable, which is a list of rangemaps that own the SymbolEntry objects.
Constructor & Destructor Documentation
ScopeInternal::ScopeInternal (uint8 id, const string & nm, Architecture * g)
Construct the Scope.
Parameters
id is the globally unique id associated with the scope
nm is the name of the Scope
g is the Architecture it belongs to
References maptable, nextUniqueId, and AddrSpaceManager::numSpaces().
Member Function Documentation
SymbolEntry * ScopeInternal::addDynamicMapInternal (Symbol * sym, uint4 exfl, uint8 hash, int4 off, int4 sz, const RangeList & uselim) protected virtual
Create a new SymbolEntry for a Symbol given a dynamic hash.
The SymbolEntry is specified in terms of a hash and usepoint, which describe how to find the temporary Varnode holding the symbol value.
Parameters
sym is the given Symbol being mapped
exfl are any boolean Varnode properties
hash is the given dynamic hash
off is the byte offset of the new SymbolEntry (relative to the whole Symbol)
sz is the number of bytes occupied by the Varnode
uselim is the given usepoint
Returns
the newly created SymbolEntry
Implements Scope.
References Datatype::getSize(), Symbol::mapentry, Symbol::type, and Symbol::wholeCount.
SymbolEntry * ScopeInternal::addMapInternal (Symbol * sym, uint4 exfl, const Address & addr, int4 off, int4 sz, const RangeList & uselim) protected virtual
Create a new SymbolEntry for a Symbol given a memory range.
The SymbolEntry is specified in terms of a memory range and usepoint
Parameters
sym is the given Symbol being mapped
exfl are any boolean Varnode properties specific to the memory range
addr is the starting address of the given memory range
off is the byte offset of the new SymbolEntry (relative to the whole Symbol)
sz is the number of bytes in the range
uselim is the given usepoint (which may be invalid)
Returns
the newly created SymbolEntry
Implements Scope.
Reimplemented in ScopeGhidraNamespace.
References AddrSpace::getIndex(), Symbol::getName(), Address::getOffset(), Datatype::getSize(), Address::getSpace(), rangemap< _recordtype >::insert(), Symbol::mapentry, Symbol::type, and Symbol::wholeCount.
Referenced by ScopeGhidraNamespace::addMapInternal().
void ScopeInternal::addSymbolInternal (Symbol * sym) protected virtual
Put a Symbol into the name map.
Parameters
sym is the preconstructed Symbol
Implements Scope.
References Symbol::category, Symbol::catindex, Symbol::getName(), Datatype::getSize(), Symbol::getType(), Symbol::ID_BASE, Symbol::name, and Symbol::symbolId.
void ScopeInternal::adjustCaches (void) virtual
Let scopes internally adjust any caches.
This is called once after Architecture configuration is complete.
Implements Scope.
References Scope::glb, maptable, and AddrSpaceManager::numSpaces().
Referenced by ScopeGhidra::adjustCaches().
void ScopeInternal::assignDefaultNames (int4 & base)
Assign a default name (via buildVariableName) to any unnamed symbol.
Run through all the symbols whose name is undefined. Build a variable name, uniquify it, and rename the variable.
Parameters
base is the base index to start at for generating generic names
References Scope::buildDefaultName(), Symbol::isNameUndefined(), nametree, and renameSymbol().
Referenced by ActionNameVars::apply().
string ScopeInternal::buildUndefinedName (void) const virtual
Build a formal undefined name, used internally when a Symbol is not given a name.
Returns
a special internal name that won't collide with other names in this Scope
Implements Scope.
References nametree.
Referenced by ScopeGhidra::buildUndefinedName(), clearUnlocked(), and clearUnlockedCategory().
string ScopeInternal::buildVariableName (const Address & addr, const Address & pc, Datatype * ct, int4 & index, uint4 flags) const virtual
Given an address and data-type, build a suitable generic symbol name.
Parameters
addr is the given address
pc is the address at which the name is getting used
ct is a data-type used to inform the name
index is a reference to an index used to make the name unique, which will be updated
flags are boolean properties of the variable we need the name for
Returns
the new variable name
Implements Scope.
Reimplemented in ScopeLocal.
References Varnode::addrtied, AddrSpace::byteToAddress(), findFirstByName(), Address::getAddrSize(), AddrSpace::getName(), Address::getOffset(), Translate::getRegisterName(), Datatype::getSize(), Address::getSpace(), AddrSpace::getWordSize(), Scope::glb, Varnode::indirect_creation, Varnode::input, makeNameUnique(), nametree, Varnode::persist, Datatype::printNameBase(), Varnode::return_address, Architecture::translate, and Varnode::unaffected.
Referenced by ScopeGhidra::buildVariableName(), and ScopeLocal::buildVariableName().
void ScopeInternal::categorySanity (void) virtual
Make sure Symbol categories are sane.
Look for NULL entries in the category tables. If there are, clear out the entire category, marking all symbols as uncategorized
References category, and setCategory().
Referenced by restoreXml().
SymbolEntry * ScopeInternal::findAddr (const Address & addr, const Address & usepoint) const virtual
Find a Symbol at a given address and usepoint.
Parameters
addr is the given address
usepoint is the point at which the Symbol is accessed (may be invalid)
Returns
the matching SymbolEntry or NULL
Implements Scope.
References rangemap< _recordtype >::find(), SymbolEntry::getAddr(), AddrSpace::getIndex(), Address::getOffset(), Address::getSpace(), SymbolEntry::inUse(), Address::isInvalid(), and maptable.
Referenced by ScopeGhidra::findAddr(), and ScopeGhidra::findCodeLabel().
void ScopeInternal::findByName (const string & name, vector< Symbol * > & res) const virtual
Find a Symbol by name within this Scope.
If there are multiple Symbols with the same name, all are passed back.
Parameters
name is the name to search for
res will contain any matching Symbols
Implements Scope.
References findFirstByName(), Symbol::name, and nametree.
SymbolEntry * ScopeInternal::findClosestFit (const Address & addr, int4 size, const Address & usepoint) const virtual
Find Symbol which is the closest fit to the given memory range.
Parameters
addr is the starting address of the given memory range
size is the number of bytes in the range
usepoint is the point at which the Symbol is accessed (may be invalid)
Returns
the matching SymbolEntry or NULL
Implements Scope.
References rangemap< _recordtype >::find(), AddrSpace::getIndex(), SymbolEntry::getLast(), Address::getOffset(), SymbolEntry::getSize(), Address::getSpace(), SymbolEntry::inUse(), Address::isInvalid(), and maptable.
Referenced by ScopeGhidra::findContainer().
LabSymbol * ScopeInternal::findCodeLabel (const Address & addr) const virtual
Find a label Symbol at the given address.
Parameters
addr is the given address
Returns
the matching LabSymbol or NULL
Implements Scope.
References rangemap< _recordtype >::find(), SymbolEntry::getAddr(), AddrSpace::getIndex(), Address::getOffset(), Address::getSpace(), SymbolEntry::getSymbol(), SymbolEntry::inUse(), and maptable.
Referenced by ScopeGhidra::findCodeLabel().
SymbolEntry * ScopeInternal::findContainer (const Address & addr, int4 size, const Address & usepoint) const virtual
Find the smallest Symbol containing the given memory range.
Parameters
addr is the starting address of the given memory range
size is the number of bytes in the range
usepoint is the point at which the Symbol is accessed (may be invalid)
Returns
the matching SymbolEntry or NULL
Implements Scope.
References end(), rangemap< _recordtype >::find(), AddrSpace::getIndex(), SymbolEntry::getLast(), Address::getOffset(), SymbolEntry::getSize(), Address::getSpace(), SymbolEntry::inUse(), Address::isInvalid(), and maptable.
Referenced by ScopeGhidra::findAddr(), ScopeGhidra::findExternalRef(), and ScopeGhidra::findFunction().
ExternRefSymbol * ScopeInternal::findExternalRef (const Address & addr) const virtual
Find an external reference at the given address.
Parameters
addr is the given address
Returns
the matching ExternRefSymbol or NULL
Implements Scope.
References rangemap< _recordtype >::find(), SymbolEntry::getAddr(), AddrSpace::getIndex(), Address::getOffset(), Address::getSpace(), SymbolEntry::getSymbol(), and maptable.
Referenced by ScopeGhidra::findExternalRef().
SymbolNameTree::const_iterator ScopeInternal::findFirstByName (const string & name) const private
Find an iterator pointing to the first Symbol in the ordering with a given name.
Parameters
name is the name to search for
Returns
iterator pointing to the first Symbol or nametree.end() if there is no matching Symbol
References Scope::name, and nametree.
Referenced by buildVariableName(), findByName(), makeNameUnique(), and processCollision().
Funcdata * ScopeInternal::findFunction (const Address & addr) const virtual
Find the function starting at the given address.
Parameters
addr is the given starting address
Returns
the matching Funcdata object or NULL
Implements Scope.
References rangemap< _recordtype >::find(), SymbolEntry::getAddr(), FunctionSymbol::getFunction(), AddrSpace::getIndex(), Address::getOffset(), Address::getSpace(), SymbolEntry::getSymbol(), and maptable.
Referenced by ScopeGhidra::findFunction(), and ScopeGhidra::resolveExternalRefFunction().
SymbolEntry * ScopeInternal::findOverlap (const Address & addr, int4 size) const virtual
Find first Symbol overlapping the given memory range.
Parameters
addr is the starting address of the given range
size is the number of bytes in the range
Returns
an overlapping SymbolEntry or NULL if none exists
Implements Scope.
References rangemap< _recordtype >::end(), rangemap< _recordtype >::find_overlap(), AddrSpace::getIndex(), Address::getOffset(), Address::getSpace(), and maptable.
Referenced by ScopeLocal::adjustFit(), ScopeLocal::markNotMapped(), and Funcdata::syncVarnodesWithSymbols().
int4 ScopeInternal::getCategorySize (int4 cat) const virtual
Get the number of Symbols in the given category.
Parameters
cat is the Symbol category
Returns
the number in that category
Implements Scope.
References category.
Symbol * ScopeInternal::getCategorySymbol (int4 cat, int4 ind) const virtual
Retrieve a Symbol by index within a specific category.
Parameters
cat is the Symbol category
ind is the index (within the category) of the Symbol
Returns
the indicated Symbol or NULL if no Symbol with that index exists
Implements Scope.
References category.
void ScopeInternal::insertNameTree (Symbol * sym) private
Insert a Symbol into the nametree.
Duplicate symbol names are allowed for by establishing a deduplication id for the Symbol.
Parameters
sym is the Symbol to insert
References Symbol::name, Symbol::nameDedup, and nametree.
Referenced by renameSymbol().
bool ScopeInternal::isNameUsed (const string & nm, const Scope * op2) const virtual
Check if the given name is occurs within the given scope path.
Test for the presence of a symbol with the given name in either this scope or an ancestor scope up to but not including the given terminating scope. If the name is used true is returned.
Parameters
nm is the given name to test
op2 is the terminating ancestor scope (or null)
Implements Scope.
Reimplemented in ScopeGhidraNamespace.
References Scope::getParent(), Scope::isNameUsed(), and nametree.
string ScopeInternal::makeNameUnique (const string & nm) const virtual
Produce a version of the given symbol name that won't collide with other names in this Scope.
Parameters
nm is the given name
Returns
return a unique version of the name
Implements Scope.
References findFirstByName(), Symbol::getName(), Symbol::nameDedup, and nametree.
Referenced by ScopeLocal::buildVariableName(), buildVariableName(), ActionNameVars::lookForBadJumpTables(), and ActionNameVars::lookForFuncParamNames().
void ScopeInternal::processCollision (const Element * el) private
Parse a <collision> tag indicating a named symbol with no storage or data-type info.
Let the decompiler know that a name is occupied within the scope for isNameUsed queries, without specifying storage and data-type information about the symbol. This is modeled currently by creating an unmapped symbol.
Parameters
el is the <collision> element
References Scope::addSymbol(), findFirstByName(), Element::getAttributeValue(), TypeFactory::getBase(), Scope::glb, nametree, TYPE_INT, and Architecture::types.
Referenced by restoreXml().
void ScopeInternal::processHole (const Element * el) private
Parse a <hole> XML tag that describes boolean properties of memory range.
The <scope> XML tag is allowed to contain <hole> tags, which are really descriptions of memory globally. This method parses them and passes the info to the Database object.
Parameters
el is the <hole> element
References Element::getAttributeName(), Element::getAttributeValue(), Element::getNumAttributes(), Scope::glb, Varnode::readonly, Range::restoreXml(), Database::setPropertyRange(), Architecture::symboltab, Varnode::volatil, and xml_readbool().
Referenced by restoreXml().
Funcdata * ScopeInternal::resolveExternalRefFunction (ExternRefSymbol * sym) const virtual
Convert an external reference to the referenced function.
Parameters
sym is the Symbol marking the external reference
Returns
the underlying Funcdata object or NULL if none exists
Implements Scope.
References ExternRefSymbol::getRefAddr(), and Scope::queryFunction().
void ScopeInternal::retypeSymbol (Symbol * sym, Datatype * ct) virtual
Change the data-type of a Symbol within this Scope.
If the size of the Symbol changes, any mapping (SymbolEntry) is adjusted
Parameters
sym is the given Symbol
ct is the new data-type
Implements Scope.
References Scope::addMapPoint(), Symbol::checkSizeTypeLock(), Datatype::getSize(), Symbol::mapentry, maptable, Symbol::name, Symbol::type, and Symbol::wholeCount.
Referenced by Funcdata::attemptDynamicMappingLate().
void ScopeInternal::setCategory (Symbol * sym, int4 cat, int4 ind) virtual
Set the category and index for the given Symbol.
Parameters
sym is the given Symbol
cat is the category to set for the Symbol
ind is the index position to set (within the category)
Implements Scope.
References Symbol::category, category, and Symbol::catindex.
Referenced by categorySanity().
The documentation for this class was generated from the following files:
database.hh
database.cc