decompiler: VolatileWriteOp Class Reference
VolatileWriteOp Class Reference
An operation that writes to volatile memory.
#include <userop.hh>
Public Member Functions
VolatileWriteOp (Architecture *g, const string &nm, int4 ind)
Constructor.
virtual string getOperatorName (const PcodeOp *op) const
Get the symbol representing this operation in decompiled code.
virtual void restoreXml (const Element *el)
Restore the detailed description from an XML stream.
Public Member Functions inherited from VolatileOp
VolatileOp (Architecture *g, const string &nm, int4 ind)
Constructor.
Public Member Functions inherited from UserPcodeOp
UserPcodeOp (Architecture *g, const string &nm, int4 ind)
Construct from name and index.
const string & getName (void) const
Get the low-level name of the p-code op.
int4 getIndex (void) const
Get the constant id of the op.
virtual ~UserPcodeOp (void)
Destructor.
Additional Inherited Members
Static Protected Member Functions inherited from VolatileOp
static string appendSize (const string &base, int4 size)
Append a suffix to a string encoding a specific size.
Protected Attributes inherited from UserPcodeOp
string name
Low-level name of p-code operator.
int4 useropindex
Index passed in the CALLOTHER op.
Architecture * glb
Architecture owning the user defined op.
Detailed Description
An operation that writes to volatile memory.
This CALLOTHER p-code operation takes as its input parameters:
Constant id
Reference Varnode to the memory being written
The Varnode value being written to the memory
Member Function Documentation
string VolatileWriteOp::getOperatorName (const PcodeOp * op) const virtual
Get the symbol representing this operation in decompiled code.
This will return the symbol formally displayed in source code, which can be tailored more than the low-level name
Parameters
op is the operation (in context) where a symbol is needed
Returns
the symbol as a string
Reimplemented from UserPcodeOp.
References PcodeOp::getIn(), Varnode::getSize(), UserPcodeOp::name, and PcodeOp::numInput().
void VolatileWriteOp::restoreXml (const Element * el) virtual
Restore the detailed description from an XML stream.
The details of how a user defined operation behaves can be dynamically configured from an XML tag.
Parameters
el is the root XML element describing the op
Implements UserPcodeOp.
References Element::getAttributeValue(), and UserPcodeOp::name.
Referenced by UserOpManage::parseVolatile().
The documentation for this class was generated from the following files:
userop.hh
userop.cc