decompiler: TypeSpacebase Class Reference
TypeSpacebase Class Reference
Special Datatype object used to describe pointers that index into the symbol table.
#include <type.hh>
Public Member Functions
TypeSpacebase (const TypeSpacebase &op)
Construct from another TypeSpacebase.
TypeSpacebase (AddrSpace *id, const Address &frame, Architecture *g)
Construct given an address space, scope, and architecture.
Scope * getMap (void) const
Get the symbol table indexed by this.
Address getAddress (uintb off, int4 sz, const Address &point) const
Construct an Address given an offset.
virtual Datatype * getSubType (uintb off, uintb *newoff) const
Recover component data-type one-level down.
virtual Datatype * nearestArrayedComponentForward (uintb off, uintb *newoff, int4 *elSize) const
virtual Datatype * nearestArrayedComponentBackward (uintb off, uintb *newoff, int4 *elSize) const
virtual int4 compare (const Datatype &op, int4 level) const
Compare for functional equivalence.
virtual int4 compareDependency (const Datatype &op) const
Compare for storage in tree structure.
virtual Datatype * clone (void) const
Clone the data-type.
virtual void saveXml (ostream &s) const
Serialize the data-type to XML.
Public Member Functions inherited from Datatype
Datatype (const Datatype &op)
Construct the base data-type copying low-level properties of another.
Datatype (int4 s, type_metatype m)
Construct the base data-type providing size and meta-type.
Datatype (int4 s, type_metatype m, const string &n)
Construct the base data-type providing size, meta-type, and name.
virtual ~Datatype (void)
Destructor.
bool isCoreType (void) const
Is this a core data-type.
bool isCharPrint (void) const
Does this print as a 'char'.
bool isEnumType (void) const
Is this an enumerated type.
bool isPowerOfTwo (void) const
Is this a flag-based enumeration.
bool isASCII (void) const
Does this print as an ASCII 'char'.
bool isUTF16 (void) const
Does this print as UTF16 'wchar'.
bool isUTF32 (void) const
Does this print as UTF32 'wchar'.
bool isVariableLength (void) const
Is this a variable length structure.
bool hasSameVariableBase (const Datatype *ct) const
Are these the same variable length data-type.
bool isOpaqueString (void) const
Is this an opaquely encoded string.
uint4 getInheritable (void) const
Get properties pointers inherit.
type_metatype getMetatype (void) const
Get the type meta-type.
uint8 getId (void) const
Get the type id.
int4 getSize (void) const
Get the type size.
const string & getName (void) const
Get the type name.
virtual void printRaw (ostream &s) const
Print a description of the type to stream.
virtual int4 numDepend (void) const
Return number of component sub-types.
virtual Datatype * getDepend (int4 index) const
Return the i-th component sub-type.
virtual void printNameBase (ostream &s) const
Print name as short prefix.
int4 typeOrder (const Datatype &op) const
Order this with -op- datatype.
int4 typeOrderBool (const Datatype &op) const
Order this with -op-, treating bool data-type as special.
void saveXmlBasic (ostream &s) const
Save basic data-type properties.
void saveXmlRef (ostream &s) const
Write an XML reference of this to stream.
bool isPtrsubMatching (uintb offset) const
Is this data-type suitable as input to a CPUI_PTRSUB op.
Private Member Functions
virtual void restoreXml (const Element *el, TypeFactory &typegrp)
Restore data-type from XML.
Private Attributes
AddrSpace * spaceid
The address space we are treating as a structure.
Address localframe
Address of function whose symbol table is indexed (or INVALID for "global")
Architecture * glb
Architecture for accessing symbol table.
Friends
class TypeFactory
Additional Inherited Members
Protected Types inherited from Datatype
enum {
coretype = 1, chartype = 2, enumtype = 4, poweroftwo = 8,
utf16 = 16, utf32 = 32, opaque_string = 64, variable_length = 128
}
Boolean properties of datatypes.
Protected Member Functions inherited from Datatype
void restoreXmlBasic (const Element *el)
Recover basic data-type properties.
Static Protected Member Functions inherited from Datatype
static uint8 hashName (const string &nm)
Produce a data-type id by hashing the type name.
static uint8 hashSize (uint8 id, int4 size)
Reversibly hash size into id.
Protected Attributes inherited from Datatype
int4 size
Size (of variable holding a value of this type)
string name
Name of type.
type_metatype metatype
Meta-type - type disregarding size.
uint4 flags
Boolean properties of the type.
uint8 id
A unique id for the type (or 0 if an id is not assigned)
Detailed Description
Special Datatype object used to describe pointers that index into the symbol table.
A TypeSpacebase treats a specific AddrSpace as "structure" that will get indexed in to. This facilitates type propagation from local symbols into the stack space and from global symbols into the RAM space.
Member Function Documentation
int4 TypeSpacebase::compare (const Datatype & op, int4 level) const virtual
Compare for functional equivalence.
0 (equality) means the data-types are functionally equivalent (even if names differ) Smaller types come earlier. More specific types come earlier.
Parameters
op is the data-type to compare with this
level is maximum level to descend when recursively comparing
Returns
negative, 0, positive depending on ordering of types
Reimplemented from Datatype.
References Datatype::compareDependency().
int4 TypeSpacebase::compareDependency (const Datatype & op) const virtual
Compare for storage in tree structure.
Ordering of data-types for the main TypeFactory container. Comparison only goes down one-level in the component structure, before just comparing pointers.
Parameters
op is the data-type to compare with this
Returns
negative, 0, positive depending on ordering of types
Reimplemented from Datatype.
References Datatype::getMetatype(), Datatype::getSize(), localframe, Datatype::metatype, Datatype::size, and spaceid.
Address TypeSpacebase::getAddress (uintb off, int4 sz, const Address & point) const
Construct an Address given an offset.
Return the Address being referred to by a specific offset relative to a pointer with this Datatype
Parameters
off is the offset relative to the pointer
sz is the size of offset (as a pointer)
point is a "context" reference for the request
Returns
the referred to Address
Referenced by RulePtrsubCharConstant::applyOp(), Funcdata::linkSymbolReference(), PrintC::opPtrsub(), and ActionInferTypes::propagateSpacebaseRef().
Scope * TypeSpacebase::getMap (void) const
Get the symbol table indexed by this.
This data-type can index either a local or the global scope
Returns
the symbol table Scope
Referenced by RulePtrsubCharConstant::applyOp(), and Funcdata::linkSymbolReference().
Datatype * TypeSpacebase::getSubType (uintb off, uintb * newoff) const virtual
Recover component data-type one-level down.
Given an offset into this data-type, return the component data-type at that offset. Also, pass back a "renormalized" offset suitable for recursize getSubType() calls: i.e. if the original offset hits the exact start of the sub-type, 0 is passed back. If there is no valid component data-type at the offset, return NULL and pass back the original offset
Parameters
off is the offset into this data-type
newoff is a pointer to the passed-back offset
Returns
a pointer to the component data-type or NULL
Reimplemented from Datatype.
Datatype * TypeSpacebase::nearestArrayedComponentBackward (uintb off, uintb * newoff, int4 * elSize) const virtual
Find the first component data-type before the given offset that is (or contains) an array, and pass back the difference between the component's start and the given offset. Return the component data-type or null if no array is found.
Parameters
off is the given offset into this data-type
newoff is used to pass back the offset difference
elSize is used to pass back the array element size
Returns
the component data-type or null
Reimplemented from Datatype.
References Datatype::getMetatype(), Datatype::getSubType(), Datatype::nearestArrayedComponentBackward(), TYPE_ARRAY, and TYPE_STRUCT.
Datatype * TypeSpacebase::nearestArrayedComponentForward (uintb off, uintb * newoff, int4 * elSize) const virtual
Find the first component data-type after the given offset that is (or contains) an array, and pass back the difference between the component's start and the given offset. Return the component data-type or null if no array is found.
Parameters
off is the given offset into this data-type
newoff is used to pass back the offset difference
elSize is used to pass back the array element size
Returns
the component data-type or null
Reimplemented from Datatype.
References Datatype::nearestArrayedComponentForward(), and TYPE_STRUCT.
void TypeSpacebase::restoreXml (const Element * el, TypeFactory & typegrp) private virtual
Restore data-type from XML.
Restore a Datatype object from an XML element
Parameters
el is the XML element
typegrp is the underlying TypeFactory that will hold the new object
Reimplemented from Datatype.
Referenced by TypeFactory::restoreXmlTypeNoRef().
void TypeSpacebase::saveXml (ostream & s) const virtual
Serialize the data-type to XML.
Write out a formal description of the data-type as an XML <type> tag. For composite data-types, the description goes down one level, describing the component types only by reference.
Parameters
s is the stream to write to
Reimplemented from Datatype.
References a_v(), and Datatype::saveXmlBasic().
The documentation for this class was generated from the following files:
type.hh
type.cc