decompiler: Rule Class Reference
Rule Class Reference abstract
Class for performing a single transformation on a PcodeOp or Varnode.
#include <action.hh>
Public Types
enum typeflags { type_disable = 1, rule_debug = 2, warnings_on = 4, warnings_given = 8 }
Properties associated with a Rule.
Public Member Functions
Rule (const string &g, uint4 fl, const string &nm)
Construct given group, properties name.
virtual ~Rule (void)
Destructor.
const string & getName (void) const
Return the name of this Rule.
const string & getGroup (void) const
Return the group this Rule belongs to.
uint4 getNumTests (void)
Get number of attempted applications.
uint4 getNumApply (void)
Get number of successful applications.
void setBreak (uint4 tp)
Set a breakpoint on this Rule.
void clearBreak (uint4 tp)
Clear a breakpoint on this Rule.
void clearBreakPoints (void)
Clear all breakpoints on this Rule.
void turnOnWarnings (void)
Enable warnings for this Rule.
void turnOffWarnings (void)
Disable warnings for this Rule.
bool isDisabled (void) const
Return true if this Rule is disabled.
void setDisable (void)
Disable this Rule (within its pool)
void clearDisable (void)
Enable this Rule (within its pool)
bool checkActionBreak (void)
Check if an action breakpoint is turned on.
uint4 getBreakPoint (void) const
Return breakpoint toggles.
virtual Rule * clone (const ActionGroupList &grouplist) const =0
Clone the Rule.
virtual void getOpList (vector< uint4 > &oplist) const
List of op codes this rule operates on.
virtual int4 applyOp (PcodeOp *op, Funcdata &data)
Attempt to apply this Rule.
virtual void reset (Funcdata &data)
Reset this Rule.
virtual void resetStats (void)
Reset Rule statistics.
virtual void printStatistics (ostream &s) const
Print statistics for this Rule.
Private Member Functions
void issueWarning (Architecture *glb)
If enabled, print a warning that this Rule has been applied.
Private Attributes
uint4 flags
Properties enabled with this Rule.
uint4 breakpoint
Breakpoint(s) enabled for this Rule.
string name
Name of the Rule.
string basegroup
Group to which this Rule belongs.
uint4 count_tests
Number of times this Rule has attempted to apply.
uint4 count_apply
Number of times this Rule has successfully been applied.
Friends
class ActionPool
Detailed Description
Class for performing a single transformation on a PcodeOp or Varnode.
A Rule, through its applyOp() method, is handed a specific PcodeOp as a potential point to apply. It determines if it can apply at that point, then makes any changes. Rules inform the system of what types of PcodeOps they can possibly apply to through the getOpList() method. A set of Rules are pooled together into a single Action via the ActionPool, which efficiently applies each Rule across a whole function. A Rule supports the same breakpoint properties as an Action. A Rule is allowed to keep state that is specific to a given function (Funcdata). The reset() method is invoked to purge this state for each new function to be transformed.
Member Enumeration Documentation
enum Rule::typeflags
Properties associated with a Rule.
Enumerator
type_disable
Is this rule disabled.
rule_debug
Print debug info specific for this rule.
warnings_on
A warning is issued if this rule is applied.
warnings_given
Set if a warning for this rule has been given before.
Constructor & Destructor Documentation
Rule::Rule (const string & g, uint4 fl, const string & nm)
Construct given group, properties name.
Parameters
g is the groupname to which this Rule belongs
fl is the set of properties
nm is the name of the Rule
References Action::basegroup, Action::breakpoint, Action::count_apply, Action::count_tests, Action::flags, and Action::name.
Member Function Documentation
virtual int4 Rule::applyOp (PcodeOp * op, Funcdata & data) inline virtual
Attempt to apply this Rule.
This method contains the main logic for applying the Rule. It must use a given PcodeOp as the point at which the Rule applies. If it does apply, changes are made directly to the function and 1 (non-zero) is returned, otherwise 0 is returned.
Parameters
op is the given PcodeOp where the Rule may apply
data is the function to which to apply
Reimplemented in RuleXorSwap, RulePiecePathology, RulePopcountBoolXor, RuleThreeWayCompare, RuleFuncPtrEncoding, RuleIgnoreNan, RuleFloatCast, RuleConditionalMove, RuleNegateNegate, RuleSubfloatConvert, RuleSubvarSext, RuleSubvarZext, RuleSubvarShift, RuleSubvarCompZero, RulePtrFlow, RuleSplitFlow, RuleSubvarSubpiece, RuleSubvarAnd, RuleSegment, RuleModOpt, RuleSignNearMult, RuleSignForm, RuleSignDiv2, RuleDivOpt, RuleDivTermAdd2, RuleDivTermAdd, RulePositiveDiv, RuleSubNormal, RulePtrsubCharConstant, RuleSubRight, Rule2Comp2Sub, RuleAddUnsigned, RuleMultNegOne, RulePtrsubUndo, RulePtraddUndo, RulePushPtr, RuleStructOffset0, RulePtrArith, RuleEqual2Constant, RuleEqual2Zero, RuleSLess2Zero, RuleLessEqual2Zero, RuleLess2Zero, RuleBoolNegate, RuleCondNegate, RuleSwitchSingle, RuleEmbed, RuleHumptyOr, RuleDumptyHump, RuleHumptyDumpty, RuleShiftSub, RuleSubCancel, RuleSubZext, RuleConcatLeftShift, RuleConcatZero, RuleShiftAnd, RuleZextShiftZext, RuleZextCommute, RuleConcatZext, RuleConcatCommute, RuleSubCommute, RuleSubExtComm, RuleStoreVarnode, RuleLoadVarnode, RuleAddMultCollapse, RuleXorCollapse, RuleSub2Add, RuleCarryElim, Rule2Comp2Mult, RulePropagateCopy, RuleTransformCpool, RuleCollapseConstants, RuleShiftPiece, RuleShift2Mult, RuleIdentityEl, RuleTestSign, RuleSignShift, RuleTrivialShift, RuleSborrow, RuleMultiCollapse, RuleIndirectCollapse, RuleLogic2Bool, RuleBoolZext, RuleBooleanNegate, RuleBitUndistribute, RuleZextSless, RuleSlessToLess, RuleZextEliminate, RuleTrivialBool, RuleTrivialArith, RuleLessNotEqual, RuleLessEqual, RuleShiftCompare, RuleLeftRight, RuleConcatShift, RuleDoubleArithShift, RuleDoubleShift, RuleDoubleSub, RuleAndCompare, RuleAndPiece, RuleAndCommute, RuleFloatRange, RuleRangeMeld, RuleLessOne, RuleAndDistribute, RuleDoubleLoad, RuleHighOrderAnd, RuleDoubleIn, RuleNotDistribute, RulePushMulti, RulePullsubIndirect, RulePullsubMulti, RuleTermOrder, RuleEquality, RuleOrPredicate, RuleIntLessEqual, RuleRightShiftAnd, RuleShiftBitops, RuleNegateIdentity, RuleAndOrLump, RuleOrCollapse, RuleOrConsume, RuleAndMask, RuleOrMask, RuleBxor2NotEqual, RulePiece2Sext, RulePiece2Zext, RuleSelectCse, RuleCollectTerms, and RuleEarlyRemoval.
References ActionPool::printStatistics(), ActionPool::reset(), and ActionPool::resetStats().
Referenced by ActionPool::processOp().
bool Rule::checkActionBreak (void)
Check if an action breakpoint is turned on.
This method is called every time the Rule successfully applies. If it returns true, this indicates to the system that an action breakpoint has occurred.
Returns
true if an action breakpoint should occur because of this Rule
References Action::break_action, and Action::breakpoint.
Referenced by ActionPool::processOp().
virtual Rule* Rule::clone (const ActionGroupList & grouplist) const pure virtual
Clone the Rule.
If this Rule is a member of one of the groups in the grouplist, this returns a clone of the Rule, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Rule or NULL
Implemented in RuleXorSwap, RulePiecePathology, RulePopcountBoolXor, RuleThreeWayCompare, RuleFuncPtrEncoding, RuleIgnoreNan, RuleFloatCast, RuleConditionalMove, RuleNegateNegate, RuleSubfloatConvert, RuleSubvarSext, RuleSubvarZext, RuleSubvarShift, RuleSubvarCompZero, RulePtrFlow, RuleSplitFlow, RuleSubvarSubpiece, RuleSubvarAnd, RuleSegment, RuleModOpt, RuleSignNearMult, RuleSignForm, RuleSignDiv2, RuleDivOpt, RuleDivTermAdd2, RuleDivTermAdd, RulePositiveDiv, RuleSubNormal, RulePtrsubCharConstant, RuleSubRight, Rule2Comp2Sub, RuleAddUnsigned, RuleMultNegOne, RulePtrsubUndo, RulePtraddUndo, RulePushPtr, RuleStructOffset0, RulePtrArith, RuleEqual2Constant, RuleEqual2Zero, RuleSLess2Zero, RuleLessEqual2Zero, RuleLess2Zero, RuleBoolNegate, RuleCondNegate, RuleSwitchSingle, RuleEmbed, RuleHumptyOr, RuleDumptyHump, RuleHumptyDumpty, RuleShiftSub, RuleSubCancel, RuleSubZext, RuleConcatLeftShift, RuleConcatZero, RuleShiftAnd, RuleZextShiftZext, RuleZextCommute, RuleConcatZext, RuleConcatCommute, RuleSubCommute, RuleSubExtComm, RuleStoreVarnode, RuleLoadVarnode, RuleAddMultCollapse, RuleXorCollapse, RuleSub2Add, RuleCarryElim, Rule2Comp2Mult, RulePropagateCopy, RuleTransformCpool, RuleCollapseConstants, RuleShiftPiece, RuleShift2Mult, RuleIdentityEl, RuleTestSign, RuleSignShift, RuleTrivialShift, RuleSborrow, RuleMultiCollapse, RuleIndirectCollapse, RuleLogic2Bool, RuleBoolZext, RuleBooleanNegate, RuleBitUndistribute, RuleZextSless, RuleSlessToLess, RuleZextEliminate, RuleTrivialBool, RuleTrivialArith, RuleLessNotEqual, RuleLessEqual, RuleShiftCompare, RuleLeftRight, RuleConcatShift, RuleDoubleArithShift, RuleDoubleShift, RuleDoubleSub, RuleAndCompare, RuleAndPiece, RuleAndCommute, RuleFloatRange, RuleRangeMeld, RuleLessOne, RuleAndDistribute, RuleDoubleLoad, RuleHighOrderAnd, RuleNotDistribute, RuleDoubleIn, RulePushMulti, RulePullsubIndirect, RulePullsubMulti, RuleTermOrder, RuleEquality, RuleOrPredicate, RuleIntLessEqual, RuleRightShiftAnd, RuleShiftBitops, RuleNegateIdentity, RuleAndOrLump, RuleOrCollapse, RuleOrConsume, RuleAndMask, RuleOrMask, RuleBxor2NotEqual, RulePiece2Sext, RulePiece2Zext, RuleSelectCse, RuleCollectTerms, and RuleEarlyRemoval.
Referenced by ActionPool::clone().
void Rule::getOpList (vector< uint4 > & oplist) const virtual
List of op codes this rule operates on.
Populate the given array with all possible OpCodes this Rule might apply to. By default, this method returns all possible OpCodes
Parameters
oplist is the array to populate
Reimplemented in RuleXorSwap, RulePiecePathology, RulePopcountBoolXor, RuleThreeWayCompare, RuleFuncPtrEncoding, RuleIgnoreNan, RuleFloatCast, RuleConditionalMove, RuleNegateNegate, RuleSubfloatConvert, RuleSubvarSext, RuleSubvarZext, RuleSubvarShift, RuleSubvarCompZero, RulePtrFlow, RuleSplitFlow, RuleSubvarSubpiece, RuleSubvarAnd, RuleSegment, RuleModOpt, RuleSignNearMult, RuleSignForm, RuleSignDiv2, RuleDivOpt, RuleDivTermAdd2, RuleDivTermAdd, RulePositiveDiv, RuleSubNormal, RulePtrsubCharConstant, RuleSubRight, Rule2Comp2Sub, RuleAddUnsigned, RuleMultNegOne, RulePtrsubUndo, RulePtraddUndo, RulePushPtr, RuleStructOffset0, RulePtrArith, RuleEqual2Constant, RuleEqual2Zero, RuleSLess2Zero, RuleLessEqual2Zero, RuleLess2Zero, RuleBoolNegate, RuleCondNegate, RuleSwitchSingle, RuleEmbed, RuleHumptyOr, RuleDumptyHump, RuleHumptyDumpty, RuleShiftSub, RuleSubCancel, RuleSubZext, RuleConcatLeftShift, RuleConcatZero, RuleShiftAnd, RuleZextShiftZext, RuleZextCommute, RuleConcatZext, RuleConcatCommute, RuleSubCommute, RuleSubExtComm, RuleStoreVarnode, RuleLoadVarnode, RuleAddMultCollapse, RuleXorCollapse, RuleSub2Add, RuleCarryElim, Rule2Comp2Mult, RuleTransformCpool, RuleShiftPiece, RuleShift2Mult, RuleIdentityEl, RuleTestSign, RuleSignShift, RuleTrivialShift, RuleSborrow, RuleMultiCollapse, RuleIndirectCollapse, RuleLogic2Bool, RuleBoolZext, RuleBooleanNegate, RuleBitUndistribute, RuleZextSless, RuleSlessToLess, RuleZextEliminate, RuleTrivialBool, RuleTrivialArith, RuleLessNotEqual, RuleLessEqual, RuleShiftCompare, RuleLeftRight, RuleConcatShift, RuleDoubleArithShift, RuleDoubleShift, RuleDoubleSub, RuleAndCompare, RuleAndPiece, RuleAndCommute, RuleFloatRange, RuleRangeMeld, RuleLessOne, RuleAndDistribute, RuleDoubleLoad, RuleHighOrderAnd, RuleDoubleIn, RuleNotDistribute, RulePushMulti, RulePullsubIndirect, RulePullsubMulti, RuleTermOrder, RuleEquality, RuleOrPredicate, RuleIntLessEqual, RuleRightShiftAnd, RuleShiftBitops, RuleNegateIdentity, RuleAndOrLump, RuleOrCollapse, RuleOrConsume, RuleAndMask, RuleOrMask, RuleBxor2NotEqual, RulePiece2Sext, RulePiece2Zext, RuleSelectCse, and RuleCollectTerms.
References CPUI_MAX.
Referenced by ActionPool::addRule().
void Rule::issueWarning (Architecture * glb) private
If enabled, print a warning that this Rule has been applied.
This method is called whenever this Rule applies. If warnings have been enabled for the Rule via turnOnWarnings(), this method will print a message indicating the Rule has been applied. Even with repeat calls, the message will only be printed once (until reset() is called)
Parameters
glb is the Architecture holding the console to print to
References Action::flags, Action::name, and Architecture::printMessage().
Referenced by ActionPool::processOp().
void Rule::printStatistics (ostream & s) const virtual
Print statistics for this Rule.
Print the accumulated counts associated with applying this Rule to stream. This method is intended for console mode debugging. Derived Rules may override this to display their own statistics.
Parameters
s is the output stream
References Action::count_apply, Action::count_tests, and Action::name.
void Rule::reset (Funcdata & data) virtual
Reset this Rule.
Any state that is specific to a particular function is cleared by this method. This method can be used to initialize a Rule based on a new function it will apply to
Parameters
data is the new function about to be transformed
Reimplemented in RuleSubvarSext, and RuleDoubleIn.
References Action::flags.
void Rule::resetStats (void) virtual
Reset Rule statistics.
Counts of when this Rule has been attempted/applied are reset to zero. Derived Rules may reset their own statistics.
References Action::count_apply, Action::count_tests, Action::flags, Action::name, and Action::rule_debug.
The documentation for this class was generated from the following files:
action.hh
action.cc