decompiler: Cover Class Reference
Cover Class Reference
A description of the topological scope of a single variable object.
#include <cover.hh>
Public Member Functions
void clear (void)
Clear this to an empty Cover.
int4 compareTo (const Cover &op2) const
Give ordering of this and another Cover.
const CoverBlock & getCoverBlock (int4 i) const
Get the CoverBlock corresponding to the i-th block.
int4 intersect (const Cover &op2) const
Characterize the intersection between this and another Cover.
int4 intersectByBlock (int4 blk, const Cover &op2) const
Characterize the intersection on a specific block.
void intersectList (vector< int4 > &listout, const Cover &op2, int4 level) const
Generate a list of blocks that intersect.
bool contain (const PcodeOp *op, int4 max) const
Does this contain the given PcodeOp.
int4 containVarnodeDef (const Varnode *vn) const
Check the definition of a Varnode for containment.
void merge (const Cover &op2)
Merge this with another Cover block by block.
void rebuild (const Varnode *vn)
Reset this based on def-use of a single Varnode.
void addDefPoint (const Varnode *vn)
Reset to the single point where the given Varnode is defined.
void addRefPoint (const PcodeOp *ref, const Varnode *vn)
Add a variable read to this Cover.
void print (ostream &s) const
Dump a description of this cover to stream.
map< int4, CoverBlock >::const_iterator begin (void) const
Get beginning of CoverBlocks.
map< int4, CoverBlock >::const_iterator end (void) const
Get end of CoverBlocks.
Private Member Functions
void addRefRecurse (const FlowBlock *bl)
Fill-in this recursively from the given block.
Private Attributes
map< int4, CoverBlock > cover
block index -> CoverBlock
Static Private Attributes
static const CoverBlock emptyBlock
Global empty CoverBlock for blocks not covered by this.
Detailed Description
A description of the topological scope of a single variable object.
The topological scope of a variable within a function is the set of locations within the code of the function where that variable holds a variable. For the decompiler, a high-level variable in this sense, HighVariable, is a collection of Varnode objects. In order to merge Varnodes into a HighVariable, the topological scope of each Varnode must not intersect because that would mean the high-level variable holds different values at the same point in the function.
Internally this is implemented as a map from basic block to their non-empty CoverBlock
Member Function Documentation
void Cover::addDefPoint (const Varnode * vn)
Reset to the single point where the given Varnode is defined.
Any previous cover is removed. Calling this with an input Varnode still produces a valid Cover.
Parameters
vn is the Varnode
References Varnode::getDef(), FlowBlock::getIndex(), PcodeOp::getParent(), Varnode::isInput(), CoverBlock::setBegin(), and CoverBlock::setEnd().
Referenced by Merge::buildDominantCopy(), Merge::checkCopyPair(), and Merge::eliminateIntersect().
void Cover::addRefPoint (const PcodeOp * ref, const Varnode * vn)
Add a variable read to this Cover.
Given a Varnode being read and the PcodeOp which reads it, add the point of the read to this and recursively fill in backwards until we run into existing cover.
Parameters
ref is the reading PcodeOp
vn is the Varnode being read
References PcodeOp::code(), CPUI_MULTIEQUAL, PcodeOp::getIn(), FlowBlock::getIn(), FlowBlock::getIndex(), PcodeOp::getParent(), CoverBlock::getUIndex(), PcodeOp::numInput(), CoverBlock::setEnd(), and FlowBlock::sizeIn().
Referenced by Merge::buildDominantCopy(), Merge::checkCopyPair(), and Merge::eliminateIntersect().
void Cover::addRefRecurse (const FlowBlock * bl) private
Fill-in this recursively from the given block.
Add to this Cover recursively, starting at bottom of the given block and filling in backward until we run into existing cover.
Parameters
bl is the starting block to add
References PcodeOp::code(), CPUI_MULTIEQUAL, FlowBlock::getIn(), FlowBlock::getIndex(), CoverBlock::getUIndex(), CoverBlock::setAll(), and FlowBlock::sizeIn().
int4 Cover::compareTo (const Cover & op2) const
Give ordering of this and another Cover.
Compare this with another Cover by comparing just the indices of the first blocks respectively that are partly covered. Return -1, 0, or 1 if this Cover's first block has a smaller, equal, or bigger index than the other Cover's first block.
Parameters
op2 is the other Cover
Returns
the comparison value
References cover.
Referenced by Merge::compareHighByBlock().
bool Cover::contain (const PcodeOp * op, int4 max) const
Does this contain the given PcodeOp.
Parameters
op is the given PcodeOp
max is 1 to test for any containment, 2 to force interior containment
Returns
true if there is containment
References FlowBlock::getIndex(), and PcodeOp::getParent().
Referenced by Merge::checkCopyPair(), and ActionMarkImplied::checkImpliedCover().
int4 Cover::containVarnodeDef (const Varnode * vn) const
Check the definition of a Varnode for containment.
If the given Varnode has a defining PcodeOp this is checked for containment. If the Varnode is an input, check if this covers the start of the function.
Return:
0 if cover does not contain varnode definition
1 if there if it is contained in interior
2 if the defining points intersect
3 if Cover's tail is the varnode definition
Parameters
vn is the given Varnode
Returns
the containment characterization
References Varnode::getDef(), FlowBlock::getIndex(), and PcodeOp::getParent().
Referenced by Merge::eliminateIntersect(), and Merge::hideShadows().
const CoverBlock & Cover::getCoverBlock (int4 i) const
Get the CoverBlock corresponding to the i-th block.
Return a representative CoverBlock describing how much of the given block is covered by this
Parameters
i is the index of the given block
Returns
a reference to the corresponding CoverBlock
Referenced by Merge::collectCorrectable(), and Merge::collectCovering().
int4 Cover::intersect (const Cover & op2) const
Characterize the intersection between this and another Cover.
Return
0 if there is no intersection
1 if the only intersection is on a boundary point
2 if the intersection contains a range of p-code ops
Parameters
op2 is the other Cover
Returns
the intersection characterization
References cover.
Referenced by Merge::buildDominantCopy(), Merge::inflateTest(), and Merge::shadowedVarnode().
int4 Cover::intersectByBlock (int4 blk, const Cover & op2) const
Characterize the intersection on a specific block.
Looking only at the given block, Return
0 if there is no intersection
1 if the only intersection is on a boundary point
2 if the intersection contains a range of p-code ops
Parameters
blk is the index of the given block
op2 is the other Cover
Returns
the characterization
References cover.
Referenced by Merge::blockIntersection().
void Cover::intersectList (vector< int4 > & listout, const Cover & op2, int4 level) const
Generate a list of blocks that intersect.
For each block for which this and another Cover intersect, and the block's index to a result list if the type of intersection exceeds a characterization level.
Parameters
listout will hold the list of intersecting block indices
op2 is the other Cover
level is the characterization threshold which must be exceeded
References cover.
Referenced by Merge::intersection().
void Cover::merge (const Cover & op2)
Merge this with another Cover block by block.
Parameters
op2 is the other Cover
References cover.
Referenced by Merge::buildDominantCopy(), Merge::inflate(), HighVariable::merge(), and HighVariable::updateCover().
void Cover::print (ostream & s) const
Dump a description of this cover to stream.
Parameters
s is the output stream
Referenced by HighVariable::printCover().
void Cover::rebuild (const Varnode * vn)
Reset this based on def-use of a single Varnode.
The cover is set to all p-code ops between the point where the Varnode is defined and all the points where it is read
Parameters
vn is the single Varnode
References Varnode::beginDescend(), and Varnode::endDescend().
The documentation for this class was generated from the following files:
cover.hh
cover.cc