decompiler: ActionMarkImplied Class Reference
ActionMarkImplied Class Reference
Mark all the implied Varnode objects, which will have no explicit token in the output.
#include <coreaction.hh>
Classes
struct DescTreeElement
This class holds a single entry in a stack used to forward traverse Varnode expressions.
Public Member Functions
ActionMarkImplied (const string &g)
Constructor.
virtual Action * clone (const ActionGroupList &grouplist) const
Clone the Action.
virtual int4 apply (Funcdata &data)
Make a single attempt to apply this Action.
Public Member Functions inherited from Action
Action (uint4 f, const string &nm, const string &g)
Base constructor for an Action.
virtual ~Action (void)
Destructor.
virtual void printStatistics (ostream &s) const
Dump statistics to stream.
int4 perform (Funcdata &data)
Perform this action (if necessary)
bool setBreakPoint (uint4 tp, const string &specify)
Set a breakpoint on this action.
virtual void clearBreakPoints (void)
Clear all breakpoints set on this Action.
bool setWarning (bool val, const string &specify)
Set a warning on this action.
bool disableRule (const string &specify)
Disable a specific Rule within this.
bool enableRule (const string &specify)
Enable a specific Rule within this.
const string & getName (void) const
Get the Action's name.
const string & getGroup (void) const
Get the Action's group.
uint4 getStatus (void) const
Get the current status of this Action.
uint4 getNumTests (void)
Get the number of times apply() was invoked.
uint4 getNumApply (void)
virtual void reset (Funcdata &data)
Reset the Action for a new function.
virtual void resetStats (void)
Reset all the counts to zero.
virtual int4 print (ostream &s, int4 num, int4 depth) const
Print a description of this Action to stream.
virtual void printState (ostream &s) const
Print status to stream.
virtual void saveXml (ostream &s) const
Save specifics of this action to stream.
virtual void restoreXml (const Element *el, Funcdata *fd)
Load specifics of action from XML.
virtual Action * getSubAction (const string &specify)
Retrieve a specific sub-action by name.
virtual Rule * getSubRule (const string &specify)
Retrieve a specific sub-rule by name.
Static Private Member Functions
static bool isPossibleAliasStep (Varnode *vn1, Varnode *vn2)
Check for additive relationship.
static bool isPossibleAlias (Varnode *vn1, Varnode *vn2, int4 depth)
Check for possible duplicate value.
static bool checkImpliedCover (Funcdata &data, Varnode *vn)
Check for cover violation if Varnode is implied.
Additional Inherited Members
Public Types inherited from Action
enum ruleflags {
rule_repeatapply = 4, rule_onceperfunc = 8, rule_oneactperfunc = 16, rule_debug = 32,
rule_warnings_on = 64, rule_warnings_given = 128
}
Boolean behavior properties governing this particular Action.
enum statusflags {
status_start =1, status_breakstarthit =2, status_repeat =4, status_mid =8,
status_end =16, status_actionbreak =32
}
Boolean properties describing the status of an action.
enum breakflags { break_start = 1, tmpbreak_start = 2, break_action = 4, tmpbreak_action = 8 }
Break points associated with an Action.
Protected Member Functions inherited from Action
void issueWarning (Architecture *glb)
Warn that this Action has applied.
bool checkStartBreak (void)
Check start breakpoint.
bool checkActionBreak (void)
Check action breakpoint.
void turnOnWarnings (void)
Enable warnings for this Action.
void turnOffWarnings (void)
Disable warnings for this Action.
Protected Attributes inherited from Action
int4 lcount
Changes not including last call to apply()
int4 count
Number of changes made by this action so far.
uint4 status
Current status.
uint4 breakpoint
Breakpoint properties.
uint4 flags
Behavior properties.
uint4 count_tests
Number of times apply() has been called.
uint4 count_apply
Number of times apply() made changes.
string name
Name of the action.
string basegroup
Base group this action belongs to.
Detailed Description
Mark all the implied Varnode objects, which will have no explicit token in the output.
Member Function Documentation
int4 ActionMarkImplied::apply (Funcdata & data) virtual
Make a single attempt to apply this Action.
This is the main entry point for applying changes to a function that are specific to this Action. The method can inspect whatever it wants to decide if the Action does or does not apply. Changes are indicated by incrementing the count field.
Parameters
data is the function to inspect/modify
Returns
0 for a complete application, -1 for a partial completion (due to breakpoint)
Implements Action.
References Funcdata::beginLoc(), Varnode::endDescend(), Funcdata::endLoc(), Varnode::getDef(), Varnode::getHigh(), PcodeOp::getIn(), Funcdata::getMerge(), Varnode::hasCover(), Merge::inflate(), Varnode::isExplicit(), Varnode::isFree(), Varnode::isImplied(), PcodeOp::numInput(), Varnode::setExplicit(), and Varnode::setImplied().
bool ActionMarkImplied::checkImpliedCover (Funcdata & data, Varnode * vn) static private
Check for cover violation if Varnode is implied.
Marking a Varnode as implied causes the input Varnodes to its defining op to propagate farther in the output. This may cause eventual variables to hold different values at the same point in the code. Any input must test that its propagated Cover doesn't intersect its current Cover.
Parameters
data is the function being analyzed
vn is the given Varnode
Returns
true if there is a Cover violation
References Funcdata::beginOp(), PcodeOp::code(), Cover::contain(), CPUI_LOAD, CPUI_STORE, Funcdata::endOp(), Funcdata::getCallSpecs(), Varnode::getCover(), Varnode::getDef(), Varnode::getHigh(), PcodeOp::getIn(), Funcdata::getMerge(), Varnode::getOffset(), FuncCallSpecs::getOp(), Merge::inflateTest(), PcodeOp::isCall(), Varnode::isConstant(), PcodeOp::isDead(), Funcdata::numCalls(), and PcodeOp::numInput().
virtual Action* ActionMarkImplied::clone (const ActionGroupList & grouplist) const inline virtual
Clone the Action.
If this Action is a member of one of the groups in the grouplist, this returns a clone of the Action, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Action or NULL
Implements Action.
References ActionStart::apply(), ActionGroupList::contains(), and Action::getGroup().
bool ActionMarkImplied::isPossibleAlias (Varnode * vn1, Varnode * vn2, int4 depth) static private
Check for possible duplicate value.
Return false only if we can guarantee two Varnodes have different values.
Parameters
vn1 is the first Varnode
vn2 is the second Varnode
depth is the maximum level to recurse
Returns
true if its possible the Varnodes hold the same value
References PcodeOp::code(), CPUI_COPY, CPUI_INT_2COMP, CPUI_INT_ADD, CPUI_INT_NEGATE, CPUI_INT_SEXT, CPUI_INT_ZEXT, CPUI_PTRADD, CPUI_PTRSUB, functionalEquality(), Varnode::getDef(), PcodeOp::getIn(), Varnode::getOffset(), Varnode::isConstant(), and Varnode::isWritten().
bool ActionMarkImplied::isPossibleAliasStep (Varnode * vn1, Varnode * vn2) static private
Check for additive relationship.
Return false only if one Varnode is obtained by adding non-zero thing to another Varnode. The order of the Varnodes is not important.
Parameters
vn1 is the first Varnode
vn2 is the second Varnode
Returns
false if the additive relationship holds
References PcodeOp::code(), CPUI_INT_ADD, CPUI_INT_XOR, CPUI_PTRADD, CPUI_PTRSUB, Varnode::getDef(), PcodeOp::getIn(), Varnode::isConstant(), and Varnode::isWritten().
The documentation for this class was generated from the following files:
coreaction.hh
coreaction.cc