decompiler: LoadImageXml Class Reference
LoadImageXml Class Reference
Implementation of the LoadImage interface using underlying data stored in an XML format.
#include <loadimage_xml.hh>
Public Member Functions
LoadImageXml (const string &f, const Element *el)
Constructor.
void open (const AddrSpaceManager *m)
Read XML tags into the containers.
void clear (void)
Clear out all the caches.
void saveXml (ostream &s) const
Save the image back out to an XML stream.
virtual void loadFill (uint1 *ptr, int4 size, const Address &addr)
Get data from the LoadImage.
virtual void openSymbols (void) const
Prepare to read symbols.
virtual bool getNextSymbol (LoadImageFunc &record) const
Get the next symbol record.
virtual void getReadonly (RangeList &list) const
Return list of readonly address ranges.
virtual string getArchType (void) const
Get a string indicating the architecture type.
virtual void adjustVma (long adjust)
Adjust load addresses with a global offset.
Public Member Functions inherited from LoadImage
LoadImage (const string &f)
LoadImage constructor.
virtual ~LoadImage (void)
LoadImage destructor.
const string & getFileName (void) const
Get the name of the LoadImage.
virtual void closeSymbols (void) const
Stop reading symbols.
virtual void openSectionInfo (void) const
Prepare to read section info.
virtual void closeSectionInfo (void) const
Stop reading section info.
virtual bool getNextSection (LoadImageSection &sec) const
Get info on the next section.
uint1 * load (int4 size, const Address &addr)
Load a chunk of image.
Private Member Functions
void pad (void)
Make sure every chunk is followed by at least 512 bytes of pad.
Private Attributes
const Element * rootel
The root XML element.
string archtype
The architecture string.
const AddrSpaceManager * manage
Manager of addresses.
set< Address > readonlyset
Starting address of read-only chunks.
map< Address, vector< uint1 > > chunk
Chunks of image data, mapped by address.
map< Address, string > addrtosymbol
Symbols sorted by address.
map< Address, string >::const_iterator cursymbol
Current symbol being reported.
Additional Inherited Members
Protected Attributes inherited from LoadImage
string filename
Name of the loadimage.
Detailed Description
Implementation of the LoadImage interface using underlying data stored in an XML format.
The image data is stored in an XML file in a <binaryimage> file. The data is encoded in <bytechunk> and potentially <symbol> files.
Constructor & Destructor Documentation
LoadImageXml::LoadImageXml (const string & f, const Element * el)
Constructor.
Parameters
f is the (path to the) underlying XML file
el is the parsed form of the file
References archtype, LoadImage::filename, Element::getAttributeValue(), Element::getName(), manage, and rootel.
Member Function Documentation
void LoadImageXml::adjustVma (long adjust) virtual
Adjust load addresses with a global offset.
Most load image formats automatically encode information about the true loading address(es) for the data in the image. But if this is missing or incorrect, this routine can be used to make a global adjustment to the load address. Only one adjustment is made across all addresses in the image. The offset passed to this method is added to the stored or default value for any address queried in the image. This is most often used in a raw binary file format. In this case, the entire executable file is intended to be read straight into RAM, as one contiguous chunk, in order to be executed. In the absence of any other info, the first byte of the image file is loaded at offset 0. This method then would adjust the load address of the first byte.
Parameters
adjust is the offset amount to be added to default values
Implements LoadImage.
References AddrSpace::addressToByte(), addrtosymbol, chunk, and AddrSpace::getWordSize().
Referenced by getArchType().
virtual string LoadImageXml::getArchType (void) const inline virtual
Get a string indicating the architecture type.
The load image class is intended to be a generic front-end to the large variety of load formats in use. This method should return a string that identifies the particular architecture this particular image is intended to run on. It is currently the responsibility of any derived LoadImage class to establish a format for this string, but it should generally contain some indication of the operating system and the processor.
Returns
the identifier string
Implements LoadImage.
References adjustVma(), and archtype.
bool LoadImageXml::getNextSymbol (LoadImageFunc & record) const virtual
Get the next symbol record.
This method is used to read out an individual symbol record, LoadImageFunc, from the load image. Right now, the only information that can be read out are function starts and the associated function name. This method can be called repeatedly to iterate through all the symbols, until it returns false. This indicates the end of the symbols.
Parameters
record is a reference to the symbol record to be filled in
Returns
true if there are more records to read
Reimplemented from LoadImage.
References LoadImageFunc::address, addrtosymbol, cursymbol, and LoadImageFunc::name.
void LoadImageXml::getReadonly (RangeList & list) const virtual
Return list of readonly address ranges.
This method should read out information about all address ranges within the load image that are known to be readonly. This method is intended to be called only once, so all information should be written to the passed RangeList object.
Parameters
list is where readonly info will get put
Reimplemented from LoadImage.
References chunk, RangeList::insertRange(), and readonlyset.
void LoadImageXml::loadFill (uint1 * ptr, int4 size, const Address & addr) virtual
Get data from the LoadImage.
This is the core routine of a LoadImage. Given a particular address range, this routine retrieves the exact byte values that are stored at that address when the executable is loaded into RAM. The caller must supply a pre-allocated array of bytes where the returned bytes should be stored. If the requested address range does not exist in the image, or otherwise can't be retrieved, this method throws an DataUnavailError exception.
Parameters
ptr points to where the resulting bytes will be stored
size is the number of bytes to retrieve from the image
addr is the starting address of the bytes to retrieve
Implements LoadImage.
References chunk, Address::overlap(), and Address::printRaw().
void LoadImageXml::open (const AddrSpaceManager * m)
Read XML tags into the containers.
Parameters
m is for looking up address space
References addrtosymbol, chunk, Element::getAttributeName(), Element::getAttributeValue(), Element::getChildren(), Element::getContent(), Element::getName(), Element::getNumAttributes(), AddrSpaceManager::getSpaceByName(), manage, pad(), readonlyset, AddrSpace::restoreXmlAttributes(), rootel, and xml_readbool().
void LoadImageXml::openSymbols (void) const virtual
Prepare to read symbols.
This routine should read in and parse any symbol information that the load image contains about executable. Once this method is called, individual symbol records are read out using the getNextSymbol() method.
Reimplemented from LoadImage.
References addrtosymbol, and cursymbol.
void LoadImageXml::saveXml (ostream & s) const
Save the image back out to an XML stream.
Write out the byte chunks and symbols as XML tags
Parameters
s is the output stream
References addrtosymbol, archtype, chunk, and readonlyset.
The documentation for this class was generated from the following files:
loadimage_xml.hh
loadimage_xml.cc