decompiler: ExternRefSymbol Class Reference
ExternRefSymbol Class Reference
A function Symbol referring to an external location.
#include <database.hh>
Public Member Functions
ExternRefSymbol (Scope *sc, const Address &ref, const string &nm)
Construct given a placeholder address.
ExternRefSymbol (Scope *sc)
For use with restoreXml.
const Address & getRefAddr (void) const
Return the placeholder address.
virtual void saveXml (ostream &s) const
Save this Symbol to an XML stream.
virtual void restoreXml (const Element *el)
Restore this Symbol from an XML stream.
Public Member Functions inherited from Symbol
Symbol (Scope *sc, const string &nm, Datatype *ct)
Construct given a name and data-type.
Symbol (Scope *sc)
Construct for use with restoreXml()
const string & getName (void) const
Get the local name of the symbol.
Datatype * getType (void) const
Get the data-type.
uint8 getId (void) const
Get a unique id for the symbol.
uint4 getFlags (void) const
Get the boolean properties of the Symbol.
uint4 getDisplayFormat (void) const
Get the format to display the Symbol in.
int2 getCategory (void) const
Get the Symbol category.
uint2 getCategoryIndex (void) const
Get the position of the Symbol within its category.
bool isTypeLocked (void) const
Is the Symbol type-locked.
bool isNameLocked (void) const
Is the Symbol name-locked.
bool isSizeTypeLocked (void) const
Is the Symbol size type-locked.
bool isThisPointer (void) const
Is this the "this" pointer.
bool isIndirectStorage (void) const
Is storage really a pointer to the true Symbol.
bool isHiddenReturn (void) const
Is this a reference to the function return value.
bool isNameUndefined (void) const
Does this have an undefined name.
bool isMultiEntry (void) const
Does this have more than one entire mapping.
bool hasMergeProblems (void) const
Were some SymbolEntrys not merged.
void setMergeProblems (void)
Mark that some SymbolEntrys could not be merged.
bool isIsolated (void) const
Return true if this is isolated from speculative merging.
void setIsolated (bool val)
Set whether this Symbol should be speculatively merged.
Scope * getScope (void) const
Get the scope owning this Symbol.
SymbolEntry * getFirstWholeMap (void) const
Get the first entire mapping of the symbol.
SymbolEntry * getMapEntry (const Address &addr) const
Get first mapping of the symbol that contains the given Address.
int4 numEntries (void) const
Return the number of SymbolEntrys.
SymbolEntry * getMapEntry (int4 i) const
Return the i-th SymbolEntry for this Symbol.
int4 getMapEntryPosition (const SymbolEntry *entry) const
Position of given SymbolEntry within this multi-entry Symbol.
int4 getResolutionDepth (const Scope *useScope) const
Get number of scope names needed to resolve this symbol.
void saveXmlHeader (ostream &s) const
Save basic Symbol properties as XML attributes.
void restoreXmlHeader (const Element *el)
Restore basic Symbol properties from XML.
void saveXmlBody (ostream &s) const
Save details of the Symbol to XML.
void restoreXmlBody (List::const_iterator iter)
Restore details of the Symbol from XML.
virtual int4 getBytesConsumed (void) const
Get number of bytes consumed within the address->symbol map.
Private Member Functions
void buildNameType (void)
Create a name and data-type for the Symbol.
Private Attributes
Address refaddr
The placeholder address for meta-data.
Additional Inherited Members
Public Types inherited from Symbol
enum {
force_hex = 1, force_dec = 2, force_oct = 3, force_bin = 4,
force_char = 5, size_typelock = 8, isolate = 16, merge_problems = 32,
is_this_ptr = 64
}
Possible display (dispflag) properties for a Symbol.
Static Public Attributes inherited from Symbol
static uint8 ID_BASE = 0x4000000000000000L
Base of internal ID's.
Protected Member Functions inherited from Symbol
virtual ~Symbol (void)
Destructor.
void setDisplayFormat (uint4 val)
Set the display format for this Symbol.
void checkSizeTypeLock (void)
Calculate if size_typelock property is on.
void setThisPointer (bool val)
Toggle whether this is the "this" pointer for a class method.
Protected Attributes inherited from Symbol
Scope * scope
The scope that owns this symbol.
string name
The local name of the symbol.
Datatype * type
The symbol's data-type.
uint4 nameDedup
id to distinguish symbols with the same name
uint4 flags
Varnode-like properties of the symbol.
uint4 dispflags
Flags affecting the display of this symbol.
int2 category
Special category (-1==none 0=parameter 1=equate)
uint2 catindex
Index within category.
uint8 symbolId
Unique id, 0=unassigned.
vector< list< SymbolEntry >::iterator > mapentry
List of storage locations labeled with this Symbol.
const Scope * depthScope
Scope associated with current depth resolution.
int4 depthResolution
Number of namespace elements required to resolve symbol in current scope.
uint4 wholeCount
Number of SymbolEntries that map to the whole Symbol.
Detailed Description
A function Symbol referring to an external location.
This Symbol is intended to label functions that have not been mapped directly into the image being analyzed. It holds a level of indirection between the address the image expects the symbol to be at and a placeholder address the system hangs meta-data on.
Constructor & Destructor Documentation
ExternRefSymbol::ExternRefSymbol (Scope * sc, const Address & ref, const string & nm)
Construct given a placeholder address.
Parameters
sc is the Scope containing the Symbol
ref is the placeholder address where the system will hold meta-data
nm is the name of the Symbol
References buildNameType(), and refaddr.
Referenced by Scope::addExternalRef(), and Scope::addMapSym().
Member Function Documentation
void ExternRefSymbol::buildNameType (void) private
Create a name and data-type for the Symbol.
Build name, type, and flags based on the placeholder address.
References Varnode::externref, Symbol::flags, Scope::getArch(), TypeFactory::getTypeCode(), TypeFactory::getTypePointer(), Symbol::name, TypePointer::printRaw(), Symbol::scope, Symbol::type, Varnode::typelock, and Architecture::types.
Referenced by ExternRefSymbol(), and restoreXml().
void ExternRefSymbol::restoreXml (const Element * el) virtual
Restore this Symbol from an XML stream.
Parameters
el is the root XML tag of the symbol
Reimplemented from Symbol.
References buildNameType(), Scope::getArch(), Element::getAttributeName(), Element::getAttributeValue(), Element::getChildren(), Element::getNumAttributes(), Symbol::name, refaddr, Address::restoreXml(), and Symbol::scope.
void ExternRefSymbol::saveXml (ostream & s) const virtual
Save this Symbol to an XML stream.
Parameters
s is the output stream
Reimplemented from Symbol.
References a_v(), Symbol::name, refaddr, and Address::saveXml().
Referenced by Scope::saveXmlRecursive().
The documentation for this class was generated from the following files:
database.hh
database.cc