decompiler: CastStrategyJava Class Reference
CastStrategyJava Class Reference
Casting strategies that are specific to the Java language.
#include <cast.hh>
Public Member Functions
virtual Datatype * castStandard (Datatype *reqtype, Datatype *curtype, bool care_uint_int, bool care_ptr_uint) const
Does there need to be a visible cast between the given data-types.
virtual bool isZextCast (Datatype *outtype, Datatype *intype) const
Is zero-extending an input data-type, producing an output data-type, considered a cast.
Public Member Functions inherited from CastStrategyC
virtual int4 localExtensionType (const Varnode *vn) const
Decide on integer promotion by examining just local properties of the given Varnode.
virtual int4 intPromotionType (const Varnode *vn) const
Calculate the integer promotion code of a given Varnode.
virtual bool checkIntPromotionForCompare (const PcodeOp *op, int4 slot) const
Check if integer promotion forces a cast for the given comparison op and slot.
virtual bool checkIntPromotionForExtension (const PcodeOp *op) const
Check if integer promotion forces a cast for the input to the given extension.
virtual bool isExtensionCastImplied (const PcodeOp *op, const PcodeOp *readOp) const
Is the given ZEXT/SEXT cast implied by the expression its in?
virtual Datatype * arithmeticOutputStandard (const PcodeOp *op)
What is the output data-type produced by the given integer arithmetic operation.
virtual bool isSubpieceCast (Datatype *outtype, Datatype *intype, uint4 offset) const
Is truncating an input data-type, producing an output data-type, considered a cast.
virtual bool isSubpieceCastEndian (Datatype *outtype, Datatype *intype, uint4 offset, bool isbigend) const
Is the given data-type truncation considered a cast, given endianess concerns.
virtual bool isSextCast (Datatype *outtype, Datatype *intype) const
Is sign-extending an input data-type, producing an output data-type, considered a cast.
Public Member Functions inherited from CastStrategy
CastStrategy (void)
Constructor.
void setTypeFactory (TypeFactory *t)
Establish the data-type factory.
virtual ~CastStrategy (void)
Destructor.
Additional Inherited Members
Public Types inherited from CastStrategy
enum IntPromotionCode {
NO_PROMOTION = -1, UNKNOWN_PROMOTION = 0, UNSIGNED_EXTENSION = 1, SIGNED_EXTENSION = 2,
EITHER_EXTENSION = 3
}
Types of integer promotion.
Protected Attributes inherited from CastStrategy
TypeFactory * tlst
Type factory associated with the Architecture.
int4 promoteSize
Size of int data-type, (size that integers get promoted to)
Detailed Description
Casting strategies that are specific to the Java language.
This is nearly identical to the strategy for C, but there is some change to account for the way object references are encoded as pointer data-types within the decompiler's data-type system.
Member Function Documentation
Datatype * CastStrategyJava::castStandard (Datatype * reqtype, Datatype * curtype, bool care_uint_int, bool care_ptr_uint) const virtual
Does there need to be a visible cast between the given data-types.
The cast is from a current data-type to an expected data-type. NULL is returned if no cast is required, otherwise the data-type to cast to (usually the expected data-type) is returned.
Parameters
reqtype is the expected data-type
curtype is the current data-type
care_uint_int is true if we care about a change in signedness
care_ptr_uint is true if we care about conversions between pointers and unsigned values
Returns
NULL to indicate no cast, or the data-type to cast to
Reimplemented from CastStrategyC.
References Datatype::getMetatype(), Datatype::getSize(), TYPE_BOOL, TYPE_CODE, TYPE_INT, TYPE_PTR, TYPE_UINT, TYPE_UNKNOWN, and TYPE_VOID.
bool CastStrategyJava::isZextCast (Datatype * outtype, Datatype * intype) const virtual
Is zero-extending an input data-type, producing an output data-type, considered a cast.
Data-types must be provided from the input and output of an INT_ZEXT operation.
Parameters
outtype is the output data-type
intype is the input data-type
Returns
true if the INT_ZEXT should be represented as a cast
Reimplemented from CastStrategyC.
References Datatype::getMetatype(), Datatype::getSize(), Datatype::isCharPrint(), TYPE_BOOL, TYPE_INT, and TYPE_UINT.
The documentation for this class was generated from the following files:
cast.hh
cast.cc