decompiler: ActionLikelyTrash Class Reference
ActionLikelyTrash Class Reference
Get rid of registers with trash values.
#include <coreaction.hh>
Public Member Functions
ActionLikelyTrash (const string &g)
Constructor.
virtual Action * clone (const ActionGroupList &grouplist) const
Clone the Action.
virtual int4 apply (Funcdata &data)
Make a single attempt to apply this Action.
Public Member Functions inherited from Action
Action (uint4 f, const string &nm, const string &g)
Base constructor for an Action.
virtual ~Action (void)
Destructor.
virtual void printStatistics (ostream &s) const
Dump statistics to stream.
int4 perform (Funcdata &data)
Perform this action (if necessary)
bool setBreakPoint (uint4 tp, const string &specify)
Set a breakpoint on this action.
virtual void clearBreakPoints (void)
Clear all breakpoints set on this Action.
bool setWarning (bool val, const string &specify)
Set a warning on this action.
bool disableRule (const string &specify)
Disable a specific Rule within this.
bool enableRule (const string &specify)
Enable a specific Rule within this.
const string & getName (void) const
Get the Action's name.
const string & getGroup (void) const
Get the Action's group.
uint4 getStatus (void) const
Get the current status of this Action.
uint4 getNumTests (void)
Get the number of times apply() was invoked.
uint4 getNumApply (void)
virtual void reset (Funcdata &data)
Reset the Action for a new function.
virtual void resetStats (void)
Reset all the counts to zero.
virtual int4 print (ostream &s, int4 num, int4 depth) const
Print a description of this Action to stream.
virtual void printState (ostream &s) const
Print status to stream.
virtual void saveXml (ostream &s) const
Save specifics of this action to stream.
virtual void restoreXml (const Element *el, Funcdata *fd)
Load specifics of action from XML.
virtual Action * getSubAction (const string &specify)
Retrieve a specific sub-action by name.
virtual Rule * getSubRule (const string &specify)
Retrieve a specific sub-rule by name.
Static Private Member Functions
static uint4 countMarks (PcodeOp *op)
static bool traceTrash (Varnode *vn, vector< PcodeOp * > &indlist)
Decide if the given Varnode only ever flows into CPUI_INDIRECT.
Additional Inherited Members
Public Types inherited from Action
enum ruleflags {
rule_repeatapply = 4, rule_onceperfunc = 8, rule_oneactperfunc = 16, rule_debug = 32,
rule_warnings_on = 64, rule_warnings_given = 128
}
Boolean behavior properties governing this particular Action.
enum statusflags {
status_start =1, status_breakstarthit =2, status_repeat =4, status_mid =8,
status_end =16, status_actionbreak =32
}
Boolean properties describing the status of an action.
enum breakflags { break_start = 1, tmpbreak_start = 2, break_action = 4, tmpbreak_action = 8 }
Break points associated with an Action.
Protected Member Functions inherited from Action
void issueWarning (Architecture *glb)
Warn that this Action has applied.
bool checkStartBreak (void)
Check start breakpoint.
bool checkActionBreak (void)
Check action breakpoint.
void turnOnWarnings (void)
Enable warnings for this Action.
void turnOffWarnings (void)
Disable warnings for this Action.
Protected Attributes inherited from Action
int4 lcount
Changes not including last call to apply()
int4 count
Number of changes made by this action so far.
uint4 status
Current status.
uint4 breakpoint
Breakpoint properties.
uint4 flags
Behavior properties.
uint4 count_tests
Number of times apply() has been called.
uint4 count_apply
Number of times apply() made changes.
string name
Name of the action.
string basegroup
Base group this action belongs to.
Detailed Description
Get rid of registers with trash values.
Register locations called likely trash are read as a side-effect of some instruction the compiler was using. The canonical example in x86 code is the PUSH ECX which compilers use to create space on the stack without caring about what's in ECX. Even though the decompiler can see that the read ECX value is never getting used directly by the function, because the value is getting copied to the stack, the decompiler frequently can't tell if the value has been aliased across sub-function calls. By marking the ECX register as likely \ trash the decompiler will assume that, unless there is a direct read of the incoming ECX, none of subfunctions alias the stack location where ECX was stored. This allows the spurious references to the register to be removed.
Member Function Documentation
int4 ActionLikelyTrash::apply (Funcdata & data) virtual
Make a single attempt to apply this Action.
This is the main entry point for applying changes to a function that are specific to this Action. The method can inspect whatever it wants to decide if the Action does or does not apply. Changes are indicated by incrementing the count field.
Parameters
data is the function to inspect/modify
Returns
0 for a complete application, -1 for a partial completion (due to breakpoint)
Implements Action.
References PcodeOp::code(), CPUI_INDIRECT, CPUI_INT_AND, Funcdata::findCoveredInput(), Funcdata::getFuncProto(), PcodeOp::getIn(), FuncProto::getLikelyTrash(), PcodeOp::getOut(), Varnode::getSize(), Funcdata::markIndirectCreation(), Funcdata::newConstant(), FuncProto::numLikelyTrash(), and Funcdata::opSetInput().
virtual Action* ActionLikelyTrash::clone (const ActionGroupList & grouplist) const inline virtual
Clone the Action.
If this Action is a member of one of the groups in the grouplist, this returns a clone of the Action, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Action or NULL
Implements Action.
References ActionStart::apply(), ActionGroupList::contains(), and Action::getGroup().
uint4 ActionLikelyTrash::countMarks (PcodeOp * op) static private
Count the number of inputs to op which have their mark set
Parameters
op is the PcodeOp to count
Returns
the number of marks set
References PcodeOp::code(), CPUI_INDIRECT, Varnode::getDef(), PcodeOp::getIn(), Varnode::isMark(), Varnode::isWritten(), and PcodeOp::numInput().
bool ActionLikelyTrash::traceTrash (Varnode * vn, vector< PcodeOp * > & indlist) static private
Decide if the given Varnode only ever flows into CPUI_INDIRECT.
Return all the CPUI_INDIRECT ops that the Varnode hits in a list. Trace forward down all paths from -vn-, if we hit
CPUI_INDIRECT -> trim that path and store that op in the resulting -indlist-
CPUI_SUBPIECE
CPUI_MULTIEQUAL
CPUI_PIECE
CPUI_AND -> follow through to output
anything else -> consider -vn- to NOT be trash
For any CPUI_MULTIEQUAL and CPUI_PIECE that are hit, all the other inputs must be hit as well
Parameters
vn is the given Varnode
indlist is the list to populate with CPUI_INDIRECT ops
Returns
true if all flows look like trash
References Varnode::beginDescend(), calc_mask(), PcodeOp::code(), CPUI_INDIRECT, CPUI_INT_AND, CPUI_MULTIEQUAL, CPUI_PIECE, CPUI_SUBPIECE, Varnode::endDescend(), PcodeOp::getIn(), Varnode::getOffset(), PcodeOp::getOut(), Varnode::getSize(), Varnode::isConstant(), PcodeOp::isIndirectStore(), PcodeOp::isMark(), Varnode::isMark(), Varnode::isPersist(), PcodeOp::numInput(), PcodeOp::setMark(), and Varnode::setMark().
The documentation for this class was generated from the following files:
coreaction.hh
coreaction.cc