decompiler: ActionGroupList Class Reference
ActionGroupList Class Reference
The list of groups defining a root Action.
#include <action.hh>
Public Member Functions
bool contains (const string &nm) const
Check if this ActionGroupList contains a given group.
Private Attributes
set< string > list
List of group names.
Friends
class ActionDatabase
Detailed Description
The list of groups defining a root Action.
Any Rule or leaf Action belongs to a group. This class is a grouplist defined by a collection of these group names. The set of Rule and Action objects belong to any of the groups in this list together form a root Action.
Member Function Documentation
bool ActionGroupList::contains (const string & nm) const inline
Check if this ActionGroupList contains a given group.
Parameters
nm is the given group to check for
Returns
true if this contains the group
Referenced by ActionStart::clone(), ActionStop::clone(), ActionStartCleanUp::clone(), ActionStartTypes::clone(), RuleEarlyRemoval::clone(), ActionStackPtrFlow::clone(), RuleCollectTerms::clone(), RuleSelectCse::clone(), ActionLaneDivide::clone(), RulePiece2Zext::clone(), ActionSegmentize::clone(), RulePiece2Sext::clone(), ActionForceGoto::clone(), RuleBxor2NotEqual::clone(), RuleOrMask::clone(), RuleAndMask::clone(), ActionMultiCse::clone(), RuleOrConsume::clone(), ActionShadowVar::clone(), ActionConditionalExe::clone(), RuleOrCollapse::clone(), RuleAndOrLump::clone(), ActionConstantPtr::clone(), RuleNegateIdentity::clone(), ActionDeindirect::clone(), RuleShiftBitops::clone(), ActionVarnodeProps::clone(), RuleRightShiftAnd::clone(), RuleIntLessEqual::clone(), RuleOrPredicate::clone(), RuleEquality::clone(), ActionDirectWrite::clone(), RuleTermOrder::clone(), ActionConstbase::clone(), RulePullsubMulti::clone(), ActionSpacebase::clone(), ActionNormalizeBranches::clone(), RulePullsubIndirect::clone(), ActionHeritage::clone(), RulePushMulti::clone(), ActionNonzeroMask::clone(), ActionPreferComplement::clone(), RuleDoubleIn::clone(), RuleNotDistribute::clone(), ActionBlockStructure::clone(), RuleHighOrderAnd::clone(), RuleDoubleLoad::clone(), ActionFinalStructure::clone(), RuleAndDistribute::clone(), ActionSetCasts::clone(), RuleLessOne::clone(), ActionReturnSplit::clone(), ActionAssignHigh::clone(), RuleRangeMeld::clone(), ActionNodeJoin::clone(), ActionMarkIndirectOnly::clone(), RuleFloatRange::clone(), ActionMergeRequired::clone(), RuleAndCommute::clone(), ActionMergeAdjacent::clone(), RuleAndPiece::clone(), ActionMergeCopy::clone(), RuleAndCompare::clone(), ActionMergeMultiEntry::clone(), RuleDoubleSub::clone(), RuleDoubleShift::clone(), ActionMergeType::clone(), RuleDoubleArithShift::clone(), RuleConcatShift::clone(), RuleLeftRight::clone(), ActionMarkExplicit::clone(), RuleShiftCompare::clone(), ActionMarkImplied::clone(), RuleLessEqual::clone(), RuleLessNotEqual::clone(), ActionNameVars::clone(), RuleTrivialArith::clone(), ActionUnreachable::clone(), RuleTrivialBool::clone(), ActionDoNothing::clone(), RuleZextEliminate::clone(), ActionRedundBranch::clone(), RuleSlessToLess::clone(), ActionDeterminedBranch::clone(), RuleZextSless::clone(), RuleBitUndistribute::clone(), RuleBooleanNegate::clone(), RuleBoolZext::clone(), ActionDeadCode::clone(), RuleLogic2Bool::clone(), ActionConditionalConst::clone(), RuleIndirectCollapse::clone(), ActionSwitchNorm::clone(), RuleMultiCollapse::clone(), RuleSborrow::clone(), ActionNormalizeSetup::clone(), RuleTrivialShift::clone(), RuleSignShift::clone(), ActionPrototypeTypes::clone(), RuleTestSign::clone(), ActionDefaultParams::clone(), RuleIdentityEl::clone(), RuleShift2Mult::clone(), ActionExtraPopSetup::clone(), RuleShiftPiece::clone(), RuleCollapseConstants::clone(), ActionFuncLink::clone(), RuleTransformCpool::clone(), RulePropagateCopy::clone(), ActionFuncLinkOutOnly::clone(), Rule2Comp2Mult::clone(), RuleCarryElim::clone(), ActionParamDouble::clone(), RuleSub2Add::clone(), ActionActiveParam::clone(), RuleXorCollapse::clone(), RuleAddMultCollapse::clone(), ActionActiveReturn::clone(), RuleLoadVarnode::clone(), RuleStoreVarnode::clone(), ActionReturnRecovery::clone(), ActionRestrictLocal::clone(), RuleSubExtComm::clone(), RuleSubCommute::clone(), RuleConcatCommute::clone(), ActionLikelyTrash::clone(), ActionRestructureVarnode::clone(), RuleConcatZext::clone(), ActionRestructureHigh::clone(), RuleZextCommute::clone(), RuleZextShiftZext::clone(), ActionMapGlobals::clone(), RuleShiftAnd::clone(), ActionInputPrototype::clone(), RuleConcatZero::clone(), ActionOutputPrototype::clone(), RuleConcatLeftShift::clone(), ActionUnjustifiedParams::clone(), RuleSubZext::clone(), RuleSubCancel::clone(), RuleShiftSub::clone(), RuleHumptyDumpty::clone(), RuleDumptyHump::clone(), RuleHumptyOr::clone(), ActionInferTypes::clone(), RuleEmbed::clone(), RuleSwitchSingle::clone(), ActionHideShadow::clone(), RuleCondNegate::clone(), ActionDominantCopy::clone(), RuleBoolNegate::clone(), ActionCopyMarker::clone(), RuleLess2Zero::clone(), ActionDynamicMapping::clone(), RuleLessEqual2Zero::clone(), ActionDynamicSymbols::clone(), RuleSLess2Zero::clone(), ActionPrototypeWarnings::clone(), RuleEqual2Zero::clone(), RuleEqual2Constant::clone(), RulePtrArith::clone(), RuleStructOffset0::clone(), RulePushPtr::clone(), RulePtraddUndo::clone(), RulePtrsubUndo::clone(), RuleMultNegOne::clone(), RuleAddUnsigned::clone(), Rule2Comp2Sub::clone(), RuleSubRight::clone(), RulePtrsubCharConstant::clone(), RuleSubNormal::clone(), RulePositiveDiv::clone(), RuleDivTermAdd::clone(), RuleDivTermAdd2::clone(), RuleDivOpt::clone(), RuleSignDiv2::clone(), RuleSignForm::clone(), RuleSignNearMult::clone(), RuleModOpt::clone(), RuleSegment::clone(), RuleSubvarAnd::clone(), RuleSubvarSubpiece::clone(), RuleSplitFlow::clone(), RulePtrFlow::clone(), RuleSubvarCompZero::clone(), RuleSubvarShift::clone(), RuleSubvarZext::clone(), RuleSubvarSext::clone(), RuleSubfloatConvert::clone(), RuleNegateNegate::clone(), RuleConditionalMove::clone(), RuleFloatCast::clone(), RuleIgnoreNan::clone(), RuleFuncPtrEncoding::clone(), RuleThreeWayCompare::clone(), RulePopcountBoolXor::clone(), RulePiecePathology::clone(), and RuleXorSwap::clone().
The documentation for this class was generated from the following file:
action.hh