decompiler: Address Class Reference
Address Class Reference
A low-level machine address for labelling bytes and data.
#include <address.hh>
Public Types
enum mach_extreme { m_minimal, m_maximal }
An enum for specifying extremal addresses.
Public Member Functions
Address (mach_extreme ex)
Initialize an extremal address.
Address (void)
Create an invalid address.
Address (AddrSpace *id, uintb off)
Construct an address with a space/offset pair.
Address (const Address &op2)
A copy constructor.
bool isInvalid (void) const
Is the address invalid?
int4 getAddrSize (void) const
Get the number of bytes in the address.
bool isBigEndian (void) const
Is data at this address big endian encoded.
void printRaw (ostream &s) const
Write a raw version of the address to a stream.
int4 read (const string &s)
Read in the address from a string.
AddrSpace * getSpace (void) const
Get the address space.
uintb getOffset (void) const
Get the address offset.
void toPhysical (void)
Convert this to a physical address.
char getShortcut (void) const
Get the shortcut character for the address space.
Address & operator= (const Address &op2)
Copy an address.
bool operator== (const Address &op2) const
Compare two addresses for equality.
bool operator!= (const Address &op2) const
Compare two addresses for inequality.
bool operator< (const Address &op2) const
Compare two addresses via their natural ordering.
bool operator<= (const Address &op2) const
Compare two addresses via their natural ordering.
Address operator+ (int4 off) const
Increment address by a number of bytes.
Address operator- (int4 off) const
Decrement address by a number of bytes.
bool containedBy (int4 sz, const Address &op2, int4 sz2) const
Determine if op2 range contains this range.
int4 justifiedContain (int4 sz, const Address &op2, int4 sz2, bool forceleft) const
Determine if op2 is the least significant part of this.
int4 overlap (int4 skip, const Address &op, int4 size) const
Determine how two address ranges overlap.
bool isContiguous (int4 sz, const Address &loaddr, int4 losz) const
Does this form a contigous range with loaddr.
bool isConstant (void) const
Is this a constant value.
void renormalize (int4 size)
Make sure there is a backing JoinRecord if this is in the join space.
bool isJoin (void) const
Is this a join value.
void saveXml (ostream &s) const
Save this to a stream as an XML tag.
void saveXml (ostream &s, int4 size) const
Save this and a size to a stream as an XML tag.
Static Public Member Functions
static Address restoreXml (const Element *el, const AddrSpaceManager *manage)
Restore an address from parsed XML.
static Address restoreXml (const Element *el, const AddrSpaceManager *manage, int4 &size)
Restore an address and size from parsed XML.
static AddrSpace * getSpaceFromConst (const Address &addr)
Recover an encoded address space from an address.
Protected Attributes
AddrSpace * base
Pointer to our address space.
uintb offset
Offset (in bytes)
Friends
ostream & operator<< (ostream &s, const Address &addr)
Write out an address to stream.
Detailed Description
A low-level machine address for labelling bytes and data.
All data that can be manipulated within the processor reverse engineering model can be labelled with an Address. It is simply an address space (AddrSpace) and an offset within that space. Note that processor registers are typically modelled by creating a dedicated address space for them, as distinct from RAM say, and then specifying certain addresses within the register space that correspond to particular registers. However, an arbitrary address could refer to anything, RAM, ROM, cpu register, data segment, coprocessor, stack, nvram, etc. An Address represents an offset only, not an offset and length
Member Enumeration Documentation
enum Address::mach_extreme
An enum for specifying extremal addresses.
Enumerator
m_minimal
Smallest possible address.
m_maximal
Biggest possible address.
Constructor & Destructor Documentation
Address::Address (mach_extreme ex)
Initialize an extremal address.
Some data structures sort on an Address, and it is convenient to be able to create an Address that is either bigger than or smaller than all other Addresses.
Parameters
ex is either m_minimal or m_maximal
Address::Address (void) inline
Create an invalid address.
An invalid address is possible in some circumstances. This deliberately constructs an invalid address
References base.
Referenced by Range::getFirstAddr(), Range::getLastAddr(), operator+(), and operator-().
Address::Address (AddrSpace * id, uintb off) inline
Construct an address with a space/offset pair.
This is the basic Address constructor
Parameters
id is the space containing the address
off is the offset of the address
References base, and offset.
Address::Address (const Address & op2) inline
A copy constructor.
This is a standard copy constructor, copying the address space and the offset
Parameters
op2 is the Address to copy
References base, and offset.
Member Function Documentation
bool Address::containedBy (int4 sz, const Address & op2, int4 sz2) const
Determine if op2 range contains this range.
Return true if the range starting at this extending the given number of bytes is contained by the second given range.
Parameters
sz is the given number of bytes in this range
op2 is the start of the second given range
sz2 is the number of bytes in the second given range
Returns
true if the second given range contains this range
References base, and offset.
Referenced by FuncProto::characterizeAsInputParam(), and FuncProto::getBiggestContainedInputParam().
int4 Address::getAddrSize (void) const inline
Get the number of bytes in the address.
Get the number of bytes needed to encode the offset for this address.
Returns
the number of bytes in the encoding
References base, and AddrSpace::getAddrSize().
Referenced by ScopeLocal::buildVariableName(), ScopeInternal::buildVariableName(), ToOpEdge::hash(), Heritage::normalizeReadSize(), Heritage::normalizeWriteSize(), and Funcdata::spacebaseConstant().
uintb Address::getOffset (void) const inline
Get the address offset.
Get the offset of the address as an integer.
Returns
the offset integer
References offset.
Referenced by Scope::addDynamicSymbol(), Scope::addMap(), ScopeInternal::addMapInternal(), Scope::addMapPoint(), ScopeLocal::adjustFit(), Funcdata::adjustInputVarnodes(), ActionShadowVar::apply(), ActionRestrictLocal::apply(), ParamEntry::assumedExtension(), FuncCallSpecs::buildParam(), Heritage::buildRefinement(), ScopeLocal::buildVariableName(), ScopeInternal::buildVariableName(), ParamListStandard::characterizeAsParam(), Varnode::characterizeOverlap(), Funcdata::checkForLanedRegister(), ParamListStandard::checkJoin(), Heritage::collect(), Varnode::constantMatch(), AddrSpaceManager::constructFloatExtensionAddress(), AddrSpaceManager::constructJoinAddress(), ParamEntry::containedBy(), Range::contains(), Varnode::contains(), Funcdata::coverVarnodes(), ScopeGhidra::dump2Cache(), EffectRecord::EffectRecord(), PrintC::emitLabel(), PrintLanguage::emitLineComment(), VarnodeBank::endLoc(), SymbolEntry::EntrySubsort::EntrySubsort(), EmulatePcodeCache::executeBranch(), ScopeLocal::fakeInputSymbols(), ScopeInternal::findAddr(), ScopeInternal::findClosestFit(), ScopeInternal::findCodeLabel(), ScopeGhidra::findContainer(), ScopeInternal::findContainer(), VarnodeBank::findCoveredInput(), VarnodeBank::findCoveringInput(), Funcdata::findDisjointCover(), ParamListStandard::findEntry(), ScopeInternal::findExternalRef(), ScopeInternal::findFunction(), ScopeInternal::findOverlap(), Funcdata::Funcdata(), ActionFuncLink::funcLinkInput(), FuncProto::getBiggestContainedInputParam(), ParamListStandard::getBiggestContainedParam(), ParamEntry::getContainer(), ContextInternal::getContext(), ContextCache::getContext(), SymbolEntry::getFirst(), FuncCallSpecs::getFspecFromConst(), SymbolEntry::getLast(), Symbol::getMapEntry(), Varnode::getOffset(), PcodeOp::getOpName(), GhidraTranslate::getRegister(), FlowInfo::getSize(), SymbolEntry::getSizedType(), ParamEntry::getSlot(), Architecture::getSpaceBySpacebase(), Heritage::guardCallOverlappingInput(), Heritage::guardCalls(), Heritage::guardInput(), Heritage::guardLoads(), FuncCallSpecs::hasEffectTranslate(), ToOpEdge::hash(), RangeList::inRange(), Varnode::intersects(), LoadGuard::isGuarded(), ParamEntry::justifiedContain(), Funcdata::linkSymbolReference(), RawLoadImage::loadFill(), RangeList::longestFit(), Funcdata::mapGlobals(), ScopeLocal::markUnaliased(), Sleigh::oneInstruction(), LoadImageXml::pad(), ParamEntry::ParamEntry(), print_data(), Varnode::printRawNoMarkup(), ActionInferTypes::propagateRef(), ScopeLocal::remapSymbol(), ScopeLocal::remapSymbolDynamic(), AddrSpaceManager::renormalizeJoinAddress(), FuncProto::resolveExtraPop(), FuncCallSpecs::resolveSpacebaseRelative(), TrackedContext::restoreXml(), ParamEntry::restoreXml(), SegmentOp::restoreXml(), JumpBasic::sanityCheck(), JumpTable::sanityCheck(), ContextInternal::saveContext(), ContextDatabase::saveTracked(), Comment::saveXml(), SeqNum::saveXml(), Varnode::saveXml(), JumpBasicOverride::saveXml(), Database::saveXml(), FspecSpace::saveXmlAttributes(), ContextCache::setContext(), BlockBasic::setInitialRange(), Funcdata::spacebaseConstant(), Heritage::splitByRefinement(), Heritage::splitPieces(), Funcdata::syncVarnodesWithSymbols(), FuncProto::unjustifiedInputParam(), and Varnode::Varnode().
char Address::getShortcut (void) const inline
Get the shortcut character for the address space.
Each address has a shortcut character associated with it for use with the read and printRaw methods.
Returns
the shortcut char
References base, and AddrSpace::getShortcut().
Referenced by PrintC::emitLabel(), ArchitectureGhidra::getBytes(), FlowInfo::handleOutOfBounds(), RawLoadImage::loadFill(), GhidraTranslate::oneInstruction(), SymbolEntry::printEntry(), IopSpace::printRaw(), Varnode::printRawNoMarkup(), and VarnodeBank::setDef().
AddrSpace * Address::getSpace (void) const inline
Get the address space.
Get the address space associated with this address.
Returns
the AddressSpace pointer, or NULL if invalid
References base.
Referenced by Scope::addDynamicSymbol(), ScopeGhidraNamespace::addMapInternal(), ScopeInternal::addMapInternal(), Scope::addMapPoint(), ActionDeindirect::apply(), ActionRestrictLocal::apply(), RulePiecePathology::applyOp(), JumpBasic::buildAddresses(), JumpAssisted::buildAddresses(), FuncCallSpecs::buildParam(), ScopeLocal::buildVariableName(), ScopeInternal::buildVariableName(), ParamListStandard::characterizeAsParam(), Varnode::characterizeOverlap(), Funcdata::checkForLanedRegister(), Heritage::collect(), FuncCallSpecs::commitNewInputs(), FuncCallSpecs::commitNewOutputs(), AddrSpaceManager::constructFloatExtensionAddress(), AddrSpaceManager::constructJoinAddress(), ParamEntry::containedBy(), Range::contains(), Varnode::contains(), ScopeGhidra::dump2Cache(), EffectRecord::EffectRecord(), PrintC::emitLabel(), PrintLanguage::emitLineComment(), VarnodeBank::endLoc(), SymbolEntry::EntrySubsort::EntrySubsort(), ScopeLocal::fakeInputSymbols(), ScopeInternal::findAddr(), ScopeInternal::findClosestFit(), ScopeInternal::findCodeLabel(), ScopeInternal::findContainer(), VarnodeBank::findCoveredInput(), VarnodeBank::findCoveringInput(), ParamListStandard::findEntry(), ScopeInternal::findExternalRef(), ScopeInternal::findFunction(), ScopeInternal::findOverlap(), FlowInfo::findRelTarget(), FuncCallSpecs::FuncCallSpecs(), ActionFuncLink::funcLinkInput(), FuncProto::getBiggestContainedInputParam(), ParamListStandard::getBiggestContainedParam(), ContextInternal::getContext(), ContextCache::getContext(), TypeOpCallind::getInputLocal(), TypeOpIndirect::getInputLocal(), Symbol::getMapEntry(), GhidraTranslate::getRegister(), Varnode::getSpace(), Architecture::getSpaceBySpacebase(), Heritage::guardCalls(), Heritage::guardInput(), Heritage::guardLoads(), Heritage::guardStores(), FuncCallSpecs::hasEffectTranslate(), Architecture::highPtrPossible(), Funcdata::inlineFlow(), RangeList::inRange(), Varnode::intersects(), LoadGuard::isGuarded(), ParamEntry::justifiedContain(), RangeList::longestFit(), ProtoModel::lookupEffect(), LoadImageXml::pad(), ParamEntry::ParamEntry(), Heritage::placeMultiequals(), Varnode::printRawNoMarkup(), ActionInferTypes::propagateRef(), PrintC::pushPartialSymbol(), PrintC::pushUnnamedLocation(), ParamActive::registerTrial(), FlowInfo::reinterpreted(), ScopeLocal::remapSymbol(), ScopeLocal::remapSymbolDynamic(), ScopeGhidra::removeQuery(), Funcdata::removeUnreachableBlocks(), FuncCallSpecs::resolveSpacebaseRelative(), TrackedContext::restoreXml(), ParamEntry::restoreXml(), SegmentOp::restoreXml(), ScopeInternal::restoreXml(), ContextInternal::saveContext(), ContextDatabase::saveTracked(), Comment::saveXml(), SeqNum::saveXml(), Varnode::saveXml(), JumpBasicOverride::saveXml(), Database::saveXml(), FspecSpace::saveXmlAttributes(), ContextCache::setContext(), EmulateFunction::setExecuteAddress(), BlockBasic::setInitialRange(), Funcdata::spacebaseConstant(), Heritage::splitByRefinement(), Funcdata::startProcessing(), FlowInfo::target(), FuncCallSpecs::transferLockedInputParam(), JumpBasicOverride::trialNorm(), FuncProto::unjustifiedInputParam(), and Varnode::Varnode().
AddrSpace * Address::getSpaceFromConst (const Address & addr) inline static
Recover an encoded address space from an address.
In LOAD and STORE instructions, the particular address space being read/written is encoded as a constant input parameter to the instruction. Internally, this constant is the actual pointer to the AddrSpace. This function allows the encoded pointer to be recovered from the address it is encoded in.
Parameters
addr is the Address encoding the pointer
Returns
the AddrSpace pointer
References offset.
Referenced by RuleDoubleIn::applyOp(), RuleSegment::applyOp(), RulePtrFlow::applyOp(), LaneDivide::buildLoad(), LaneDivide::buildStore(), RuleLoadVarnode::checkSpacebase(), EmulatePcodeOp::executeLoad(), EmulateFunction::executeLoad(), EmulateSnippet::executeLoad(), EmulateMemory::executeLoad(), EmulatePcodeOp::executeSegmentOp(), EmulateMemory::executeStore(), TypeOpLoad::getInputCast(), TypeOpStore::getInputCast(), Heritage::guardStores(), TypeOpLoad::printRaw(), TypeOpStore::printRaw(), TypeOpSegment::printRaw(), ActionInferTypes::propagateTypeEdge(), PcodeOp::saveXml(), and ActionConstantPtr::searchForLoadStore().
bool Address::isBigEndian (void) const inline
Is data at this address big endian encoded.
Determine if data stored at this address is big endian encoded.
Returns
true if the address is big endian
References base, and AddrSpace::isBigEndian().
Referenced by Scope::addMap(), RuleLeftRight::applyOp(), Heritage::concatPieces(), AddrSpaceManager::constructJoinAddress(), SubvariableFlow::getReplacementAddress(), Heritage::normalizeWriteSize(), Heritage::splitPieces(), and RulePtrFlow::truncatePointer().
bool Address::isConstant (void) const inline
Is this a constant value.
Determine if this address is from the constant space. All constant values are represented as an offset into the constant space.
Returns
true if this address represents a constant
References base, AddrSpace::getType(), and IPTR_CONSTANT.
Referenced by Scope::discoverScope(), Scope::stackAddr(), Scope::stackClosestFit(), Scope::stackCodeLabel(), Scope::stackContainer(), Scope::stackExternalRef(), and Scope::stackFunction().
bool Address::isContiguous (int4 sz, const Address & loaddr, int4 losz) const
Does this form a contigous range with loaddr.
Does the location this, sz form a contiguous region to loaddr, losz, where this forms the most significant piece of the logical whole
Parameters
sz is the size of this hi region
loaddr is the starting address of the low region
losz is the size of the low region
Returns
true if the pieces form a contiguous whole
References base, and offset.
Referenced by ParamListStandard::checkJoin(), and AddrSpaceManager::constructJoinAddress().
bool Address::isInvalid (void) const inline
Is the address invalid?
Determine if this is an invalid address. This only detects deliberate invalid addresses.
Returns
true if the address is invalid
References base.
Referenced by Scope::addDynamicSymbol(), Scope::addMap(), Scope::addMapPoint(), ParamListStandard::assignAddress(), Scope::buildDefaultName(), FuncCallSpecs::countMatchingCalls(), ScopeInternal::findAddr(), ScopeInternal::findClosestFit(), ScopeInternal::findContainer(), Funcdata::findLinkedVarnode(), ContextInternal::getRegionForSet(), FlowInfo::inlineClone(), RangeList::inRange(), SymbolEntry::inUse(), SymbolEntry::isDynamic(), SymbolEntry::isInvalid(), ActionConstantPtr::isPointer(), Funcdata::linkSymbolReference(), RangeList::longestFit(), SymbolEntry::printEntry(), PrintC::pushPtrCharConstant(), FlowInfo::queryCall(), ScopeLocal::remapSymbol(), ScopeLocal::remapSymbolDynamic(), AddrSpaceManager::renormalizeJoinAddress(), ContextInternal::restoreContext(), Override::restoreXml(), FuncProto::restoreXml(), SymbolEntry::saveXml(), FspecSpace::saveXmlAttributes(), Database::setPropertyRange(), FlowInfo::setupCallindSpecs(), and FlowInfo::target().
bool Address::isJoin (void) const inline
Is this a join value.
Determine if this address represents a set of joined memory locations.
Returns
true if this address represents a join
References base, AddrSpace::getType(), and IPTR_JOIN.
Referenced by Scope::addMap(), and RulePullsubMulti::buildSubpiece().
int4 Address::justifiedContain (int4 sz, const Address & op2, int4 sz2, bool forceleft) const
Determine if op2 is the least significant part of this.
Return -1 if (op2,sz2) is not properly contained in (this,sz). If it is contained, return the endian aware offset of (op2,sz2) I.e. if the least significant byte of the op2 range falls on the least significant byte of the this range, return 0. If it intersects the second least significant, return 1, etc. The -forceleft- toggle causes the check to be made against the left (lowest address) side of the container, regardless of the endianness. I.e. it forces a little endian interpretation.
Parameters
sz is the size of this range
op2 is the address of the second range
sz2 is the size of the second range
forceleft is true if containments is forced to be on the left even for big endian
Returns
the endian aware offset, or -1
References base, and offset.
Referenced by Funcdata::adjustInputVarnodes(), FuncProto::characterizeAsInputParam(), Heritage::guardCallOverlappingInput(), ParamEntry::justifiedContain(), FuncProto::possibleInputParam(), FuncProto::possibleOutputParam(), FuncCallSpecs::transferLockedOutputParam(), and FuncProto::unjustifiedInputParam().
bool Address::operator!= (const Address & op2) const inline
Compare two addresses for inequality.
Check if two addresses are not equal. I.e. if either their address space or offset are different.
Parameters
op2 is the address to compare to this
Returns
true if the addresses are different
Address Address::operator+ (int4 off) const inline
Increment address by a number of bytes.
Add an integer value to the offset portion of the address. The addition takes into account the size of the address space, and the Address will wrap around if necessary.
Parameters
off is the number to add to the offset
Returns
the new incremented address
References Address(), base, offset, and AddrSpace::wrapOffset().
Address Address::operator- (int4 off) const inline
Decrement address by a number of bytes.
Subtract an integer value from the offset portion of the address. The subtraction takes into account the size of the address space, and the Address will wrap around if necessary.
Parameters
off is the number to subtract from the offset
Returns
the new decremented address
References Address(), base, offset, and AddrSpace::wrapOffset().
bool Address::operator< (const Address & op2) const inline
Compare two addresses via their natural ordering.
Do an ordering comparison of two addresses. Addresses are sorted first on space, then on offset. So two addresses in the same space compare naturally based on their offset, but addresses in different spaces also compare. Different spaces are ordered by their index.
Parameters
op2 is the address to compare to
Returns
true if this comes before op2
References base, AddrSpace::getIndex(), and offset.
bool Address::operator<= (const Address & op2) const inline
Compare two addresses via their natural ordering.
Do an ordering comparison of two addresses.
Parameters
op2 is the address to compare to
Returns
true if this comes before or is equal to op2
References base, AddrSpace::getIndex(), and offset.
Address & Address::operator= (const Address & op2) inline
Copy an address.
This is a standard assignment operator, copying the address space pointer and the offset
Parameters
op2 is the Address being assigned
Returns
a reference to altered address
References base, and offset.
bool Address::operator== (const Address & op2) const inline
Compare two addresses for equality.
Check if two addresses are equal. I.e. if their address space and offset are the same.
Parameters
op2 is the address to compare to this
Returns
true if the addresses are the same
References base, and offset.
int4 Address::overlap (int4 skip, const Address & op, int4 size) const
Determine how two address ranges overlap.
If this + skip falls in the range op to op + size, then a non-negative integer is returned indicating where in the interval it falls. I.e. if this + skip == op, then 0 is returned. Otherwise -1 is returned.
Parameters
skip is an adjust to this address
op is the start of the range to check
size is the size of the range
Returns
an integer indicating how overlap occurs
References base, IPTR_CONSTANT, and offset.
Referenced by LocationMap::add(), LocationMap::find(), LocationMap::findPass(), ParamEntry::getContainer(), LoadImageXml::loadFill(), ProtoModel::lookupEffect(), HighVariable::setSymbol(), and ParamActive::whichTrial().
void Address::printRaw (ostream & s) const inline
Write a raw version of the address to a stream.
Write a short-hand or debug version of this address to a stream.
Parameters
s is the stream being written
References base, offset, and AddrSpace::printRaw().
Referenced by AddTreeState::apply(), ActionSegmentize::apply(), RuleSwitchSingle::applyOp(), FlowInfo::checkContainedCall(), PrintC::emitLabel(), Funcdata::fillinReadOnly(), FlowInfo::findRelTarget(), PrintC::genericFunctionName(), ArchitectureGhidra::getBytes(), FlowInfo::handleOutOfBounds(), Heritage::heritage(), LoadImageXml::loadFill(), RawLoadImage::loadFill(), Architecture::nameFunction(), GhidraTranslate::oneInstruction(), SymbolEntry::printEntry(), IopSpace::printRaw(), FspecSpace::printRaw(), Varnode::printRawNoMarkup(), PrintC::pushUnnamedLocation(), FlowInfo::reinterpreted(), Funcdata::removeUnreachableBlocks(), Funcdata::stageJumpTable(), and FlowInfo::target().
int4 Address::read (const string & s) inline
Read in the address from a string.
Convert a string into an address. The string format can be tailored for the particular address space.
Parameters
s is the string to parse
Returns
any size associated with the parsed string
References base, offset, and AddrSpace::read().
void Address::renormalize (int4 size)
Make sure there is a backing JoinRecord if this is in the join space.
If this is (originally) a join address, reevaluate it in terms of its new offset and siz, changing the space and offset if necessary.
Parameters
size is the new size in bytes of the underlying object
References IPTR_JOIN.
Referenced by RulePullsubMulti::applyOp(), RuleLeftRight::applyOp(), RulePullsubMulti::buildSubpiece(), TransformVar::createReplacement(), SubvariableFlow::getReplacementAddress(), and RulePtrFlow::truncatePointer().
Address Address::restoreXml (const Element * el, const AddrSpaceManager * manage) static
Restore an address from parsed XML.
This is usually used to build an address from an <addr> tag, but it can be used to create an address from any tag with the appropriate attributes
space indicates the address space of the tag
offset indicates the offset within the space
or a name attribute can be used to recover an address based on a register name.
Parameters
el is the parsed tag
manage is the address space manager for the program
Returns
the resulting Address
References VarnodeData::offset, VarnodeData::restoreXml(), and VarnodeData::space.
Referenced by ScopeGhidra::dump2Cache(), GhidraTranslate::getRegister(), DecompileAt::loadParameters(), RangeList::numRanges(), SeqNum::operator<(), Range::operator<(), Architecture::restoreFlowOverride(), LoadTable::restoreXml(), StringManager::restoreXml(), Comment::restoreXml(), TrackedContext::restoreXml(), Override::restoreXml(), ParamEntry::restoreXml(), SymbolEntry::restoreXml(), SeqNum::restoreXml(), Funcdata::restoreXml(), SegmentOp::restoreXml(), ContextInternal::restoreXml(), ExternRefSymbol::restoreXml(), JumpBasicOverride::restoreXml(), JumpTable::restoreXml(), Database::restoreXml(), ProtoStoreInternal::restoreXml(), FuncProto::restoreXml(), and PcodeEmit::restoreXmlOp().
Address Address::restoreXml (const Element * el, const AddrSpaceManager * manage, int4 & size) static
Restore an address and size from parsed XML.
This is usually used to build an address from an <addr> tag, but it can be used to create an address from any tag with the appropriate attributes
space indicates the address space of the tag
offset indicates the offset within the space
size indicates the size of an address range
or a name attribute can be used to recover an address and size based on a register name. If a size is recovered it is stored in size reference.
Parameters
el is the parsed tag
manage is the address space manager for the program
size is the reference to any recovered size
Returns
the resulting Address
References VarnodeData::offset, VarnodeData::restoreXml(), VarnodeData::size, and VarnodeData::space.
void Address::saveXml (ostream & s) const inline
Save this to a stream as an XML tag.
Save an <addr> tag corresponding to this address to a stream. The exact format is determined by the address space, but this generally has a space and an offset attribute.
Parameters
s is the stream being written to
References base, offset, and AddrSpace::saveXmlAttributes().
Referenced by ArchitectureGhidra::getBytes(), ArchitectureGhidra::getCodeLabel(), ArchitectureGhidra::getComments(), ArchitectureGhidra::getExternalRefXML(), ArchitectureGhidra::getMappedSymbolsXML(), ArchitectureGhidra::getPcodePacked(), ArchitectureGhidra::getRegisterName(), ArchitectureGhidra::getTrackedRegisters(), RangeList::numRanges(), SeqNum::operator<(), Range::operator<(), InjectContextGhidra::saveXml(), LoadTable::saveXml(), SymbolEntry::saveXml(), Funcdata::saveXml(), ExternRefSymbol::saveXml(), EffectRecord::saveXml(), JumpTable::saveXml(), ProtoStoreInternal::saveXml(), and FuncProto::saveXml().
void Address::saveXml (ostream & s, int4 size) const inline
Save this and a size to a stream as an XML tag.
Save an <addr> tag corresponding to this address to a stream. The tag will also include an extra size attribute so that it can describe an entire memory range.
Parameters
s is the stream being written to
size is the number of bytes in the range
References base, offset, and AddrSpace::saveXmlAttributes().
void Address::toPhysical (void)
Convert this to a physical address.
Deprecated:
Convert this to the most basic physical address. This routine is only present for backward compatibility with SLED
References AddrSpace::getContain(), and IPTR_SPACEBASE.
Referenced by DecompileAt::loadParameters().
Friends And Related Function Documentation
ostream& operator<< (ostream & s, const Address & addr) friend
Write out an address to stream.
This allows an Address to be written to a stream using the standard '<<' operator. This is a wrapper for the printRaw method and is intended for debugging and console mode uses.
Parameters
s is the stream being written to
addr is the Address to write
Returns
the output stream
Referenced by SeqNum::operator<().
The documentation for this class was generated from the following files:
address.hh
address.cc