decompiler: ParamListRegister Class Reference
ParamListRegister Class Reference
An unstructured model for passing input parameters to a function.
#include <fspec.hh>
Public Member Functions
ParamListRegister (void)
Constructor for use with restoreXml()
ParamListRegister (const ParamListRegister &op2)
Copy constructor.
virtual uint4 getType (void) const
Get the type of parameter list.
virtual void fillinMap (ParamActive *active) const
Given an unordered list of storage locations, calculate a function prototype.
virtual ParamList * clone (void) const
Clone this parameter list model.
Public Member Functions inherited from ParamListStandard
ParamListStandard (void)
Construct for use with restoreXml()
ParamListStandard (const ParamListStandard &op2)
Copy constructor.
const list< ParamEntry > & getEntry (void) const
Get the list of parameter entries.
virtual void assignMap (const vector< Datatype * > &proto, bool isinput, TypeFactory &typefactory, vector< ParameterPieces > &res) const
Given list of data-types, map the list positions to storage locations.
virtual bool checkJoin (const Address &hiaddr, int4 hisize, const Address &loaddr, int4 losize) const
Check if the given two storage locations can represent a single logical parameter.
virtual bool checkSplit (const Address &loc, int4 size, int4 splitpoint) const
Check if it makes sense to split a single storage location into two parameters.
virtual int4 characterizeAsParam (const Address &loc, int4 size) const
Characterize whether the given range overlaps parameter storage.
virtual bool possibleParam (const Address &loc, int4 size) const
Does the given storage location make sense as a parameter.
virtual bool possibleParamWithSlot (const Address &loc, int4 size, int4 &slot, int4 &slotsize) const
Pass-back the slot and slot size for the given storage location as a parameter.
virtual bool getBiggestContainedParam (const Address &loc, int4 size, VarnodeData &res) const
Pass-back the biggest parameter contained within the given range.
virtual bool unjustifiedContainer (const Address &loc, int4 size, VarnodeData &res) const
Check if the given storage location looks like an unjustified parameter.
virtual OpCode assumedExtension (const Address &addr, int4 size, VarnodeData &res) const
Get the type of extension and containing parameter for the given storage.
virtual AddrSpace * getSpacebase (void) const
Get the address space associated with any stack based parameters in this list.
virtual void getRangeList (AddrSpace *spc, RangeList &res) const
For a given address space, collect all the parameter locations within that space.
virtual int4 getMaxDelay (void) const
Return the maximum heritage delay across all possible parameters.
virtual void restoreXml (const Element *el, const AddrSpaceManager *manage, vector< EffectRecord > &effectlist, bool normalstack)
Restore the model from an XML stream.
Public Member Functions inherited from ParamList
virtual ~ParamList (void)
Destructor.
Additional Inherited Members
Public Types inherited from ParamList
enum { p_standard, p_standard_out, p_register, p_merged }
Protected Member Functions inherited from ParamListStandard
const ParamEntry * findEntry (const Address &loc, int4 size) const
Given storage location find matching ParamEntry.
Address assignAddress (const Datatype *tp, vector< int4 > &status) const
Assign storage for given parameter data-type.
void buildTrialMap (ParamActive *active) const
Build map from parameter trials to model ParamEntrys.
void separateFloat (ParamActive *active, int4 &floatstart, int4 &floatstop, int4 &start, int4 &stop) const
Calculate the range of floating-point entries within a given set of parameter trials.
void forceExclusionGroup (ParamActive *active) const
Enforce exclusion rules for the given set of parameter trials.
void forceNoUse (ParamActive *active, int4 start, int4 stop) const
Mark every trial above the first "definitely not used" as inactive.
void forceInactiveChain (ParamActive *active, int4 maxchain, int4 start, int4 stop) const
Enforce rules about chains of inactive slots.
void calcDelay (void)
Calculate the maximum heritage delay for any potential parameter in this list.
void populateResolver (void)
Build the ParamEntry resolver maps.
Protected Attributes inherited from ParamListStandard
int4 numgroup
Number of groups in this parameter convention.
int4 maxdelay
Maximum heritage delay across all parameters.
int4 pointermax
If non-zero, maximum size of a data-type before converting to a pointer.
bool thisbeforeret
Does a this parameter come before a hidden return parameter.
int4 nonfloatgroup
Group of first entry which is not marked float.
list< ParamEntry > entry
The ordered list of parameter entries.
vector< ParamEntryResolver * > resolverMap
Map from space id to resolver.
AddrSpace * spacebase
Address space containing relative offset parameters.
Detailed Description
An unstructured model for passing input parameters to a function.
This is the register model, meaning a collection of registers, any of which can be used to pass a parameter. This is nearly identical to ParamListStandard, but rules banning holes are not enforced, any subset of the resource list can be used. This makes sense for executables where parameters follow no conventions or only loose conventions. The assignMap() method may make less sense in this scenario.
Member Function Documentation
void ParamListRegister::fillinMap (ParamActive * active) const virtual
Given an unordered list of storage locations, calculate a function prototype.
A list of input (or output) trials is given, which may have holes, invalid inputs etc. Decide on the formal ordered parameter list. Trials within the ParamActive are added, removed, or reordered as needed.
Parameters
active is the given list of trials
Reimplemented from ParamListStandard.
References ParamActive::getNumTrials(), ParamActive::getTrial(), and ParamActive::sortTrials().
The documentation for this class was generated from the following files:
fspec.hh
fspec.cc