decompiler: RulePtrFlow Class Reference
RulePtrFlow Class Reference
Mark Varnode and PcodeOp objects that are carrying or operating on pointers.
Public Member Functions
RulePtrFlow (const string &g, Architecture *conf)
Constructor.
virtual Rule * clone (const ActionGroupList &grouplist) const
Clone the Rule.
virtual void getOpList (vector< uint4 > &oplist) const
List of op codes this rule operates on.
virtual int4 applyOp (PcodeOp *op, Funcdata &data)
Attempt to apply this Rule.
Public Member Functions inherited from Rule
Rule (const string &g, uint4 fl, const string &nm)
Construct given group, properties name.
virtual ~Rule (void)
Destructor.
const string & getName (void) const
Return the name of this Rule.
const string & getGroup (void) const
Return the group this Rule belongs to.
uint4 getNumTests (void)
Get number of attempted applications.
uint4 getNumApply (void)
Get number of successful applications.
void setBreak (uint4 tp)
Set a breakpoint on this Rule.
void clearBreak (uint4 tp)
Clear a breakpoint on this Rule.
void clearBreakPoints (void)
Clear all breakpoints on this Rule.
void turnOnWarnings (void)
Enable warnings for this Rule.
void turnOffWarnings (void)
Disable warnings for this Rule.
bool isDisabled (void) const
Return true if this Rule is disabled.
void setDisable (void)
Disable this Rule (within its pool)
void clearDisable (void)
Enable this Rule (within its pool)
bool checkActionBreak (void)
Check if an action breakpoint is turned on.
uint4 getBreakPoint (void) const
Return breakpoint toggles.
virtual void reset (Funcdata &data)
Reset this Rule.
virtual void resetStats (void)
Reset Rule statistics.
virtual void printStatistics (ostream &s) const
Print statistics for this Rule.
Private Member Functions
bool trialSetPtrFlow (PcodeOp *op)
bool propagateFlowToDef (Varnode *vn)
Propagate ptrflow property to given Varnode and the defining PcodeOp.
bool propagateFlowToReads (Varnode *vn)
Propagate ptrflow property to given Varnode and to descendant PcodeOps.
Varnode * truncatePointer (AddrSpace *spc, PcodeOp *op, Varnode *vn, int4 slot, Funcdata &data)
Truncate pointer Varnode being read by given PcodeOp.
Private Attributes
Architecture * glb
The address space manager.
bool hasTruncations
true if this architecture needs truncated pointers
Additional Inherited Members
Public Types inherited from Rule
enum typeflags { type_disable = 1, rule_debug = 2, warnings_on = 4, warnings_given = 8 }
Properties associated with a Rule.
Detailed Description
Mark Varnode and PcodeOp objects that are carrying or operating on pointers.
This is used on architectures where the data-flow for pointer values needs to be truncated. This marks the places where the truncation needs to happen. Then the SubvariableFlow actions do the actual truncation.
Member Function Documentation
int4 RulePtrFlow::applyOp (PcodeOp * op, Funcdata & data) virtual
Attempt to apply this Rule.
This method contains the main logic for applying the Rule. It must use a given PcodeOp as the point at which the Rule applies. If it does apply, changes are made directly to the function and 1 (non-zero) is returned, otherwise 0 is returned.
Parameters
op is the given PcodeOp where the Rule may apply
data is the function to which to apply
Reimplemented from Rule.
References PcodeOp::code(), CPUI_BRANCHIND, CPUI_CALLIND, CPUI_COPY, CPUI_INDIRECT, CPUI_INT_ADD, CPUI_LOAD, CPUI_MULTIEQUAL, CPUI_NEW, CPUI_PTRADD, CPUI_PTRSUB, CPUI_STORE, Varnode::getAddr(), AddrSpace::getAddrSize(), Funcdata::getArch(), AddrSpaceManager::getDefaultCodeSpace(), PcodeOp::getIn(), PcodeOp::getOut(), Varnode::getSize(), Address::getSpaceFromConst(), PcodeOp::isPtrFlow(), PcodeOp::numInput(), propagateFlowToDef(), propagateFlowToReads(), and truncatePointer().
virtual Rule* RulePtrFlow::clone (const ActionGroupList & grouplist) const inline virtual
Clone the Rule.
If this Rule is a member of one of the groups in the grouplist, this returns a clone of the Rule, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Rule or NULL
Implements Rule.
References ActionGroupList::contains(), and AddTreeState::data.
void RulePtrFlow::getOpList (vector< uint4 > & oplist) const virtual
List of op codes this rule operates on.
Populate the given array with all possible OpCodes this Rule might apply to. By default, this method returns all possible OpCodes
Parameters
oplist is the array to populate
Reimplemented from Rule.
References CPUI_BRANCHIND, CPUI_CALLIND, CPUI_COPY, CPUI_INDIRECT, CPUI_INT_ADD, CPUI_LOAD, CPUI_MULTIEQUAL, CPUI_PTRADD, CPUI_PTRSUB, CPUI_STORE, and hasTruncations.
bool RulePtrFlow::propagateFlowToDef (Varnode * vn) private
Propagate ptrflow property to given Varnode and the defining PcodeOp.
Parameters
vn is the given Varnode
Returns
true if a change was made
References Varnode::getDef(), Varnode::isPtrFlow(), Varnode::isWritten(), Varnode::setPtrFlow(), and trialSetPtrFlow().
Referenced by applyOp().
bool RulePtrFlow::propagateFlowToReads (Varnode * vn) private
Propagate ptrflow property to given Varnode and to descendant PcodeOps.
Parameters
vn is the given Varnode
Returns
true if a change was made
References Varnode::beginDescend(), Varnode::endDescend(), Varnode::isPtrFlow(), Varnode::setPtrFlow(), and trialSetPtrFlow().
Referenced by applyOp().
bool RulePtrFlow::trialSetPtrFlow (PcodeOp * op) private
Set ptrflow property on PcodeOp only if it is propagating
Parameters
op is the PcodeOp
Returns
true if ptrflow property is newly set
References PcodeOp::code(), CPUI_COPY, CPUI_INDIRECT, CPUI_INT_ADD, CPUI_MULTIEQUAL, CPUI_PTRADD, CPUI_PTRSUB, PcodeOp::isPtrFlow(), and PcodeOp::setPtrFlow().
Referenced by propagateFlowToDef(), and propagateFlowToReads().
Varnode * RulePtrFlow::truncatePointer (AddrSpace * spc, PcodeOp * op, Varnode * vn, int4 slot, Funcdata & data) private
Truncate pointer Varnode being read by given PcodeOp.
Insert a SUBPIECE operation truncating the value to the size necessary for a pointer into the given address space. Update the PcodeOp input.
Parameters
spc is the given address space
op is the given PcodeOp reading the pointer
vn is the pointer Varnode
slot is the input slot reading the pointer
data is the function being analyzed
Returns
the new truncated Varnode
References CPUI_SUBPIECE, PcodeOp::getAddr(), Varnode::getAddr(), AddrSpace::getAddrSize(), Varnode::getSize(), Varnode::getSpace(), AddrSpace::getType(), IPTR_INTERNAL, Address::isBigEndian(), Funcdata::newConstant(), Funcdata::newOp(), Funcdata::newUniqueOut(), Funcdata::newVarnodeOut(), Funcdata::opInsertBefore(), Funcdata::opSetInput(), Funcdata::opSetOpcode(), and Address::renormalize().
Referenced by applyOp().
The documentation for this class was generated from the following files:
ruleaction.hh
ruleaction.cc