decompiler: PcodeOpBank Class Reference
PcodeOpBank Class Reference
Container class for PcodeOps associated with a single function.
#include <op.hh>
Public Member Functions
void clear (void)
Clear all PcodeOps from this container.
PcodeOpBank (void)
Constructor.
~PcodeOpBank (void)
Destructor.
void setUniqId (uintm val)
Set the unique id counter.
uintm getUniqId (void) const
Get the next unique id.
PcodeOp * create (int4 inputs, const Address &pc)
Create a PcodeOp with at a given Address.
PcodeOp * create (int4 inputs, const SeqNum &sq)
Create a PcodeOp with a given sequence number.
void destroy (PcodeOp *op)
Destroy/retire the given PcodeOp.
void destroyDead (void)
Destroy/retire all PcodeOps in the dead list.
void changeOpcode (PcodeOp *op, TypeOp *newopc)
Change the op-code for the given PcodeOp.
void markAlive (PcodeOp *op)
Mark the given PcodeOp as alive.
void markDead (PcodeOp *op)
Mark the given PcodeOp as dead.
void insertAfterDead (PcodeOp *op, PcodeOp *prev)
Insert the given PcodeOp after a point in the dead list.
void moveSequenceDead (PcodeOp *firstop, PcodeOp *lastop, PcodeOp *prev)
Move a sequence of PcodeOps to a point in the dead list.
void markIncidentalCopy (PcodeOp *firstop, PcodeOp *lastop)
Mark any COPY ops in the given range as incidental.
bool empty (void) const
Return true if there are no PcodeOps in this container.
PcodeOp * target (const Address &addr) const
Find the first executing PcodeOp for a target address.
PcodeOp * findOp (const SeqNum &num) const
Find a PcodeOp by sequence number.
PcodeOp * fallthru (const PcodeOp *op) const
Find the PcodeOp considered a fallthru of the given PcodeOp.
PcodeOpTree::const_iterator beginAll (void) const
Start of all PcodeOps in sequence number order.
PcodeOpTree::const_iterator endAll (void) const
End of all PcodeOps in sequence number order.
PcodeOpTree::const_iterator begin (const Address &addr) const
Start of all PcodeOps at one Address.
PcodeOpTree::const_iterator end (const Address &addr) const
End of all PcodeOps at one Address.
list< PcodeOp * >::const_iterator beginAlive (void) const
Start of all PcodeOps marked as alive.
list< PcodeOp * >::const_iterator endAlive (void) const
End of all PcodeOps marked as alive.
list< PcodeOp * >::const_iterator beginDead (void) const
Start of all PcodeOps marked as dead.
list< PcodeOp * >::const_iterator endDead (void) const
End of all PcodeOps marked as dead.
list< PcodeOp * >::const_iterator begin (OpCode opc) const
Start of all PcodeOps sharing the given op-code.
list< PcodeOp * >::const_iterator end (OpCode opc) const
End of all PcodeOps sharing the given op-code.
Private Member Functions
void addToCodeList (PcodeOp *op)
Add given PcodeOp to specific op-code list.
void removeFromCodeList (PcodeOp *op)
Remove given PcodeOp from specific op-code list.
void clearCodeLists (void)
Clear all op-code specific lists.
Private Attributes
PcodeOpTree optree
The main sequence number sort.
list< PcodeOp * > deadlist
List of dead PcodeOps.
list< PcodeOp * > alivelist
List of alive PcodeOps.
list< PcodeOp * > storelist
List of STORE PcodeOps.
list< PcodeOp * > loadlist
list of LOAD PcodeOps
list< PcodeOp * > returnlist
List of RETURN PcodeOps.
list< PcodeOp * > useroplist
List of user-defined PcodeOps.
list< PcodeOp * > deadandgone
List of retired PcodeOps.
uintm uniqid
Counter for producing unique id's for each op.
Detailed Description
Container class for PcodeOps associated with a single function.
The PcodeOp objects are maintained under multiple different sorting criteria to facilitate quick access in various situations. The main sort (PcodeOpTree) is by sequence number (SeqNum). PcodeOps are also grouped into alive and dead lists to distinguish between raw p-code ops and those that are fully linked into control-flow. Several lists group PcodeOps with important op-codes (like STORE and RETURN).
Member Function Documentation
void PcodeOpBank::addToCodeList (PcodeOp * op) private
Add given PcodeOp to specific op-code list.
Add the PcodeOp to the list of ops with the same op-code. Currently only certain op-codes have a dedicated list.
Parameters
op is the given PcodeOp
References PcodeOp::code(), PcodeOp::codeiter, CPUI_CALLOTHER, CPUI_LOAD, CPUI_RETURN, and CPUI_STORE.
void PcodeOpBank::changeOpcode (PcodeOp * op, TypeOp * newopc)
Change the op-code for the given PcodeOp.
The PcodeOp is assigned the new op-code, which may involve moving it between the internal op-code specific lists.
Parameters
op is the given PcodeOp to change
newopc is the new op-code object
References PcodeOp::opcode, and PcodeOp::setOpcode().
Referenced by Funcdata::opSetOpcode().
PcodeOp * PcodeOpBank::create (int4 inputs, const Address & pc)
Create a PcodeOp with at a given Address.
A new PcodeOp is allocated with the indicated number of input slots, which start out empty. A sequence number is assigned, and the op is added to the end of the dead list.
Parameters
inputs is the number of input slots
pc is the Address to associate with the PcodeOp
Returns
the newly allocated PcodeOp
References PcodeOp::dead, PcodeOp::getSeqNum(), PcodeOp::insertiter, PcodeOp::PcodeOp(), and PcodeOp::setFlag().
Referenced by Funcdata::newOp().
PcodeOp * PcodeOpBank::create (int4 inputs, const SeqNum & sq)
Create a PcodeOp with a given sequence number.
A new PcodeOp is allocated with the indicated number of input slots and the specific sequence number, suitable for cloning and restoring from XML. The op is added to the end of the dead list.
Parameters
inputs is the number of input slots
sq is the specified sequence number
Returns
the newly allocated PcodeOp
References PcodeOp::dead, PcodeOp::getSeqNum(), SeqNum::getTime(), PcodeOp::insertiter, PcodeOp::PcodeOp(), and PcodeOp::setFlag().
void PcodeOpBank::destroy (PcodeOp * op)
Destroy/retire the given PcodeOp.
The given PcodeOp is removed from all internal lists and added to a final deadandgone list. The memory is not reclaimed until the whole container is destroyed, in case pointer references still exist. These will all still be marked as dead.
Parameters
op is the given PcodeOp to destroy
References PcodeOp::getSeqNum(), PcodeOp::insertiter, and PcodeOp::isDead().
Referenced by Funcdata::opDeadAndGone(), and Funcdata::opDestroyRaw().
PcodeOp * PcodeOpBank::fallthru (const PcodeOp * op) const
Find the PcodeOp considered a fallthru of the given PcodeOp.
The term fallthru in this context refers to p-code not assembly instructions.
Parameters
op is the given PcodeOp
Returns
the fallthru PcodeOp
References PcodeOp::getSeqNum(), PcodeOp::insertiter, PcodeOp::isDead(), PcodeOp::isInstructionStart(), and PcodeOp::nextOp().
PcodeOp * PcodeOpBank::findOp (const SeqNum & num) const
Find a PcodeOp by sequence number.
Parameters
num is the given sequence number
Returns
the matching PcodeOp (or NULL)
Referenced by Funcdata::findOp(), FlowInfo::findRelTarget(), and FlowInfo::target().
void PcodeOpBank::insertAfterDead (PcodeOp * op, PcodeOp * prev)
Insert the given PcodeOp after a point in the dead list.
The op is moved to right after a specified op in the dead list.
Parameters
op is the given PcodeOp to move
prev is the specified op in the dead list
References PcodeOp::insertiter, and PcodeOp::isDead().
Referenced by Funcdata::opDeadInsertAfter().
void PcodeOpBank::markAlive (PcodeOp * op)
Mark the given PcodeOp as alive.
The PcodeOp is moved out of the dead list into the alive list. The PcodeOp::isDead() method will now return false.
Parameters
op is the given PcodeOp to mark
References PcodeOp::clearFlag(), PcodeOp::dead, and PcodeOp::insertiter.
Referenced by Funcdata::opInsert().
void PcodeOpBank::markDead (PcodeOp * op)
Mark the given PcodeOp as dead.
The PcodeOp is moved out of the alive list into the dead list. The PcodeOp::isDead() method will now return true.
Parameters
op is the given PcodeOp to mark
References PcodeOp::dead, PcodeOp::insertiter, and PcodeOp::setFlag().
Referenced by Funcdata::opDestroy(), and Funcdata::opUninsert().
void PcodeOpBank::markIncidentalCopy (PcodeOp * firstop, PcodeOp * lastop)
Mark any COPY ops in the given range as incidental.
Incidental COPYs are not considered active use of parameter passing Varnodes by parameter analysis algorithms.
Parameters
firstop is the start of the range of incidental COPY ops
lastop is the end of the range of incidental COPY ops
References PcodeOp::code(), CPUI_COPY, PcodeOp::incidental_copy, PcodeOp::insertiter, and PcodeOp::setAdditionalFlag().
Referenced by FlowInfo::doInjection().
void PcodeOpBank::moveSequenceDead (PcodeOp * firstop, PcodeOp * lastop, PcodeOp * prev)
Move a sequence of PcodeOps to a point in the dead list.
The point is right after a provided op. All ops must be in the dead list.
Parameters
firstop is the first PcodeOp in the sequence to be moved
lastop is the last PcodeOp in the sequence to be moved
prev is the provided point to move to
References PcodeOp::insertiter.
Referenced by FlowInfo::doInjection(), and Funcdata::inlineFlow().
void PcodeOpBank::removeFromCodeList (PcodeOp * op) private
Remove given PcodeOp from specific op-code list.
Remove the PcodeOp from its list of ops with the same op-code. Currently only certain op-codes have a dedicated list.
Parameters
op is the given PcodeOp
References PcodeOp::code(), PcodeOp::codeiter, CPUI_CALLOTHER, CPUI_LOAD, CPUI_RETURN, and CPUI_STORE.
PcodeOp * PcodeOpBank::target (const Address & addr) const
Find the first executing PcodeOp for a target address.
Find the first PcodeOp at or after the given Address assuming they have not yet been broken up into basic blocks. Take into account delay slots.
Parameters
addr is the given Address
Returns
the targeted PcodeOp (or NULL)
References PcodeOp::target().
Referenced by Funcdata::target().
The documentation for this class was generated from the following files:
op.hh
op.cc