decompiler: ProtoModelMerged Class Reference
ProtoModelMerged Class Reference
A prototype model made by merging together other models.
#include <fspec.hh>
Public Member Functions
ProtoModelMerged (Architecture *g)
Constructor.
virtual ~ProtoModelMerged (void)
Destructor.
int4 numModels (void) const
Get the number of constituent models.
ProtoModel * getModel (int4 i) const
Get the i-th model.
void foldIn (ProtoModel *model)
Fold-in an additional prototype model.
ProtoModel * selectModel (ParamActive *active) const
Select the best model given a set of trials.
virtual bool isMerged (void) const
Is this a merged prototype model.
virtual void restoreXml (const Element *el)
Restore this model from an XML stream.
Public Member Functions inherited from ProtoModel
ProtoModel (Architecture *g)
Constructor for use with restoreXml()
ProtoModel (const string &nm, const ProtoModel &op2)
Copy constructor changing the name.
virtual ~ProtoModel (void)
Destructor.
const string & getName (void) const
Get the name of the prototype model.
Architecture * getArch (void) const
Get the owning Architecture.
uint4 hasEffect (const Address &addr, int4 size) const
Determine side-effect of this on the given memory range.
int4 getExtraPop (void) const
Get the stack-pointer extrapop for this model.
void setExtraPop (int4 ep)
Set the stack-pointer extrapop.
int4 getInjectUponEntry (void) const
Get the inject uponentry id.
int4 getInjectUponReturn (void) const
Get the inject uponreturn id.
bool isCompatible (const ProtoModel *op2) const
Return true if other given model can be substituted for this.
void deriveInputMap (ParamActive *active) const
Given a list of input trials, derive the most likely input prototype.
void deriveOutputMap (ParamActive *active) const
Given a list of output trials, derive the most likely output prototype.
void assignParameterStorage (const vector< Datatype * > &typelist, vector< ParameterPieces > &res, bool ignoreOutputError)
Calculate input and output storage locations given a function prototype.
bool checkInputJoin (const Address &hiaddr, int4 hisize, const Address &loaddr, int4 losize) const
Check if the given two input storage locations can represent a single logical parameter.
bool checkOutputJoin (const Address &hiaddr, int4 hisize, const Address &loaddr, int4 losize) const
Check if the given two output storage locations can represent a single logical return value.
bool checkInputSplit (const Address &loc, int4 size, int4 splitpoint) const
Check if it makes sense to split a single storage location into two input parameters.
const RangeList & getLocalRange (void) const
Get the range of (possible) local stack variables.
const RangeList & getParamRange (void) const
Get the range of (possible) stack parameters.
vector< EffectRecord >::const_iterator effectBegin (void) const
Get an iterator to the first EffectRecord.
vector< EffectRecord >::const_iterator effectEnd (void) const
Get an iterator to the last EffectRecord.
int4 numLikelyTrash (void) const
Get the number of likelytrash locations.
const VarnodeData & getLikelyTrash (int4 i) const
Get the i-th likelytrashh location.
int4 characterizeAsInputParam (const Address &loc, int4 size) const
Characterize whether the given range overlaps parameter storage.
bool possibleInputParam (const Address &loc, int4 size) const
Does the given storage location make sense as an input parameter.
bool possibleOutputParam (const Address &loc, int4 size) const
Does the given storage location make sense as a return value.
bool possibleInputParamWithSlot (const Address &loc, int4 size, int4 &slot, int4 &slotsize) const
Pass-back the slot and slot size for the given storage location as an input parameter.
bool possibleOutputParamWithSlot (const Address &loc, int4 size, int4 &slot, int4 &slotsize) const
Pass-back the slot and slot size for the given storage location as a return value.
bool unjustifiedInputParam (const Address &loc, int4 size, VarnodeData &res) const
Check if the given storage location looks like an unjustified input parameter.
OpCode assumedInputExtension (const Address &addr, int4 size, VarnodeData &res) const
Get the type of extension and containing input parameter for the given storage.
OpCode assumedOutputExtension (const Address &addr, int4 size, VarnodeData &res) const
Get the type of extension and containing return value location for the given storage.
bool getBiggestContainedInputParam (const Address &loc, int4 size, VarnodeData &res) const
Pass-back the biggest input parameter contained within the given range.
AddrSpace * getSpacebase (void) const
Get the stack space associated with this model.
bool isStackGrowsNegative (void) const
Return true if the stack grows toward smaller addresses.
bool hasThisPointer (void) const
Is this a model for (non-static) class methods.
bool isConstructor (void) const
Is this model for class constructors.
int4 getMaxInputDelay (void) const
Return the maximum heritage delay across all possible input parameters.
int4 getMaxOutputDelay (void) const
Return the maximum heritage delay across all possible return values.
Private Member Functions
void intersectEffects (const vector< EffectRecord > &efflist)
Fold EffectRecords into this model.
void intersectLikelyTrash (const vector< VarnodeData > &trashlist)
Fold likelytrash locations into this model.
Private Attributes
vector< ProtoModel * > modellist
Constituent models being merged.
Additional Inherited Members
Public Types inherited from ProtoModel
enum { extrapop_unknown = 0x8000 }
Static Public Member Functions inherited from ProtoModel
static uint4 lookupEffect (const vector< EffectRecord > &efflist, const Address &addr, int4 size)
Look up an effect from the given EffectRecord list.
Detailed Description
A prototype model made by merging together other models.
This model serves as a placeholder for multiple models, when the exact model hasn't been immediately determined. At the time of active parameter recovery the correct model is selected for the given set of trials from among the constituent prototype models used to build this, by calling the method selectModel(). Up to this time, this serves as a merged form of the models so that all potential parameter trials will be included in the analysis. The parameter recovery for the output part of the model is currently limited, so the constituent models must all share the same output model, and this part is not currently merged.
Member Function Documentation
void ProtoModelMerged::foldIn (ProtoModel * model)
Fold-in an additional prototype model.
Parameters
model is the new prototype model to add to the merge
References RangeList::begin(), ProtoModel::effectlist, RangeList::end(), ProtoModel::extrapop, ProtoModel::extrapop_unknown, ParamList::getType(), ProtoModel::glb, ProtoModel::injectUponEntry, ProtoModel::injectUponReturn, ProtoModel::input, ProtoModel::likelytrash, ProtoModel::localrange, ProtoModel::output, ParamList::p_register, ParamList::p_standard, and ProtoModel::paramrange.
void ProtoModelMerged::intersectEffects (const vector< EffectRecord > & efflist) private
Fold EffectRecords into this model.
The EffectRecord lists are intersected. Anything in this that is not also in the given EffectRecord list is removed.
Parameters
efflist is the given EffectRecord list
void ProtoModelMerged::intersectLikelyTrash (const vector< VarnodeData > & trashlist) private
Fold likelytrash locations into this model.
The likely-trash locations are intersected. Anything in this that is not also in the given likely-trash list is removed.
Parameters
trashlist is the given likely-trash list
void ProtoModelMerged::restoreXml (const Element * el) virtual
Restore this model from an XML stream.
Read in details about this model from a <prototype> tag
Parameters
el is the <prototype> element
Reimplemented from ProtoModel.
References Element::getAttributeValue(), Element::getChildren(), and AddrSpace::name.
Referenced by ProtoModel::isMerged().
ProtoModel * ProtoModelMerged::selectModel (ParamActive * active) const
Select the best model given a set of trials.
The model that best matches the given set of input parameter trials is returned. This method currently uses the ScoreProtoModel object to score the different prototype models.
Parameters
active is the set of parameter trials
Returns
the prototype model that scores the best
References ScoreProtoModel::addParameter(), ScoreProtoModel::doScore(), ParamActive::getNumTrials(), ScoreProtoModel::getScore(), and ParamActive::getTrial().
Referenced by FuncProto::resolveModel().
The documentation for this class was generated from the following files:
fspec.hh
fspec.cc