decompiler: StackSolver Class Reference
StackSolver Class Reference
A class that solves for stack-pointer changes across unknown sub-functions.
Public Member Functions
void solve (void)
Solve the system of equations.
void build (const Funcdata &data, AddrSpace *id, int4 spcbase)
Build the system of equations.
int4 getNumVariables (void) const
Get the number of variables in the system.
Varnode * getVariable (int4 i) const
Get the i-th Varnode variable.
int4 getCompanion (int4 i) const
Get the i-th variable's companion index.
int4 getSolution (int4 i) const
Get the i-th variable's solution.
Private Member Functions
void duplicate (void)
Duplicate each equation, multiplying by -1.
void propagate (int4 varnum, int4 val)
Propagate solution for one variable to other variables.
Private Attributes
vector< StackEqn > eqs
Known equations based on operations that explicitly change the stack-pointer.
vector< StackEqn > guess
Guessed equations for underdetermined systems.
vector< Varnode * > vnlist
The indexed set of variables, one for each reference to the stack-pointer.
vector< int4 > companion
Index of companion input for variable produced by CPUI_INDIRECT.
Address spacebase
Starting address of the stack-pointer.
vector< int4 > soln
Collected solutions (corresponding to array of variables)
int4 missedvariables
Number of variables for which we are missing an equation.
Detailed Description
A class that solves for stack-pointer changes across unknown sub-functions.
Member Function Documentation
void StackSolver::build (const Funcdata & data, AddrSpace * id, int4 spcbase)
Build the system of equations.
Collect references to the stack-pointer as variables, and examine their defining PcodeOps to determine equations and coefficient.
Parameters
data is the function being analyzed
id is the stack address space
spcbase is the index, relative to the stack space, of the stack pointer
References Funcdata::beginLoc(), PcodeOp::code(), Varnode::comparePointers(), CPUI_COPY, CPUI_INDIRECT, CPUI_INT_ADD, CPUI_INT_AND, CPUI_MULTIEQUAL, Funcdata::endLoc(), ProtoModel::extrapop_unknown, Varnode::getAddr(), Funcdata::getCallSpecs(), Varnode::getDef(), PcodeOp::getIn(), Varnode::getOffset(), PcodeOp::getOpFromConst(), Varnode::getSpace(), AddrSpace::getSpacebase(), AddrSpace::getType(), IPTR_IOP, Varnode::isConstant(), PcodeOp::numInput(), StackEqn::rhs, StackEqn::var1, and StackEqn::var2.
Referenced by ActionStackPtrFlow::analyzeExtraPop().
void StackSolver::propagate (int4 varnum, int4 val) private
Propagate solution for one variable to other variables.
Given a solution for one variable, look for equations containing the variable and attempt to solve for the other variable. Continue propagating new solutions to other equations to find even more solutions. Populate the soln array with the solutions.
Parameters
varnum is the index of the initial variable
val is the solution for the variable
References StackEqn::compare(), StackEqn::var1, and StackEqn::var2.
The documentation for this class was generated from the following file:
coreaction.cc