decompiler: ActionFuncLink Class Reference
ActionFuncLink Class Reference
Prepare for data-flow analysis of function parameters.
#include <coreaction.hh>
Public Member Functions
ActionFuncLink (const string &g)
Constructor.
virtual Action * clone (const ActionGroupList &grouplist) const
Clone the Action.
virtual int4 apply (Funcdata &data)
Make a single attempt to apply this Action.
Public Member Functions inherited from Action
Action (uint4 f, const string &nm, const string &g)
Base constructor for an Action.
virtual ~Action (void)
Destructor.
virtual void printStatistics (ostream &s) const
Dump statistics to stream.
int4 perform (Funcdata &data)
Perform this action (if necessary)
bool setBreakPoint (uint4 tp, const string &specify)
Set a breakpoint on this action.
virtual void clearBreakPoints (void)
Clear all breakpoints set on this Action.
bool setWarning (bool val, const string &specify)
Set a warning on this action.
bool disableRule (const string &specify)
Disable a specific Rule within this.
bool enableRule (const string &specify)
Enable a specific Rule within this.
const string & getName (void) const
Get the Action's name.
const string & getGroup (void) const
Get the Action's group.
uint4 getStatus (void) const
Get the current status of this Action.
uint4 getNumTests (void)
Get the number of times apply() was invoked.
uint4 getNumApply (void)
virtual void reset (Funcdata &data)
Reset the Action for a new function.
virtual void resetStats (void)
Reset all the counts to zero.
virtual int4 print (ostream &s, int4 num, int4 depth) const
Print a description of this Action to stream.
virtual void printState (ostream &s) const
Print status to stream.
virtual void saveXml (ostream &s) const
Save specifics of this action to stream.
virtual void restoreXml (const Element *el, Funcdata *fd)
Load specifics of action from XML.
virtual Action * getSubAction (const string &specify)
Retrieve a specific sub-action by name.
virtual Rule * getSubRule (const string &specify)
Retrieve a specific sub-rule by name.
Static Private Member Functions
static void funcLinkInput (FuncCallSpecs *fc, Funcdata &data)
Set up the parameter recovery process for a single sub-function call.
static void funcLinkOutput (FuncCallSpecs *fc, Funcdata &data)
Set up the return value recovery process for a single sub-function call.
Friends
class ActionFuncLinkOutOnly
Additional Inherited Members
Public Types inherited from Action
enum ruleflags {
rule_repeatapply = 4, rule_onceperfunc = 8, rule_oneactperfunc = 16, rule_debug = 32,
rule_warnings_on = 64, rule_warnings_given = 128
}
Boolean behavior properties governing this particular Action.
enum statusflags {
status_start =1, status_breakstarthit =2, status_repeat =4, status_mid =8,
status_end =16, status_actionbreak =32
}
Boolean properties describing the status of an action.
enum breakflags { break_start = 1, tmpbreak_start = 2, break_action = 4, tmpbreak_action = 8 }
Break points associated with an Action.
Protected Member Functions inherited from Action
void issueWarning (Architecture *glb)
Warn that this Action has applied.
bool checkStartBreak (void)
Check start breakpoint.
bool checkActionBreak (void)
Check action breakpoint.
void turnOnWarnings (void)
Enable warnings for this Action.
void turnOffWarnings (void)
Disable warnings for this Action.
Protected Attributes inherited from Action
int4 lcount
Changes not including last call to apply()
int4 count
Number of changes made by this action so far.
uint4 status
Current status.
uint4 breakpoint
Breakpoint properties.
uint4 flags
Behavior properties.
uint4 count_tests
Number of times apply() has been called.
uint4 count_apply
Number of times apply() made changes.
string name
Name of the action.
string basegroup
Base group this action belongs to.
Detailed Description
Prepare for data-flow analysis of function parameters.
If exact prototypes are known for sub-functions, insert the appropriate Varnodes to match the parameters. If not known, prepare the sub-function for the parameter recovery process.
Member Function Documentation
int4 ActionFuncLink::apply (Funcdata & data) virtual
Make a single attempt to apply this Action.
This is the main entry point for applying changes to a function that are specific to this Action. The method can inspect whatever it wants to decide if the Action does or does not apply. Changes are indicated by incrementing the count field.
Parameters
data is the function to inspect/modify
Returns
0 for a complete application, -1 for a partial completion (due to breakpoint)
Implements Action.
References Funcdata::getCallSpecs(), and Funcdata::numCalls().
virtual Action* ActionFuncLink::clone (const ActionGroupList & grouplist) const inline virtual
Clone the Action.
If this Action is a member of one of the groups in the grouplist, this returns a clone of the Action, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Action or NULL
Implements Action.
References ActionStart::apply(), ActionGroupList::contains(), and Action::getGroup().
void ActionFuncLink::funcLinkInput (FuncCallSpecs * fc, Funcdata & data) static private
Set up the parameter recovery process for a single sub-function call.
If the prototype is known (locked), insert stub Varnodes If the prototype is varargs (dotdotdot), set up recovery of variable Varnodes
Parameters
fc is the given sub-function
data is the function being analyzed
References FuncCallSpecs::getActiveInput(), ProtoParameter::getAddress(), Address::getOffset(), FuncCallSpecs::getOp(), FuncProto::getParam(), ProtoParameter::getSize(), Address::getSpace(), FuncProto::getSpacebase(), ParamActive::getTrial(), AddrSpace::getType(), FuncCallSpecs::initActiveInput(), IPTR_SPACEBASE, FuncProto::isDotdotdot(), FuncProto::isInputLocked(), ParamTrial::markActive(), Funcdata::newVarnode(), PcodeOp::numInput(), FuncProto::numParams(), Funcdata::opInsertInput(), Funcdata::opStackLoad(), ParamActive::registerTrial(), Varnode::setSpacebasePlaceholder(), and FuncCallSpecs::setStackPlaceholderSlot().
void ActionFuncLink::funcLinkOutput (FuncCallSpecs * fc, Funcdata & data) static private
Set up the return value recovery process for a single sub-function call.
If the prototype is known(locked), insert an output Varnode on the call If the prototype is unknown set-up the ParamActive, so that outputs will be "gathered"
Parameters
fc is the given sub-function
data is the function being analyzed
References FuncProto::assumedOutputExtension(), CPUI_COPY, CPUI_INT_SEXT, CPUI_INT_ZEXT, CPUI_PIECE, VarnodeData::getAddr(), PcodeOp::getAddr(), ProtoParameter::getAddress(), Datatype::getMetatype(), FuncCallSpecs::getOp(), FuncProto::getOutput(), ProtoParameter::getSize(), ProtoParameter::getType(), FuncCallSpecs::initActiveOutput(), FuncProto::isOutputLocked(), Funcdata::newOp(), Funcdata::newVarnode(), Funcdata::newVarnodeOut(), Funcdata::opInsertAfter(), Funcdata::opSetInput(), Funcdata::opSetOpcode(), VarnodeData::size, TYPE_INT, and TYPE_VOID.
Referenced by ActionFuncLinkOutOnly::apply().
The documentation for this class was generated from the following files:
coreaction.hh
coreaction.cc