decompiler: CompilerTag Class Reference
CompilerTag Class Reference
Contents of a <compiler> tag in a .ldefs file.
#include <sleigh_arch.hh>
Public Member Functions
CompilerTag (void)
Constructor.
void restoreXml (const Element *el)
Restore the record from an XML stream.
const string & getName (void) const
Get the human readable name of the spec.
const string & getSpec (void) const
Get the file-name.
const string & getId (void) const
Get the string used as part of language id.
Private Attributes
string name
(Human readable) name of the compiler
string spec
cspec file for this compiler
string id
Unique id for this compiler.
Detailed Description
Contents of a <compiler> tag in a .ldefs file.
This class describes a compiler specification file as referenced by the Sleigh language subsystem.
Member Function Documentation
void CompilerTag::restoreXml (const Element * el)
Restore the record from an XML stream.
Read file attributes from an XML <compiler> tag
Parameters
el is the XML element
References Element::getAttributeValue(), name, and spec.
Referenced by CompilerTag(), and LanguageDescription::LanguageDescription().
The documentation for this class was generated from the following files:
sleigh_arch.hh
sleigh_arch.cc