decompiler: ActionMarkExplicit::OpStackElement Struct Reference
ActionMarkExplicit::OpStackElement Struct Reference
This class holds a single entry in a stack used to traverse Varnode expressions.
Public Member Functions
OpStackElement (Varnode *v)
Constructor.
Public Attributes
Varnode * vn
The Varnode at this particular point in the path.
int4 slot
The slot of the first input Varnode to traverse in this subexpression.
int4 slotback
The slot(+1) of the last input Varnode to traverse in this subexpression.
Detailed Description
This class holds a single entry in a stack used to traverse Varnode expressions.
Constructor & Destructor Documentation
ActionMarkExplicit::OpStackElement::OpStackElement (Varnode * v)
Constructor.
Record the Varnode just encountered and set-up the next (backward) edges to traverse.
Parameters
v is the Varnode just encountered
References PcodeOp::code(), CPUI_LOAD, CPUI_PTRADD, Varnode::getDef(), Varnode::isWritten(), and PcodeOp::numInput().
The documentation for this struct was generated from the following files:
coreaction.hh
coreaction.cc