decompiler: OpFollow Struct Reference
OpFollow Struct Reference
A simple node used to dynamically define a sequence of operations.
#include <userop.hh>
Public Member Functions
OpFollow (void)
Construct an empty object.
void restoreXml (const Element *el)
Restore this node from an XML stream.
Public Attributes
OpCode opc
The particular p-code operation.
uintb val
A possible constant second input.
int4 slot
Slot to follow.
Detailed Description
A simple node used to dynamically define a sequence of operations.
This should be deprecated in favor of ExecutablePcode objects. This class holds a single operation (within a sequence). It acts on the output of the previous operation with an optional constant value as the second input.
Member Function Documentation
void OpFollow::restoreXml (const Element * el)
Restore this node from an XML stream.
Process either a <baseop> or <innerop> element. Currently this only supports INT_ZEXT, INT_LEFT, and INT_AND operations
Parameters
el is the root XML element
References CPUI_INT_AND, CPUI_INT_LEFT, CPUI_INT_ZEXT, Element::getAttributeName(), Element::getAttributeValue(), Element::getNumAttributes(), and UserPcodeOp::name.
The documentation for this struct was generated from the following files:
userop.hh
userop.cc