decompiler: VarnodeCompareLocDef Struct Reference
VarnodeCompareLocDef Struct Reference
Compare two Varnode pointers by location then definition.
#include <varnode.hh>
Public Member Functions
bool operator() (const Varnode *a, const Varnode *b) const
Functional comparison operator.
Detailed Description
Compare two Varnode pointers by location then definition.
Member Function Documentation
bool VarnodeCompareLocDef::operator() (const Varnode * a, const Varnode * b) const inline
Functional comparison operator.
Compare by location then by definition. This is the same as the normal varnode compare, but we distinguish identical frees by their pointer address. Thus varsets defined with this comparison act like multisets for free varnodes and like unique sets for everything else (with respect to the standard varnode comparison)
Parameters
a is the first Varnode to compare
b is the second Varnode to compare
Returns
true if a occurs earlier than b
References Varnode::getAddr(), Varnode::getCreateIndex(), Varnode::getDef(), Varnode::getFlags(), PcodeOp::getSeqNum(), Varnode::getSize(), Varnode::input, and Varnode::written.
The documentation for this struct was generated from the following files:
varnode.hh
varnode.cc